import Foundation

/// Generates typed Swift client from Luxo schema introspection.
///
/// Usage:
///   let codegen = LuxoCodegen(endpoint: "http://localhost:4000/luvia", introspectionKey: "KEY")
///   try await codegen.generate(outputDir: "Sources/Generated", packageName: "LuxoGenerated")
///
/// Generates:
///   - Models.swift — Codable structs for all models
///   - Client.swift — Typed API methods with async/await
///   - SelectHints.swift — Pre-computed field hints (if analyze was run)
public final class LuxoCodegen {
    private let endpoint: String
    private let key: String

    public init(endpoint: String, introspectionKey: String) {
        self.endpoint = endpoint
        self.key = introspectionKey
    }

    /// Fetch schema and generate Swift files.
    public func generate(outputDir: String, packageName: String = "LuxoGenerated") async throws {
        // Fetch schema
        let schema = try await fetchSchema()

        let fm = FileManager.default
        try? fm.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

        // Generate Models.swift
        let modelsCode = generateModels(schema)
        try modelsCode.write(toFile: "\(outputDir)/Models.swift", atomically: true, encoding: .utf8)

        // Generate Client.swift
        let clientCode = generateClient(schema)
        try clientCode.write(toFile: "\(outputDir)/Client.swift", atomically: true, encoding: .utf8)

        print("[luxo] Generated Swift client → \(outputDir)/")
    }

    private func fetchSchema() async throws -> LuxoSchema {
        var request = URLRequest(url: URL(string: endpoint)!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(key, forHTTPHeaderField: "X-Introspection-Key")
        request.httpBody = try JSONSerialization.data(withJSONObject: ["$api": "__schema"])

        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(LuxoSchema.self, from: data)
    }

    private func generateModels(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\n\n"

        for (_, model) in schema.models.sorted(by: { $0.key < $1.key }) {
            out += "public struct \(model.name): Codable, Sendable {\n"
            for field in model.fields {
                let swiftType = mapType(field.type, nullable: field.nullable ?? false, list: field.list ?? false)
                out += "    public let \(field.name): \(swiftType)\n"
            }
            out += "}\n\n"
        }
        return out
    }

    private func generateClient(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\nimport LuxoClient\n\n"
        out += "public final class LuxoGeneratedClient {\n"
        out += "    private let transport: Transport\n\n"
        out += "    public init(transport: Transport) {\n"
        out += "        self.transport = transport\n"
        out += "    }\n\n"

        for (_, api) in schema.apis.sorted(by: { $0.key < $1.key }) {
            let returnType = api.returnType ?? "Void"
            let swiftReturn = mapType(returnType, nullable: false, list: api.returnList ?? false)

            // Build params
            var paramList = ""
            var paramMap = ""
            if let params = api.params {
                let parts = params.map { p in
                    let t = mapType(p.type, nullable: !(p.required ?? true), list: false)
                    return "\(p.name): \(t)"
                }
                paramList = parts.joined(separator: ", ")
                paramMap = params.map { "\"\($0.name)\": \($0.name)" }.joined(separator: ", ")
            }

            out += "    public func \(api.name)(\(paramList)) async throws -> \(swiftReturn) {\n"
            if paramMap.isEmpty {
                out += "        let result = try await transport.call(\"\(api.name)\")\n"
            } else {
                out += "        let result = try await transport.call(\"\(api.name)\", params: [\(paramMap)])\n"
            }
            out += "        let data = try JSONSerialization.data(withJSONObject: result)\n"
            out += "        return try JSONDecoder().decode(\(swiftReturn).self, from: data)\n"
            out += "    }\n\n"
        }

        out += "}\n"
        return out
    }

    private func mapType(_ type: String, nullable: Bool, list: Bool) -> String {
        let base: String
        switch type {
        case "Int": base = "Int"
        case "Float": base = "Double"
        case "String": base = "String"
        case "Boolean": base = "Bool"
        case "DateTime": base = "Date"
        case "Duration": base = "TimeInterval"
        case "UUID": base = "UUID"
        default: base = type
        }

        let result = list ? "[\(base)]" : base
        return nullable ? "\(result)?" : result
    }
}
