package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/ast"
	"github.com/light-speak/luxo/pkg/semantic"
)

// GenerateResult holds all generated Go source files.
type GenerateResult struct {
	Files map[string][]byte // filename → Go source
}

// Generate produces Go source files from semantic analysis result.
func Generate(result *semantic.Result, packageName string, softModels ...map[string]bool) *GenerateResult {
	gr := &GenerateResult{
		Files: make(map[string][]byte),
	}
	enums := collectEnums(result)

	gr.Files["model.gen.go"] = generateModelFile(result, packageName, enums)

	if dbSrc := generateDBFile(result, packageName, enums); dbSrc != nil {
		gr.Files["db.gen.go"] = dbSrc
	}
	if appSrc := generateAppFile(result, packageName, enums); appSrc != nil {
		gr.Files["app.gen.go"] = appSrc
	}
	var soft map[string]bool
	if len(softModels) > 0 {
		soft = softModels[0]
	}
	if dlSrc := generateDataLoaderFile(result, packageName, enums, soft); dlSrc != nil {
		gr.Files["dataloader.gen.go"] = dlSrc
	}
	if handlerSrc := generateHandlerFile(result, packageName, enums); handlerSrc != nil {
		gr.Files["handler.gen.go"] = handlerSrc
	}
	if nativeSrc := GenerateNativeFile(result, packageName); nativeSrc != nil {
		gr.Files["native.gen.go"] = nativeSrc
	}

	// event.gen.go — typed event structs + emit functions + listener registration
	if eventSrc := generateEventFile(result, packageName); eventSrc != nil {
		gr.Files["event.gen.go"] = eventSrc
	}

	// error.gen.go — typed error constructors
	if errorSrc := generateErrorFile(result, packageName); errorSrc != nil {
		gr.Files["error.gen.go"] = errorSrc
	}

	// writejson.gen.go — per-model WriteJSON for single-pass field-filtered serialization
	if wjSrc := generateWriteJSONFile(result, packageName, enums); wjSrc != nil {
		gr.Files["writejson.gen.go"] = wjSrc
	}

	return gr
}

// generateModelFile produces the model.gen.go file containing enums and structs.
func generateModelFile(result *semantic.Result, packageName string, enums map[string]bool) []byte {
	var b strings.Builder

	writeHeader(&b, packageName, "model.gen.go")
	writeImports(&b, result.Files)

	// enums first (structs may reference them)
	for _, file := range result.Files {
		for _, e := range file.Enums {
			generateEnum(&b, e)
			b.WriteByte('\n')
		}
	}

	modelNames := make(map[string]bool)
	for _, file := range result.Files {
		for _, m := range file.Models {
			modelNames[m.Name] = true
		}
	}

	// extend stubs — generate minimal structs for external types
	for _, file := range result.Files {
		for _, ext := range file.Extends {
			if modelNames[ext.Name] {
				continue // already defined as a full model in this file
			}
			generateExtendStub(&b, ext)
			b.WriteByte('\n')
		}
	}

	// model structs
	for _, file := range result.Files {
		for _, m := range file.Models {
			generateModel(&b, m, enums)
			b.WriteByte('\n')
		}
	}

	return []byte(b.String())
}

func writeHeader(b *strings.Builder, packageName, sourceFile string) {
	fmt.Fprintf(b, "// Code generated by luxo. DO NOT EDIT.\n")
	fmt.Fprintf(b, "// Source: %s\n\n", sourceFile)
	fmt.Fprintf(b, "package %s\n\n", packageName)
}

// modelImportNeeds tracks which imports model.gen.go requires.
type modelImportNeeds struct {
	time    bool
	uuid    bool
	decimal bool
}

// scanModelFieldImports checks a single field for import needs in model.gen.go.
func scanModelFieldImports(f *ast.FieldDecl, needs *modelImportNeeds) {
	if f.Computed != nil || f.Type == nil {
		return
	}
	switch f.Type.Name {
	case "DateTime", "Duration":
		needs.time = true
	case "UUID":
		needs.uuid = true
	case "Decimal":
		needs.decimal = true
	}
}

// writeImports writes import block for model.gen.go.
func writeImports(b *strings.Builder, files []*ast.File) {
	var needs modelImportNeeds
	for _, file := range files {
		for _, m := range file.Models {
			if isSoftDelete(m) && !hasDeletedAtField(m.Fields) {
				needs.time = true
			}
			for _, f := range m.Fields {
				scanModelFieldImports(f, &needs)
			}
		}
	}

	if !needs.time && !needs.uuid && !needs.decimal {
		return
	}

	b.WriteString("import (\n")
	if needs.time {
		b.WriteString("\t\"time\"\n")
	}
	if needs.uuid {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if needs.decimal {
		b.WriteString("\t\"github.com/shopspring/decimal\"\n")
	}
	b.WriteString(")\n\n")
}

// generateDBFile produces the db.gen.go file containing query builders.
// Returns nil if there are no models.
func generateDBFile(result *semantic.Result, packageName string, enums map[string]bool) []byte {
	hasModels := false
	for _, file := range result.Files {
		if len(file.Models) > 0 {
			hasModels = true
			break
		}
	}
	if !hasModels {
		return nil
	}

	var b strings.Builder

	writeHeader(&b, packageName, "db.gen.go")
	writeDBImports(&b, result.Files)

	// Collect model names to skip generating scanners for models that already exist
	modelNames := make(map[string]bool)
	for _, file := range result.Files {
		for _, m := range file.Models {
			modelNames[m.Name] = true
		}
	}

	// Generate scanners for extend stubs (needed by DataLoader batch functions)
	for _, file := range result.Files {
		for _, ext := range file.Extends {
			if modelNames[ext.Name] {
				continue // full model exists, has its own scanner
			}
			generateScanner(&b, &ast.ModelDecl{Name: ext.Name, Fields: ext.Fields})
			b.WriteByte('\n')
		}
	}

	for _, file := range result.Files {
		for _, m := range file.Models {
			generateQueryBuilder(&b, m, enums)
			b.WriteByte('\n')
		}
	}

	return []byte(b.String())
}

// dbImportNeeds tracks which imports db.gen.go requires.
type dbImportNeeds struct {
	time    bool
	uuid    bool
	decimal bool
}

// scanDBModelImports checks model-level directives for import needs.
func scanDBModelImports(m *ast.ModelDecl, needs *dbImportNeeds) {
	if isSoftDelete(m) {
		needs.time = true // SoftDelete uses time.Now()
	}
}

// scanDBFieldImports checks a single field for import needs in db.gen.go.
func scanDBFieldImports(f *ast.FieldDecl, needs *dbImportNeeds) {
	if f.Computed != nil || f.Type == nil {
		return
	}
	// Auto-fill needs
	if f.Type.Name == "DateTime" && (f.Name == "createdAt" || f.Name == "updatedAt") {
		needs.time = true
	}
	if hasDirective(f.Directives, "auto") && f.Type.Name == "UUID" {
		needs.uuid = true
	}
	// CreateInput struct field types
	if hasDirective(f.Directives, "internal") || isAutoManaged(f) {
		return
	}
	switch f.Type.Name {
	case "DateTime", "Duration":
		needs.time = true
	case "UUID":
		needs.uuid = true
	case "Decimal":
		needs.decimal = true
	}
}

// generateAppFile produces app.gen.go containing the App struct that wires all Clients.
// Returns nil if there are no models.
func generateAppFile(result *semantic.Result, packageName string, enums map[string]bool) []byte {
	var models []string
	for _, file := range result.Files {
		for _, m := range file.Models {
			models = append(models, m.Name)
		}
	}
	if len(models) == 0 {
		return nil
	}

	var b strings.Builder
	writeHeader(&b, packageName, "app.gen.go")

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\n\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/pg\"\n")
	b.WriteString(")\n\n")

	// Check if any model has relations (needs loaders field)
	hasRelations := false
	for _, file := range result.Files {
		for _, m := range file.Models {
			if len(analyzeRelations(m, enums)) > 0 {
				hasRelations = true
				break
			}
		}
	}

	// App struct
	b.WriteString("// App is the entry point for all database operations.\n")
	b.WriteString("type App struct {\n")
	b.WriteString("\tDB *pg.DB\n")
	for _, name := range models {
		fmt.Fprintf(&b, "\t%s *%sClient\n", name, name)
	}
	if hasRelations {
		b.WriteString("\tloaders Loaders\n")
	}
	b.WriteString("}\n\n")

	// New function
	b.WriteString("// New creates an App by reading DATABASE_* config from the environment.\n")
	b.WriteString("// Call env.Load(\".env\") before New() if using a .env file.\n")
	b.WriteString("func New(ctx context.Context) (*App, error) {\n")
	b.WriteString("\turl := buildDatabaseURL()\n")
	b.WriteString("\tdb, err := pg.NewDB(ctx, url)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"luxo: connect to database: %w\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn NewFromDB(db), nil\n")
	b.WriteString("}\n\n")

	// buildDatabaseURL helper
	b.WriteString("func buildDatabaseURL() string {\n")
	b.WriteString("\thost, _ := env.Get(\"DATABASE_HOST\")\n")
	b.WriteString("\tif host == \"\" { host = \"localhost\" }\n")
	b.WriteString("\tport, _ := env.Get(\"DATABASE_PORT\")\n")
	b.WriteString("\tif port == \"\" { port = \"5432\" }\n")
	b.WriteString("\tuser, _ := env.Get(\"DATABASE_USER\")\n")
	b.WriteString("\tif user == \"\" { user = \"postgres\" }\n")
	b.WriteString("\tpass, _ := env.Get(\"DATABASE_PASSWORD\")\n")
	b.WriteString("\tssl, _ := env.Get(\"DATABASE_SSL\")\n")
	b.WriteString("\tif ssl == \"\" { ssl = \"disable\" }\n")
	b.WriteString("\tprefix, _ := env.Get(\"DATABASE_PREFIX\")\n")
	b.WriteString("\tif prefix == \"\" { prefix = \"luxo\" }\n")
	b.WriteString("\treturn fmt.Sprintf(\"postgres://%s:%s@%s:%s/%s?sslmode=%s\", user, pass, host, port, prefix, ssl)\n")
	b.WriteString("}\n\n")

	// NewFromDB function
	b.WriteString("// NewFromDB creates an App from an existing *pg.DB.\n")
	b.WriteString("func NewFromDB(db *pg.DB) *App {\n")
	b.WriteString("\treturn &App{\n")
	b.WriteString("\t\tDB: db,\n")
	for _, name := range models {
		fmt.Fprintf(&b, "\t\t%s: &%sClient{db: db},\n", name, name)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Close function
	b.WriteString("// Close closes the database connection.\n")
	b.WriteString("func (a *App) Close() {\n")
	b.WriteString("\ta.DB.Close()\n")
	b.WriteString("}\n\n")

	// Tx function
	b.WriteString("// Tx runs fn inside a transaction. The App passed to fn uses the transaction\n")
	b.WriteString("// for all queries. If fn returns nil, the transaction commits; otherwise it rolls back.\n")
	b.WriteString("func (a *App) Tx(ctx context.Context, fn func(tx *App) error) error {\n")
	b.WriteString("\treturn a.DB.Tx(ctx, func(txDB *pg.DB) error {\n")
	b.WriteString("\t\treturn fn(NewFromDB(txDB))\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

// writeDBImports writes import block for db.gen.go.
func writeDBImports(b *strings.Builder, files []*ast.File) {
	var needs dbImportNeeds
	for _, file := range files {
		for _, m := range file.Models {
			scanDBModelImports(m, &needs)
			for _, f := range m.Fields {
				scanDBFieldImports(f, &needs)
			}
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	if needs.time {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n\t\"github.com/light-speak/luxo/pkg/lux\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/pg\"\n")
	if needs.uuid {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if needs.decimal {
		b.WriteString("\t\"github.com/shopspring/decimal\"\n")
	}
	b.WriteString(")\n\n")
}
