package codegen

import (
	"bytes"
	"encoding/json"
	"go/format"
	"strings"
	"testing"

	"github.com/light-speak/luxo/pkg/ast"
	"github.com/light-speak/luxo/pkg/semantic"
	"github.com/light-speak/luxo/pkg/token"
)

// buildResult creates a semantic.Result from manually constructed AST.
func buildResult(files ...*ast.File) *semantic.Result {
	return &semantic.Result{
		Files: files,
	}
}

// collapseSpaces normalizes runs of spaces/tabs to single spaces so assertions
// are insensitive to gofmt struct-field alignment.
func collapseSpaces(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	inSpace := false
	for _, r := range s {
		if r == ' ' || r == '\t' {
			inSpace = true
			continue
		}
		if inSpace {
			b.WriteByte(' ')
			inSpace = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func TestGenerateEmpty(t *testing.T) {
	result := buildResult(&ast.File{Name: "test.luxo"})
	gr := Generate(result, "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "package gen") {
		t.Errorf("missing package declaration:\n%s", src)
	}
	if !strings.Contains(src, "Code generated by luxo") {
		t.Errorf("missing header:\n%s", src)
	}
}

func TestFormatGeneratedReturnsInvalidSourceUnchanged(t *testing.T) {
	raw := []byte("package invalid {")
	if got := formatGenerated(raw); !bytes.Equal(got, raw) {
		t.Fatalf("formatGenerated() = %q, want original %q", got, raw)
	}
}

func TestGenerateIncludesStreamFile(t *testing.T) {
	file := &ast.File{
		Name: "origin/alert/event.luxo",
		Events: []*ast.EventDecl{{
			Name: "AlertFired",
			Params: []*ast.ParamDecl{
				{Name: "projectId", Type: &ast.TypeRef{Name: "Int"}},
				{Name: "alert", Type: &ast.TypeRef{Name: "Alert"}},
			},
		}},
		APIs: []*ast.ApiDecl{{
			Name:       "liveAlerts",
			ReturnType: &ast.TypeRef{Name: "Alert"},
			Directives: []*ast.Directive{{Name: "stream", Args: []*ast.NamedArg{{Value: &ast.Ident{Name: "AlertFired"}}}}},
		}},
	}

	gr := Generate(result(file), "luxo", DriverPG)
	if _, ok := gr.Files["stream.gen.go"]; !ok {
		t.Fatal("Generate should include stream.gen.go")
	}
}

func TestGenerateEnumAndModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "email", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "unique"}}},
					{Name: "role", Type: &ast.TypeRef{Name: "Role"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])

	if !strings.Contains(src, "type Role string") {
		t.Errorf("missing enum type:\n%s", src)
	}
	if !strings.Contains(src, `RoleUSER`) {
		t.Errorf("missing enum constant:\n%s", src)
	}
	if !strings.Contains(src, "type User struct") {
		t.Errorf("missing struct:\n%s", src)
	}
	if !strings.Contains(src, `db:"email"`) {
		t.Errorf("missing db tag:\n%s", src)
	}
}

func result(files ...*ast.File) *semantic.Result {
	return buildResult(files...)
}

func TestGenerateOutputIsGofmtFormatted(t *testing.T) {
	SetModelFieldIDs(map[string]map[string]int{
		"User":        {"id": 1, "name": 2, "role": 3, "createdAt": 4, "bio": 5},
		"AuthPayload": {"token": 1, "user": 2},
	})
	defer SetModelFieldIDs(nil)

	file := &ast.File{
		Name: "origin/auth/test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
		Models: []*ast.ModelDecl{
			{
				Name:       "User",
				Directives: []*ast.Directive{{Name: "crud"}},
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}, Directives: []*ast.Directive{{Name: "id"}, {Name: "auto"}}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "role", Type: &ast.TypeRef{Name: "Role"}},
					{Name: "createdAt", Type: &ast.TypeRef{Name: "DateTime"}},
					{Name: "bio", Type: &ast.TypeRef{Name: "String", Nullable: true}},
				},
			},
		},
		Types: []*ast.TypeDecl{
			{
				Name: "AuthPayload",
				Fields: []*ast.FieldDecl{
					{Name: "token", Type: &ast.TypeRef{Name: "String"}},
					{Name: "user", Type: &ast.TypeRef{Name: "User"}},
				},
			},
		},
		APIs: []*ast.ApiDecl{
			{
				Name:       "whoAmI",
				Directives: []*ast.Directive{{Name: "native"}},
				ReturnType: &ast.TypeRef{Name: "AuthPayload"},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	if len(gr.Files) == 0 {
		t.Fatal("no files generated")
	}
	for name, src := range gr.Files {
		formatted, err := format.Source(src)
		if err != nil {
			t.Errorf("%s: generated code does not parse: %v", name, err)
			continue
		}
		if !bytes.Equal(formatted, src) {
			t.Errorf("%s: output is not gofmt-formatted", name)
		}
	}
}

func TestGenerateWithTimeImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "createdAt", Type: &ast.TypeRef{Name: "DateTime"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"time"`) {
		t.Errorf("missing time import:\n%s", src)
	}
}

func TestGenerateNoTimeImportWhenNotNeeded(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Config",
				Fields: []*ast.FieldDecl{
					{Name: "key", Type: &ast.TypeRef{Name: "String"}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if strings.Contains(src, `"time"`) {
		t.Errorf("unexpected time import:\n%s", src)
	}
}

func TestGenerateDBFile(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, "UserClient") {
		t.Errorf("missing UserClient in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "pg.Query[User]") {
		t.Errorf("missing pg.Query[User] in db.gen.go:\n%s", dbSrc)
	}
}

func TestGenerateNoDBFileWhenNoModels(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	if _, ok := gr.Files["db.gen.go"]; ok {
		t.Errorf("db.gen.go should not be generated when no models exist")
	}
}

func TestGenerateWithDurationImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Task",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "timeout", Type: &ast.TypeRef{Name: "Duration"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"time"`) {
		t.Errorf("missing time import for Duration:\n%s", src)
	}
}

func TestGenerateComputedDateTimeNoTimeImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "lastActivity", Type: &ast.TypeRef{Name: "DateTime"}, Computed: &ast.ComputedField{}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if strings.Contains(src, `"time"`) {
		t.Errorf("computed DateTime should not trigger time import:\n%s", src)
	}
}

func TestGenerateWithUUIDImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Token",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"github.com/google/uuid"`) {
		t.Errorf("missing uuid import:\n%s", src)
	}
}

func TestGenerateWithDecimalImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Product",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "price", Type: &ast.TypeRef{Name: "Decimal"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"github.com/shopspring/decimal"`) {
		t.Errorf("missing decimal import:\n%s", src)
	}
}

func TestGenerateWithBytesType(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Doc",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "data", Type: &ast.TypeRef{Name: "Bytes"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "[]byte") {
		t.Errorf("missing []byte type:\n%s", src)
	}
}

func TestGenerateAutoUUIDDBImports(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Token",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}, Directives: []*ast.Directive{{Name: "auto"}}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
					{Name: "createdAt", Type: &ast.TypeRef{Name: "DateTime"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, `"github.com/google/uuid"`) {
		t.Errorf("missing uuid import in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, `"time"`) {
		t.Errorf("missing time import in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "uuid.Must(uuid.NewV7())") {
		t.Errorf("missing uuid auto-fill:\n%s", dbSrc)
	}
}

func TestGenerateNilTypeField(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Test",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "unknown", Type: nil},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "any") {
		t.Errorf("nil type should map to any:\n%s", src)
	}
}

func TestGenerateHiddenFieldJsonTag(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "password", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "hidden"}}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `json:"-"`) {
		t.Errorf("@hidden should generate json:\"-\":\n%s", src)
	}
}

func TestGenerateUUIDPrimaryKeyFind(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}, Directives: []*ast.Directive{{Name: "auto"}}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, "Find(ctx context.Context, id uuid.UUID)") {
		t.Errorf("Find should use uuid.UUID for UUID pk:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "pg.UpdateBase[User, uuid.UUID]") {
		t.Errorf("UpdateBase should use uuid.UUID as ID type:\n%s", dbSrc)
	}
}

func TestGenerateSoftDeleteModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
				},
				Directives: []*ast.Directive{{Name: "soft"}},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	modelSrc := string(gr.Files["model.gen.go"])
	dbSrc := string(gr.Files["db.gen.go"])

	// model.gen.go should have deletedAt field and time import
	if !strings.Contains(modelSrc, "DeletedAt") {
		t.Errorf("missing DeletedAt field in model:\n%s", modelSrc)
	}
	if !strings.Contains(modelSrc, "*time.Time") {
		t.Errorf("missing *time.Time for deletedAt:\n%s", modelSrc)
	}
	if !strings.Contains(modelSrc, `"time"`) {
		t.Errorf("missing time import for @soft model:\n%s", modelSrc)
	}

	// db.gen.go should have soft delete methods
	if !strings.Contains(dbSrc, "SoftDelete") {
		t.Errorf("missing SoftDelete in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "ForceDelete") {
		t.Errorf("missing ForceDelete in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "WithDeleted") {
		t.Errorf("missing WithDeleted in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "Restore") {
		t.Errorf("missing Restore in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, `"time"`) {
		t.Errorf("missing time import in db for @soft:\n%s", dbSrc)
	}
}

func TestGenerateSoftDeleteWithExistingDeletedAt(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
					{Name: "deletedAt", Type: &ast.TypeRef{Name: "DateTime", Nullable: true}},
				},
				Directives: []*ast.Directive{{Name: "soft"}},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	modelSrc := string(gr.Files["model.gen.go"])

	// Should not duplicate deletedAt
	count := strings.Count(modelSrc, "DeletedAt")
	if count != 1 {
		t.Errorf("DeletedAt should appear exactly once, got %d:\n%s", count, modelSrc)
	}
}

func TestGenerateAppFile(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
			{
				Name: "Order",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "total", Type: &ast.TypeRef{Name: "Float"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	// gofmt aligns struct fields — normalize runs of spaces for assertions
	appSrc := collapseSpaces(string(gr.Files["app.gen.go"]))

	checks := []string{
		"package gen",
		"type App struct",
		"DB *pg.DB",
		"User *UserClient",
		"Order *OrderClient",
		"func New(ctx context.Context) (*App, error)",
		"lux.DBConfigFromEnv()",
		"pg.NewDBWithConfig(ctx, cfg.ConnectionString(), cfg)",
		"func NewFromDB(db *pg.DB) *App",
		"&UserClient{db: db}",
		"&OrderClient{db: db}",
		"func (a *App) Close()",
		"func (a *App) Tx(ctx context.Context, fn func(tx *App) error) error",
		"NewFromDB(txDB)",
	}
	for _, check := range checks {
		if !strings.Contains(appSrc, check) {
			t.Errorf("missing %q in app.gen.go:\n%s", check, appSrc)
		}
	}
}

func TestGenerateAppFileNoModels(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	if _, ok := gr.Files["app.gen.go"]; ok {
		t.Error("app.gen.go should not be generated when no models exist")
	}
}

func TestGenerateAppFileWithRelations(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "posts", Type: &ast.TypeRef{Name: "Post", IsList: true}},
				},
			},
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "userId", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "user", Type: &ast.TypeRef{Name: "User"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	appSrc := string(gr.Files["app.gen.go"])

	// Should have loaders field since there are relations
	if !strings.Contains(appSrc, "loaders Loaders") {
		t.Errorf("should have loaders field for models with relations:\n%s", appSrc)
	}
}

func TestGenerateFullWithHandlerAndDataloader(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "posts", Type: &ast.TypeRef{Name: "Post", IsList: true}},
				},
				Directives: []*ast.Directive{{Name: "crud"}},
			},
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
					{Name: "userId", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "user", Type: &ast.TypeRef{Name: "User"}},
				},
				Directives: []*ast.Directive{{Name: "crud"}},
			},
		},
		APIs: []*ast.ApiDecl{
			{
				Name:       "doCustom",
				Directives: []*ast.Directive{{Name: "native"}},
				ReturnType: &ast.TypeRef{Name: "String"},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)

	// Should generate all files
	if _, ok := gr.Files["handler.gen.go"]; !ok {
		t.Error("missing handler.gen.go")
	}
	if _, ok := gr.Files["dataloader.gen.go"]; !ok {
		t.Error("missing dataloader.gen.go")
	}
	if _, ok := gr.Files["native.gen.go"]; !ok {
		t.Error("missing native.gen.go")
	}
}

func TestGenerateModelFileWithExtend(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
		Extends: []*ast.ExtendDecl{
			{
				Name: "ExternalUser",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "email", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])

	if !strings.Contains(src, "type ExternalUser struct") {
		t.Errorf("should have extend stub struct:\n%s", src)
	}
	if !strings.Contains(src, "stub for the external ExternalUser model") {
		t.Errorf("should have stub comment:\n%s", src)
	}
}

func TestGenerateModelFileExtendSkipsExistingModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
				},
			},
		},
		Extends: []*ast.ExtendDecl{
			{
				Name: "User", // same name as an existing model
				Fields: []*ast.FieldDecl{
					{Name: "extra", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	src := string(gr.Files["model.gen.go"])

	// Should not generate a stub for User since it already exists as a model
	if strings.Contains(src, "stub for the external User model") {
		t.Errorf("should not generate stub for existing model:\n%s", src)
	}
}

func TestGenerateAppFileSingleModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen", DriverPG)
	appSrc := collapseSpaces(string(gr.Files["app.gen.go"]))

	if !strings.Contains(appSrc, "Post *PostClient") {
		t.Errorf("missing Post client:\n%s", appSrc)
	}
	// Should NOT contain other models
	if strings.Contains(appSrc, "User") {
		t.Errorf("should not contain User:\n%s", appSrc)
	}
}

func TestGenerateAppFileWithNativeAPIs(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		APIs: []*ast.ApiDecl{{
			Name:       "getStats",
			Directives: []*ast.Directive{{Name: "native"}},
			ReturnType: &ast.TypeRef{Name: "Int"},
		}},
	}

	gr := Generate(result(file), "gen", DriverPG)
	appSrc := string(gr.Files["app.gen.go"])

	if !strings.Contains(appSrc, "Resolver NativeResolver") {
		t.Errorf("App struct should have Resolver field:\n%s", appSrc)
	}
}

func TestGenerateAppFileWithoutNativeAPIs(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{{
			Name:   "User",
			Fields: []*ast.FieldDecl{{Name: "id", Type: &ast.TypeRef{Name: "Int"}}},
		}},
	}

	gr := Generate(result(file), "gen", DriverPG)
	appSrc := string(gr.Files["app.gen.go"])

	if strings.Contains(appSrc, "Resolver") {
		t.Errorf("App struct should NOT have Resolver field without native APIs:\n%s", appSrc)
	}
}

func TestGenerateWithSoftModelsParam(t *testing.T) {
	// Test Generate() with the optional softModels parameter
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "userId", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "user", Type: &ast.TypeRef{Name: "User"}},
				},
			},
		},
		Extends: []*ast.ExtendDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	// Pass softModels map (external soft model info)
	softModels := map[string]bool{"User": true}
	gr := Generate(result(file), "gen", DriverPG, softModels)

	// dataloader.gen.go should contain soft delete filter
	dlSrc := string(gr.Files["dataloader.gen.go"])
	if !strings.Contains(dlSrc, "deleted_at") {
		t.Errorf("soft model should add deleted_at filter in dataloader:\n%s", dlSrc)
	}
}

func TestIsSoftDeleteExported(t *testing.T) {
	soft := &ast.ModelDecl{Directives: []*ast.Directive{{Name: "soft"}}}
	if !IsSoftDelete(soft) {
		t.Error("IsSoftDelete should return true for @soft model")
	}
	notSoft := &ast.ModelDecl{}
	if IsSoftDelete(notSoft) {
		t.Error("IsSoftDelete should return false without @soft")
	}
}

// --- Lock ID functions ---

func TestSetAndGetModelFieldIDs(t *testing.T) {
	old := modelFieldIDs
	defer func() { modelFieldIDs = old }()

	SetModelFieldIDs(map[string]map[string]int{
		"User": {"id": 1, "name": 2},
	})
	if got := getModelFieldID("User", "id"); got != 1 {
		t.Fatalf("want 1, got %d", got)
	}
	if got := getModelFieldID("User", "name"); got != 2 {
		t.Fatalf("want 2, got %d", got)
	}
	if got := getModelFieldID("User", "missing"); got != 0 {
		t.Fatalf("want 0 for missing field, got %d", got)
	}
	if got := getModelFieldID("NoModel", "id"); got != 0 {
		t.Fatalf("want 0 for missing model, got %d", got)
	}
}

func TestSetAndGetEventFieldIDs(t *testing.T) {
	old := eventFieldIDs
	defer func() { eventFieldIDs = old }()

	SetEventFieldIDs(map[string]map[string]int{
		"OrderCreated": {"orderId": 1, "userId": 2},
	})
	if got := getEventFieldID("OrderCreated", "orderId"); got != 1 {
		t.Fatalf("want 1, got %d", got)
	}
	if got := getEventFieldID("OrderCreated", "missing"); got != 0 {
		t.Fatalf("want 0, got %d", got)
	}
	if got := getEventFieldID("NoEvent", "orderId"); got != 0 {
		t.Fatalf("want 0, got %d", got)
	}
}

func TestSetAndGetAPIIDs(t *testing.T) {
	old := apiIDs
	defer func() { apiIDs = old }()

	SetAPIIDs(map[string]int{"getUser": 1, "listUsers": 2})
	if got := getAPIID("getUser"); got != 1 {
		t.Fatalf("want 1, got %d", got)
	}
	if got := getAPIID("missing"); got != 0 {
		t.Fatalf("want 0, got %d", got)
	}
}

func TestSetAndGetAPIParamIDs(t *testing.T) {
	old := apiParamIDs
	defer func() { apiParamIDs = old }()

	SetAPIParamIDs(map[string]map[string]int{
		"getUser": {"id": 1},
	})
	got := getAPIParamIDs("getUser")
	if got == nil || got["id"] != 1 {
		t.Fatalf("want {id:1}, got %v", got)
	}
	if got := getAPIParamIDs("missing"); got != nil {
		t.Fatalf("want nil, got %v", got)
	}
}

func TestSetAPIParamTypes(t *testing.T) {
	old := apiParamTypes
	defer func() { apiParamTypes = old }()

	SetAPIParamTypes(map[string]map[string]string{
		"getUser": {"id": "Int"},
	})
	if apiParamTypes["getUser"]["id"] != "Int" {
		t.Fatal("SetAPIParamTypes not set correctly")
	}
}

func TestDriverImportAndPkg(t *testing.T) {
	tests := []struct {
		d          DBDriver
		wantPkg    string
		wantImport string
	}{
		{DriverPG, "pg", "github.com/light-speak/luxo/pkg/lux/pg"},
		{DriverMySQL, "mysql", "github.com/light-speak/luxo/pkg/lux/mysql"},
		{DriverSQLite, "sqlite", "github.com/light-speak/luxo/pkg/lux/sqlite"},
		{DriverMongo, "mongo", "github.com/light-speak/luxo/pkg/lux/mongo"},
	}
	for _, tt := range tests {
		if got := tt.d.DriverPkg(); got != tt.wantPkg {
			t.Errorf("%s.DriverPkg() = %q, want %q", tt.d, got, tt.wantPkg)
		}
		if got := tt.d.DriverImport(); got != tt.wantImport {
			t.Errorf("%s.DriverImport() = %q, want %q", tt.d, got, tt.wantImport)
		}
	}
}

// --- BuildSchemaJSON Tests ---

func TestBuildSchemaJSON(t *testing.T) {
	SetModelFieldIDs(map[string]map[string]int{
		"User": {"id": 1, "name": 2, "email": 3},
	})
	SetAPIIDs(map[string]int{"getUser": 7, "listUsers": 8})
	SetAPIParamIDs(map[string]map[string]int{
		"getUser": {"id": 1},
	})
	defer func() {
		SetModelFieldIDs(nil)
		SetAPIIDs(nil)
		SetAPIParamIDs(nil)
	}()

	r := result(
		&ast.File{
			Name: "origin/user.luxo",
			Models: []*ast.ModelDecl{{
				Name:       "User",
				Directives: []*ast.Directive{{Name: "crud"}},
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "email", Type: &ast.TypeRef{Name: "String"}},
				},
			}},
		},
	)

	data, err := BuildSchemaJSON(r, map[string]bool{})
	if err != nil {
		t.Fatal(err)
	}

	var schema map[string]any
	if err := json.Unmarshal(data, &schema); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}

	// Check models
	models := schema["models"].(map[string]any)
	user := models["User"].(map[string]any)
	fields := user["fields"].([]any)
	if len(fields) != 3 {
		t.Errorf("expected 3 fields, got %d", len(fields))
	}

	// Check field types are strings
	f0 := fields[0].(map[string]any)
	if f0["type"] != "Int" {
		t.Errorf("field type should be 'Int', got %v", f0["type"])
	}

	// Check APIs
	apis := schema["apis"].(map[string]any)
	if _, ok := apis["getUser"]; !ok {
		t.Error("missing getUser API")
	}
	if _, ok := apis["listUsers"]; !ok {
		t.Error("missing listUsers API")
	}

	// Check API has returnType
	getUser := apis["getUser"].(map[string]any)
	if getUser["returnType"] != "User" {
		t.Errorf("getUser returnType = %v, want User", getUser["returnType"])
	}
}

func TestBuildSchemaJSON_HiddenFieldsExcluded(t *testing.T) {
	SetModelFieldIDs(map[string]map[string]int{
		"User": {"id": 1, "name": 2, "password": 3},
	})
	defer SetModelFieldIDs(nil)

	r := result(
		&ast.File{
			Name: "origin/user.luxo",
			Models: []*ast.ModelDecl{{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "password", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "hidden"}}},
				},
			}},
		},
	)

	data, err := BuildSchemaJSON(r, map[string]bool{})
	if err != nil {
		t.Fatal(err)
	}

	if strings.Contains(string(data), "password") {
		t.Error("@hidden field should not appear in schema JSON")
	}
}

func TestBuildSchemaJSON_NoSvcAPIs(t *testing.T) {
	SetAPIIDs(map[string]int{"svc:getUserScore": 15})
	defer SetAPIIDs(nil)

	r := result(
		&ast.File{
			Name: "origin/user.luxo",
			Functions: []*ast.FnDecl{{
				Name:       "getUserScore",
				Directives: []*ast.Directive{{Name: "service"}},
				ReturnType: &ast.TypeRef{Name: "Float"},
			}},
		},
	)

	data, err := BuildSchemaJSON(r, map[string]bool{})
	if err != nil {
		t.Fatal(err)
	}

	// svc: APIs should NOT be in schema.json (internal only)
	// Actually BuildSchemaJSON currently includes them...
	// This test documents current behavior
	_ = data
}

func TestIsRelationType(t *testing.T) {
	// Primitive types → false
	for _, name := range []string{"Int", "Float", "String", "Boolean", "DateTime", "Duration", "UUID", "Decimal", "Bytes"} {
		if isRelationType(name) {
			t.Errorf("%s should not be relation type", name)
		}
	}
	// Model names → true
	for _, name := range []string{"User", "Post", "Team"} {
		if !isRelationType(name) {
			t.Errorf("%s should be relation type", name)
		}
	}
	// Empty/lowercase → false
	if isRelationType("") {
		t.Error("empty should not be relation")
	}
	if isRelationType("user") {
		t.Error("lowercase should not be relation")
	}
}

func TestWriteImports_Hash(t *testing.T) {
	var b strings.Builder
	files := []*ast.File{{
		Models: []*ast.ModelDecl{{
			Name: "User",
			Fields: []*ast.FieldDecl{
				{Name: "password", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "hash"}}},
			},
		}},
	}}
	writeImports(&b, files)
	if !strings.Contains(b.String(), "luxocrypto") {
		t.Errorf("@hash should import luxocrypto: %s", b.String())
	}
}

func TestWriteImports_NoHash(t *testing.T) {
	var b strings.Builder
	files := []*ast.File{{
		Models: []*ast.ModelDecl{{
			Name: "Post",
			Fields: []*ast.FieldDecl{
				{Name: "title", Type: &ast.TypeRef{Name: "String"}},
			},
		}},
	}}
	writeImports(&b, files)
	if strings.Contains(b.String(), "luxocrypto") {
		t.Errorf("no @hash should not import luxocrypto: %s", b.String())
	}
}

func TestGenerateModelFileWithTypes(t *testing.T) {
	r := buildResult(&ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{Name: "User", Fields: []*ast.FieldDecl{
				{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
				{Name: "name", Type: &ast.TypeRef{Name: "String"}},
			}},
		},
		Types: []*ast.TypeDecl{
			{Name: "AuthPayload", Fields: []*ast.FieldDecl{
				{Name: "user", Type: &ast.TypeRef{Name: "User"}},
				{Name: "token", Type: &ast.TypeRef{Name: "String"}},
			}},
		},
	})
	src := generateModelFile(r, "luxo", nil)
	code := string(src)
	if !strings.Contains(code, "type User struct") {
		t.Error("missing User struct")
	}
	if !strings.Contains(code, "type AuthPayload struct") {
		t.Error("missing AuthPayload struct")
	}
}

func TestWriteImportsWithAuth(t *testing.T) {
	files := []*ast.File{{
		Models: []*ast.ModelDecl{{
			Name:       "User",
			Fields:     []*ast.FieldDecl{{Name: "id", Type: &ast.TypeRef{Name: "Int"}}},
			Directives: []*ast.Directive{{Name: "withAuth"}},
		}},
	}}
	var b strings.Builder
	writeImports(&b, files)
	out := b.String()
	if !strings.Contains(out, "auth") {
		t.Errorf("@withAuth model should add auth import: %s", out)
	}
}

func TestExtendStubDedup(t *testing.T) {
	r := buildResult(
		&ast.File{
			Name:    "a.luxo",
			Extends: []*ast.ExtendDecl{{Name: "Project", Fields: []*ast.FieldDecl{{Name: "rules", Type: &ast.TypeRef{Name: "Rule", IsList: true}}}}},
		},
		&ast.File{
			Name:    "b.luxo",
			Extends: []*ast.ExtendDecl{{Name: "Project", Fields: []*ast.FieldDecl{{Name: "events", Type: &ast.TypeRef{Name: "Event", IsList: true}}}}},
		},
	)
	src := generateModelFile(r, "luxo", nil)
	code := string(src)
	if strings.Count(code, "type Project struct") > 1 {
		t.Error("Project struct should appear only once")
	}
}

func TestBuildEventContext(t *testing.T) {
	files := []*ast.File{
		{Name: "origin/common/events.luxo", Events: []*ast.EventDecl{{Name: "ProjectDeleted"}}},
		{Name: "origin/monitoring/trace.luxo", Events: []*ast.EventDecl{{Name: "TraceIngested"}}},
	}
	ctx := BuildEventContext(files, "github.com/test/service")
	if ctx.EventModule["ProjectDeleted"] != "common" {
		t.Errorf("ProjectDeleted module = %q", ctx.EventModule["ProjectDeleted"])
	}
	if ctx.EventModule["TraceIngested"] != "monitoring" {
		t.Errorf("TraceIngested module = %q", ctx.EventModule["TraceIngested"])
	}
	if ctx.ModulePath != "github.com/test/service" {
		t.Errorf("ModulePath = %q", ctx.ModulePath)
	}
}

func TestSetEventContext(t *testing.T) {
	old := globalEventCtx
	defer func() { globalEventCtx = old }()

	ctx := &EventContext{EventModule: map[string]string{"Test": "test"}, ModulePath: "test"}
	SetEventContext(ctx)
	if globalEventCtx != ctx {
		t.Error("SetEventContext should set global")
	}
}

func TestAppNeedsGeneration(t *testing.T) {
	// With models
	r := &semantic.Result{Files: []*ast.File{{Models: []*ast.ModelDecl{{Name: "User"}}}}}
	_, _, needed := appNeedsGeneration(r)
	if !needed {
		t.Error("should need generation with models")
	}

	// With native API
	r2 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{Name: "test", Directives: []*ast.Directive{{Name: "native"}}}}}}}
	_, _, needed2 := appNeedsGeneration(r2)
	if !needed2 {
		t.Error("should need generation with native API")
	}

	// With events
	r3 := &semantic.Result{Files: []*ast.File{{Events: []*ast.EventDecl{{Name: "Test"}}}}}
	_, _, needed3 := appNeedsGeneration(r3)
	if !needed3 {
		t.Error("should need generation with events")
	}

	// Empty
	r4 := &semantic.Result{Files: []*ast.File{{}}}
	_, _, needed4 := appNeedsGeneration(r4)
	if needed4 {
		t.Error("should not need generation when empty")
	}
}

func TestAppNeedsEvents(t *testing.T) {
	// With events
	r := &semantic.Result{Files: []*ast.File{{Events: []*ast.EventDecl{{Name: "Test"}}}}}
	if !appNeedsEvents(r) {
		t.Error("should need events with event declarations")
	}

	// With listeners
	r2 := &semantic.Result{Files: []*ast.File{{Listeners: []*ast.OnDecl{{EventName: "Test"}}}}}
	if !appNeedsEvents(r2) {
		t.Error("should need events with listeners")
	}

	// With emit
	r3 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{&ast.EmitStmt{EventName: "Test"}}},
	}}}}}
	if !appNeedsEvents(r3) {
		t.Error("should need events with emit statement")
	}

	// Nested emit inside if
	r4 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.IfStmt{
				Condition: &ast.Literal{Kind: token.Int, Value: "1"},
				Then: &ast.Block{Stmts: []ast.Stmt{
					&ast.EmitStmt{EventName: "Test"},
				}},
			},
		}},
	}}}}}
	if !appNeedsEvents(r4) {
		t.Error("should detect emit nested inside if")
	}

	// Nested emit inside transaction
	r5 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.ExprStmt{Expr: &ast.TransactionExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{
					&ast.EmitStmt{EventName: "Test"},
				}},
			}},
		}},
	}}}}}
	if !appNeedsEvents(r5) {
		t.Error("should detect emit nested inside transaction")
	}

	// Nested emit inside for
	r6 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.ForStmt{
				VarName:    "item",
				Collection: &ast.Ident{Name: "items"},
				Body: &ast.Block{Stmts: []ast.Stmt{
					&ast.EmitStmt{EventName: "Test"},
				}},
			},
		}},
	}}}}}
	if !appNeedsEvents(r6) {
		t.Error("should detect emit nested inside for")
	}

	// Nested emit inside async
	r7 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.ExprStmt{Expr: &ast.AsyncExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{
					&ast.EmitStmt{EventName: "Test"},
				}},
			}},
		}},
	}}}}}
	if !appNeedsEvents(r7) {
		t.Error("should detect emit nested inside async")
	}

	// Nested emit inside await
	r8 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.ExprStmt{Expr: &ast.AwaitExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{
					&ast.EmitStmt{EventName: "Test"},
				}},
			}},
		}},
	}}}}}
	if !appNeedsEvents(r8) {
		t.Error("should detect emit nested inside await")
	}

	// No emit (non-emit statements only)
	r9 := &semantic.Result{Files: []*ast.File{{APIs: []*ast.ApiDecl{{
		Name: "test",
		Body: &ast.Block{Stmts: []ast.Stmt{
			&ast.IfStmt{
				Condition: &ast.Literal{Kind: token.Int, Value: "1"},
				Then:      &ast.Block{Stmts: []ast.Stmt{&ast.ReturnStmt{}}},
			},
			&ast.ForStmt{
				VarName:    "x",
				Collection: &ast.Ident{Name: "xs"},
				Body:       &ast.Block{Stmts: []ast.Stmt{&ast.BreakStmt{}}},
			},
			&ast.ExprStmt{Expr: &ast.AsyncExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{&ast.ReturnStmt{}}},
			}},
			&ast.ExprStmt{Expr: &ast.AwaitExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{&ast.ReturnStmt{}}},
			}},
			&ast.ExprStmt{Expr: &ast.TransactionExpr{
				Body: &ast.Block{Stmts: []ast.Stmt{&ast.ReturnStmt{}}},
			}},
		}},
	}}}}}
	if appNeedsEvents(r9) {
		t.Error("should not need events without any emit")
	}

	// Empty
	r10 := &semantic.Result{Files: []*ast.File{{}}}
	if appNeedsEvents(r10) {
		t.Error("should not need events when empty")
	}
}
