package codegen

import (
	"strings"
	"testing"

	"github.com/light-speak/luxo/pkg/ast"
	"github.com/light-speak/luxo/pkg/semantic"
)

// buildResult creates a semantic.Result from manually constructed AST.
func buildResult(files ...*ast.File) *semantic.Result {
	return &semantic.Result{
		Files: files,
	}
}

func TestGenerateEmpty(t *testing.T) {
	result := buildResult(&ast.File{Name: "test.luxo"})
	gr := Generate(result, "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "package gen") {
		t.Errorf("missing package declaration:\n%s", src)
	}
	if !strings.Contains(src, "Code generated by luxo") {
		t.Errorf("missing header:\n%s", src)
	}
}

func TestGenerateEnumAndModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
					{Name: "email", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "unique"}}},
					{Name: "role", Type: &ast.TypeRef{Name: "Role"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])

	if !strings.Contains(src, "type Role string") {
		t.Errorf("missing enum type:\n%s", src)
	}
	if !strings.Contains(src, `RoleUSER`) {
		t.Errorf("missing enum constant:\n%s", src)
	}
	if !strings.Contains(src, "type User struct") {
		t.Errorf("missing struct:\n%s", src)
	}
	if !strings.Contains(src, `db:"email"`) {
		t.Errorf("missing db tag:\n%s", src)
	}
}

func result(files ...*ast.File) *semantic.Result {
	return buildResult(files...)
}

func TestGenerateWithTimeImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "createdAt", Type: &ast.TypeRef{Name: "DateTime"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"time"`) {
		t.Errorf("missing time import:\n%s", src)
	}
}

func TestGenerateNoTimeImportWhenNotNeeded(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Config",
				Fields: []*ast.FieldDecl{
					{Name: "key", Type: &ast.TypeRef{Name: "String"}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if strings.Contains(src, `"time"`) {
		t.Errorf("unexpected time import:\n%s", src)
	}
}

func TestGenerateDBFile(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, "UserClient") {
		t.Errorf("missing UserClient in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "pg.Query[User]") {
		t.Errorf("missing pg.Query[User] in db.gen.go:\n%s", dbSrc)
	}
}

func TestGenerateNoDBFileWhenNoModels(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
	}

	gr := Generate(result(file), "gen")
	if _, ok := gr.Files["db.gen.go"]; ok {
		t.Errorf("db.gen.go should not be generated when no models exist")
	}
}

func TestGenerateWithDurationImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Task",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "timeout", Type: &ast.TypeRef{Name: "Duration"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"time"`) {
		t.Errorf("missing time import for Duration:\n%s", src)
	}
}

func TestGenerateComputedDateTimeNoTimeImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "lastActivity", Type: &ast.TypeRef{Name: "DateTime"}, Computed: &ast.ComputedField{}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if strings.Contains(src, `"time"`) {
		t.Errorf("computed DateTime should not trigger time import:\n%s", src)
	}
}

func TestGenerateWithUUIDImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Token",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"github.com/google/uuid"`) {
		t.Errorf("missing uuid import:\n%s", src)
	}
}

func TestGenerateWithDecimalImport(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Product",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "price", Type: &ast.TypeRef{Name: "Decimal"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `"github.com/shopspring/decimal"`) {
		t.Errorf("missing decimal import:\n%s", src)
	}
}

func TestGenerateWithBytesType(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Doc",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "data", Type: &ast.TypeRef{Name: "Bytes"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "[]byte") {
		t.Errorf("missing []byte type:\n%s", src)
	}
}

func TestGenerateAutoUUIDDBImports(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Token",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}, Directives: []*ast.Directive{{Name: "auto"}}},
					{Name: "value", Type: &ast.TypeRef{Name: "String"}},
					{Name: "createdAt", Type: &ast.TypeRef{Name: "DateTime"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, `"github.com/google/uuid"`) {
		t.Errorf("missing uuid import in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, `"time"`) {
		t.Errorf("missing time import in db.gen.go:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "uuid.Must(uuid.NewV7())") {
		t.Errorf("missing uuid auto-fill:\n%s", dbSrc)
	}
}

func TestGenerateNilTypeField(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Test",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "unknown", Type: nil},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, "any") {
		t.Errorf("nil type should map to any:\n%s", src)
	}
}

func TestGenerateHiddenFieldJsonTag(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "password", Type: &ast.TypeRef{Name: "String"}, Directives: []*ast.Directive{{Name: "hidden"}}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	src := string(gr.Files["model.gen.go"])
	if !strings.Contains(src, `json:"-"`) {
		t.Errorf("@hidden should generate json:\"-\":\n%s", src)
	}
}

func TestGenerateUUIDPrimaryKeyFind(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "UUID"}, Directives: []*ast.Directive{{Name: "auto"}}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	dbSrc := string(gr.Files["db.gen.go"])
	if !strings.Contains(dbSrc, "Find(ctx context.Context, id uuid.UUID)") {
		t.Errorf("Find should use uuid.UUID for UUID pk:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "pg.UpdateBase[User, uuid.UUID]") {
		t.Errorf("UpdateBase should use uuid.UUID as ID type:\n%s", dbSrc)
	}
}

func TestGenerateSoftDeleteModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
				},
				Directives: []*ast.Directive{{Name: "soft"}},
			},
		},
	}

	gr := Generate(result(file), "gen")
	modelSrc := string(gr.Files["model.gen.go"])
	dbSrc := string(gr.Files["db.gen.go"])

	// model.gen.go should have deletedAt field and time import
	if !strings.Contains(modelSrc, "DeletedAt") {
		t.Errorf("missing DeletedAt field in model:\n%s", modelSrc)
	}
	if !strings.Contains(modelSrc, "*time.Time") {
		t.Errorf("missing *time.Time for deletedAt:\n%s", modelSrc)
	}
	if !strings.Contains(modelSrc, `"time"`) {
		t.Errorf("missing time import for @soft model:\n%s", modelSrc)
	}

	// db.gen.go should have soft delete methods
	if !strings.Contains(dbSrc, "SoftDelete") {
		t.Errorf("missing SoftDelete in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "ForceDelete") {
		t.Errorf("missing ForceDelete in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "WithDeleted") {
		t.Errorf("missing WithDeleted in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, "Restore") {
		t.Errorf("missing Restore in db:\n%s", dbSrc)
	}
	if !strings.Contains(dbSrc, `"time"`) {
		t.Errorf("missing time import in db for @soft:\n%s", dbSrc)
	}
}

func TestGenerateSoftDeleteWithExistingDeletedAt(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "title", Type: &ast.TypeRef{Name: "String"}},
					{Name: "deletedAt", Type: &ast.TypeRef{Name: "DateTime", Nullable: true}},
				},
				Directives: []*ast.Directive{{Name: "soft"}},
			},
		},
	}

	gr := Generate(result(file), "gen")
	modelSrc := string(gr.Files["model.gen.go"])

	// Should not duplicate deletedAt
	count := strings.Count(modelSrc, "DeletedAt")
	if count != 1 {
		t.Errorf("DeletedAt should appear exactly once, got %d:\n%s", count, modelSrc)
	}
}

func TestGenerateAppFile(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "User",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "name", Type: &ast.TypeRef{Name: "String"}},
				},
			},
			{
				Name: "Order",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
					{Name: "total", Type: &ast.TypeRef{Name: "Float"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	appSrc := string(gr.Files["app.gen.go"])

	checks := []string{
		"package gen",
		"type App struct",
		"DB *pg.DB",
		"User *UserClient",
		"Order *OrderClient",
		"func New(ctx context.Context) (*App, error)",
		`env.Get("DATABASE_URL")`,
		"pg.NewDB(ctx, url)",
		"func NewFromDB(db *pg.DB) *App",
		"&UserClient{db: db}",
		"&OrderClient{db: db}",
		"func (a *App) Close()",
		"func (a *App) Tx(ctx context.Context, fn func(tx *App) error) error",
		"NewFromDB(txDB)",
	}
	for _, check := range checks {
		if !strings.Contains(appSrc, check) {
			t.Errorf("missing %q in app.gen.go:\n%s", check, appSrc)
		}
	}
}

func TestGenerateAppFileNoModels(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Enums: []*ast.EnumDecl{
			{Name: "Role", Values: []string{"USER", "ADMIN"}},
		},
	}

	gr := Generate(result(file), "gen")
	if _, ok := gr.Files["app.gen.go"]; ok {
		t.Error("app.gen.go should not be generated when no models exist")
	}
}

func TestGenerateAppFileSingleModel(t *testing.T) {
	file := &ast.File{
		Name: "test.luxo",
		Models: []*ast.ModelDecl{
			{
				Name: "Post",
				Fields: []*ast.FieldDecl{
					{Name: "id", Type: &ast.TypeRef{Name: "Int"}},
				},
			},
		},
	}

	gr := Generate(result(file), "gen")
	appSrc := string(gr.Files["app.gen.go"])

	if !strings.Contains(appSrc, "Post *PostClient") {
		t.Errorf("missing Post client:\n%s", appSrc)
	}
	// Should NOT contain other models
	if strings.Contains(appSrc, "User") {
		t.Errorf("should not contain User:\n%s", appSrc)
	}
}
