package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/ast"
	"github.com/light-speak/luxo/pkg/semantic"
)

// GenerateResult holds all generated Go source files.
type GenerateResult struct {
	Files map[string][]byte // filename → Go source
}

// Generate produces Go source files from semantic analysis result.
func Generate(result *semantic.Result, packageName string) *GenerateResult {
	gr := &GenerateResult{
		Files: make(map[string][]byte),
	}

	// model.gen.go — enums + model structs
	gr.Files["model.gen.go"] = generateModelFile(result, packageName)

	// db.gen.go — query builders (Client, Query, Where, Create, Update)
	if dbSrc := generateDBFile(result, packageName); dbSrc != nil {
		gr.Files["db.gen.go"] = dbSrc
	}

	return gr
}

// generateModelFile produces the model.gen.go file containing enums and structs.
func generateModelFile(result *semantic.Result, packageName string) []byte {
	var b strings.Builder

	writeHeader(&b, packageName, "model.gen.go")
	writeImports(&b, result.Files)

	// enums first (structs may reference them)
	for _, file := range result.Files {
		for _, e := range file.Enums {
			generateEnum(&b, e)
			b.WriteByte('\n')
		}
	}

	// model structs
	for _, file := range result.Files {
		for _, m := range file.Models {
			generateModel(&b, m)
			b.WriteByte('\n')
		}
	}

	return []byte(b.String())
}

func writeHeader(b *strings.Builder, packageName, sourceFile string) {
	fmt.Fprintf(b, "// Code generated by luxo. DO NOT EDIT.\n")
	fmt.Fprintf(b, "// Source: %s\n\n", sourceFile)
	fmt.Fprintf(b, "package %s\n\n", packageName)
}

// writeImports writes import block for model.gen.go.
func writeImports(b *strings.Builder, files []*ast.File) {
	needsTime := false
	needsUUID := false
	needsDecimal := false

	for _, file := range files {
		for _, m := range file.Models {
			for _, f := range m.Fields {
				if f.Computed != nil || f.Type == nil {
					continue
				}
				switch f.Type.Name {
				case "DateTime", "Duration":
					needsTime = true
				case "UUID":
					needsUUID = true
				case "Decimal":
					needsDecimal = true
				}
			}
		}
	}

	if !needsTime && !needsUUID && !needsDecimal {
		return
	}

	b.WriteString("import (\n")
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	if needsUUID {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if needsDecimal {
		b.WriteString("\t\"github.com/shopspring/decimal\"\n")
	}
	b.WriteString(")\n\n")
}

// generateDBFile produces the db.gen.go file containing query builders.
// Returns nil if there are no models.
func generateDBFile(result *semantic.Result, packageName string) []byte {
	hasModels := false
	for _, file := range result.Files {
		if len(file.Models) > 0 {
			hasModels = true
			break
		}
	}
	if !hasModels {
		return nil
	}

	var b strings.Builder

	writeHeader(&b, packageName, "db.gen.go")
	writeDBImports(&b, result.Files)

	for _, file := range result.Files {
		for _, m := range file.Models {
			generateQueryBuilder(&b, m)
			b.WriteByte('\n')
		}
	}

	return []byte(b.String())
}

// dbImportNeeds tracks which imports db.gen.go requires.
type dbImportNeeds struct {
	time    bool
	uuid    bool
	decimal bool
}

// scanDBFieldImports checks a single field for import needs in db.gen.go.
func scanDBFieldImports(f *ast.FieldDecl, needs *dbImportNeeds) {
	if f.Computed != nil || f.Type == nil {
		return
	}
	// Auto-fill needs
	if f.Type.Name == "DateTime" && (f.Name == "createdAt" || f.Name == "updatedAt") {
		needs.time = true
	}
	if hasDirective(f.Directives, "auto") && f.Type.Name == "UUID" {
		needs.uuid = true
	}
	// CreateInput struct field types
	if hasDirective(f.Directives, "internal") || isAutoManaged(f) {
		return
	}
	switch f.Type.Name {
	case "DateTime", "Duration":
		needs.time = true
	case "UUID":
		needs.uuid = true
	case "Decimal":
		needs.decimal = true
	}
}

// writeDBImports writes import block for db.gen.go.
func writeDBImports(b *strings.Builder, files []*ast.File) {
	var needs dbImportNeeds
	for _, file := range files {
		for _, m := range file.Models {
			for _, f := range m.Fields {
				scanDBFieldImports(f, &needs)
			}
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	if needs.time {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n\t\"github.com/light-speak/luxo/pkg/lux\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/pg\"\n")
	if needs.uuid {
		b.WriteString("\n\t\"github.com/google/uuid\"\n")
	}
	if needs.decimal {
		b.WriteString("\t\"github.com/shopspring/decimal\"\n")
	}
	b.WriteString(")\n\n")
}
