package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/semantic"
)

// DeployFiles holds generated deployment configuration files.
type DeployFiles struct {
	Dockerfile    []byte
	DockerCompose []byte
}

// GenerateDeployFiles produces Dockerfile, docker-compose.yml, and init-db.sh
// from the semantic result. Auto-detects modules, dependencies, and infra needs.
func GenerateDeployFiles(result *semantic.Result, projectName string) *DeployFiles {
	modules := collectModules(result)
	if len(modules) == 0 {
		return nil
	}

	// Detect infra needs
	hasEvents := false
	for _, m := range modules {
		if m.hasEvents {
			hasEvents = true
		}
	}

	return &DeployFiles{
		Dockerfile:    generateDockerfile(modules),
		DockerCompose: generateDockerCompose(modules, projectName, hasEvents),
	}
}

func generateDockerfile(modules []moduleInfo) []byte {
	var b strings.Builder

	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("FROM golang:1.26-alpine AS builder\n")
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY go.mod go.sum ./\n")
	b.WriteString("RUN go mod download\n")
	b.WriteString("COPY . .\n\n")

	// Per-module build stages
	for _, m := range modules {
		fmt.Fprintf(&b, "FROM builder AS %s\n", m.name)
		fmt.Fprintf(&b, "RUN CGO_ENABLED=0 go build -o /service ./luxis/%s/\n\n", m.name)
	}

	// Gateway build
	b.WriteString("FROM builder AS gateway\n")
	b.WriteString("RUN CGO_ENABLED=0 go build -o /service ./luxis/gateway/\n\n")

	// Runtime images — include migrations for auto-migrate on startup
	for _, m := range modules {
		fmt.Fprintf(&b, "FROM alpine:3.20 AS %s-run\n", m.name)
		fmt.Fprintf(&b, "WORKDIR /app\n")
		fmt.Fprintf(&b, "COPY --from=%s /service /usr/local/bin/service\n", m.name)
		fmt.Fprintf(&b, "COPY --from=builder /app/migrations/ /app/migrations/\n")
		fmt.Fprintf(&b, "ENTRYPOINT [\"service\"]\n\n")
	}

	b.WriteString("FROM alpine:3.20 AS gateway-run\n")
	b.WriteString("COPY --from=gateway /service /usr/local/bin/service\n")
	b.WriteString("ENTRYPOINT [\"service\"]\n")

	return []byte(b.String())
}

func generateDockerCompose(modules []moduleInfo, projectName string, hasEvents bool) []byte {
	var b strings.Builder

	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("services:\n")

	// --- Infra ---
	b.WriteString("  postgres:\n")
	b.WriteString("    image: postgres:17-alpine\n")
	fmt.Fprintf(&b, "    container_name: %s-pg\n", projectName)
	b.WriteString("    restart: always\n")
	b.WriteString("    environment:\n")
	b.WriteString("      POSTGRES_USER: ${DATABASE_USER:-postgres}\n")
	b.WriteString("      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - pgdata:/var/lib/postgresql/data\n")
	b.WriteString("    healthcheck:\n")
	b.WriteString("      test: [\"CMD-SHELL\", \"pg_isready -U ${DATABASE_USER:-postgres}\"]\n")
	b.WriteString("      interval: 5s\n")
	b.WriteString("      timeout: 3s\n")
	b.WriteString("      retries: 5\n\n")

	if hasEvents {
		b.WriteString("  nats:\n")
		b.WriteString("    image: nats:2-alpine\n")
		fmt.Fprintf(&b, "    container_name: %s-nats\n", projectName)
		b.WriteString("    restart: always\n\n")
	}

	b.WriteString("  redis:\n")
	b.WriteString("    image: redis:7-alpine\n")
	fmt.Fprintf(&b, "    container_name: %s-redis\n", projectName)
	b.WriteString("    restart: always\n\n")

	// --- App services ---
	for _, m := range modules {
		fmt.Fprintf(&b, "  %s:\n", m.name)
		fmt.Fprintf(&b, "    build: { context: ., target: %s-run }\n", m.name)
		b.WriteString("    restart: always\n")
		b.WriteString("    environment:\n")
		b.WriteString("      DATABASE_DRIVER: pg\n")
		b.WriteString("      DATABASE_HOST: postgres\n")
		b.WriteString("      DATABASE_PORT: \"5432\"\n")
		b.WriteString("      DATABASE_USER: ${DATABASE_USER:-postgres}\n")
		b.WriteString("      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}\n")
		fmt.Fprintf(&b, "      DATABASE_PREFIX: %s\n", projectName)
		b.WriteString("      APP_PORT: \"4000\"\n")
		b.WriteString("      LUXO_PORT: \"9000\"\n")
		if hasEvents {
			b.WriteString("      NATS_URL: nats://nats:4222\n")
		}
		b.WriteString("    depends_on:\n")
		b.WriteString("      postgres: { condition: service_healthy }\n")
		b.WriteString("\n")
	}

	// --- Gateway ---
	b.WriteString("  gateway:\n")
	b.WriteString("    build: { context: ., target: gateway-run }\n")
	b.WriteString("    restart: always\n")
	b.WriteString("    ports:\n")
	b.WriteString("      - \"${GATEWAY_PORT:-4000}:4000\"\n")
	b.WriteString("    environment:\n")
	b.WriteString("      APP_PORT: \"4000\"\n")
	b.WriteString("      CORS_ORIGIN: \"${CORS_ORIGIN:-*}\"\n")
	b.WriteString("    depends_on:\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "      %s: { condition: service_started }\n", m.name)
	}
	b.WriteString("\n")

	// --- Volumes ---
	b.WriteString("volumes:\n")
	b.WriteString("  pgdata:\n")

	return []byte(b.String())
}
