package codegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/light-speak/luxo/pkg/semantic"
)

// invalidChartChars matches any character that is not lowercase alphanumeric or hyphen.
var invalidChartChars = regexp.MustCompile(`[^a-z0-9-]`)

// normalizeChartName converts a project name into a valid Helm chart name.
// Chart names must be lowercase RFC 1123 labels: [a-z0-9-], max 53 chars.
func normalizeChartName(name string) string {
	name = strings.ToLower(name)
	name = invalidChartChars.ReplaceAllString(name, "-")
	// Collapse consecutive hyphens
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}
	name = strings.Trim(name, "-")
	if len(name) > 53 {
		name = name[:53]
		name = strings.TrimRight(name, "-")
	}
	if name == "" {
		name = "luxo-app"
	}
	return name
}

// HelmFiles holds generated Helm chart files.
// Keys are relative paths from the chart root (e.g. "Chart.yaml", "templates/gateway-deployment.yaml").
type HelmFiles struct {
	Files map[string][]byte
}

// GenerateHelmFiles produces a complete Helm chart from the semantic result.
// Chart structure:
//
//	deploy/helm/
//	├── Chart.yaml
//	├── values.yaml
//	├── .helmignore
//	└── templates/
//	    ├── _helpers.tpl
//	    ├── configmap.yaml
//	    ├── secret.yaml
//	    ├── serviceaccount.yaml
//	    ├── gateway-deployment.yaml
//	    ├── gateway-service.yaml
//	    ├── ingress.yaml
//	    ├── hpa.yaml
//	    └── module-{name}-deployment.yaml / module-{name}-service.yaml (per module)
func GenerateHelmFiles(result *semantic.Result, projectName string) *HelmFiles {
	modules := collectModules(result)
	if len(modules) == 0 {
		return nil
	}

	projectName = normalizeChartName(projectName)

	hasEvents := false
	for _, m := range modules {
		if m.hasEvents {
			hasEvents = true
		}
	}

	files := make(map[string][]byte)
	files["Chart.yaml"] = generateChartYAML(projectName)
	files["values.yaml"] = generateValuesYAML(modules, projectName, hasEvents)
	files[".helmignore"] = generateHelmIgnore()
	files["templates/_helpers.tpl"] = generateHelpers(projectName)
	files["templates/configmap.yaml"] = generateConfigMap(modules, hasEvents)
	files["templates/secret.yaml"] = generateSecret()
	files["templates/serviceaccount.yaml"] = generateServiceAccount()
	files["templates/gateway-deployment.yaml"] = generateGatewayDeployment()
	files["templates/gateway-service.yaml"] = generateGatewayService()
	files["templates/ingress.yaml"] = generateIngress()
	files["templates/hpa.yaml"] = generateHPA(modules)

	for _, m := range modules {
		files[fmt.Sprintf("templates/module-%s-deployment.yaml", m.name)] = generateModuleDeployment(m)
		files[fmt.Sprintf("templates/module-%s-service.yaml", m.name)] = generateModuleService(m)
	}

	return &HelmFiles{Files: files}
}

func generateChartYAML(projectName string) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: v2\n")
	fmt.Fprintf(&b, "name: %s\n", projectName)
	fmt.Fprintf(&b, "description: Helm chart for %s (generated by Luxo)\n", projectName)
	b.WriteString("type: application\n")
	b.WriteString("version: 0.1.0\n")
	b.WriteString("appVersion: \"1.0.0\"\n")
	return []byte(b.String())
}

func generateValuesYAML(modules []moduleInfo, projectName string, hasEvents bool) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n\n")

	// Global
	b.WriteString("global:\n")
	fmt.Fprintf(&b, "  projectName: %s\n\n", projectName)

	// Image defaults
	b.WriteString("image:\n")
	fmt.Fprintf(&b, "  repository: %s\n", projectName)
	b.WriteString("  tag: latest\n")
	b.WriteString("  pullPolicy: IfNotPresent\n\n")

	// Service account
	b.WriteString("serviceAccount:\n")
	b.WriteString("  create: true\n")
	b.WriteString("  name: \"\"\n\n")

	// Gateway
	b.WriteString("gateway:\n")
	b.WriteString("  replicas: 2\n")
	b.WriteString("  port: 4000\n")
	b.WriteString("  service:\n")
	b.WriteString("    type: ClusterIP\n")
	b.WriteString("    port: 4000\n")
	b.WriteString("  resources:\n")
	b.WriteString("    requests:\n")
	b.WriteString("      cpu: 100m\n")
	b.WriteString("      memory: 128Mi\n")
	b.WriteString("    limits:\n")
	b.WriteString("      cpu: 500m\n")
	b.WriteString("      memory: 256Mi\n")
	b.WriteString("  env:\n")
	b.WriteString("    CORS_ORIGIN: \"*\"\n")
	b.WriteString("  autoscaling:\n")
	b.WriteString("    enabled: false\n")
	b.WriteString("    minReplicas: 2\n")
	b.WriteString("    maxReplicas: 10\n")
	b.WriteString("    targetCPUUtilizationPercentage: 80\n\n")

	// Modules
	b.WriteString("modules:\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "  %s:\n", m.name)
		b.WriteString("    replicas: 2\n")
		b.WriteString("    port: 4000\n")
		b.WriteString("    rpcPort: 9000\n")
		b.WriteString("    resources:\n")
		b.WriteString("      requests:\n")
		b.WriteString("        cpu: 100m\n")
		b.WriteString("        memory: 128Mi\n")
		b.WriteString("      limits:\n")
		b.WriteString("        cpu: 500m\n")
		b.WriteString("        memory: 512Mi\n")
		b.WriteString("    autoscaling:\n")
		b.WriteString("      enabled: false\n")
		b.WriteString("      minReplicas: 2\n")
		b.WriteString("      maxReplicas: 10\n")
		b.WriteString("      targetCPUUtilizationPercentage: 80\n")
	}
	b.WriteString("\n")

	// Database
	b.WriteString("database:\n")
	b.WriteString("  driver: pg\n")
	b.WriteString("  host: postgres\n")
	b.WriteString("  port: \"5432\"\n")
	b.WriteString("  user: luxo\n")
	b.WriteString("  password: luxo\n")
	fmt.Fprintf(&b, "  prefix: %s\n\n", projectName)

	// Redis
	b.WriteString("redis:\n")
	b.WriteString("  host: redis\n")
	b.WriteString("  port: \"6379\"\n\n")

	// NATS (only if events exist)
	if hasEvents {
		b.WriteString("nats:\n")
		b.WriteString("  url: nats://nats:4222\n\n")
	}

	// Ingress
	b.WriteString("ingress:\n")
	b.WriteString("  enabled: false\n")
	b.WriteString("  className: \"\"\n")
	b.WriteString("  annotations: {}\n")
	b.WriteString("  hosts:\n")
	fmt.Fprintf(&b, "    - host: %s.local\n", projectName)
	b.WriteString("      paths:\n")
	b.WriteString("        - path: /\n")
	b.WriteString("          pathType: Prefix\n")
	b.WriteString("  tls: []\n")

	return []byte(b.String())
}

func generateHelmIgnore() []byte {
	return []byte(`# Auto-generated by luxo. DO NOT EDIT.
.DS_Store
.git
.gitignore
*.swp
*.bak
*.tmp
`)
}

func generateHelpers(projectName string) []byte {
	var b strings.Builder
	b.WriteString("{{/* Auto-generated by luxo. DO NOT EDIT. */}}\n\n")

	// Chart name
	b.WriteString("{{- define \"luxo.name\" -}}\n")
	b.WriteString("{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix \"-\" }}\n")
	b.WriteString("{{- end }}\n\n")

	// Fullname
	b.WriteString("{{- define \"luxo.fullname\" -}}\n")
	b.WriteString("{{- if .Values.fullnameOverride }}\n")
	b.WriteString("{{- .Values.fullnameOverride | trunc 63 | trimSuffix \"-\" }}\n")
	b.WriteString("{{- else }}\n")
	b.WriteString("{{- $name := default .Chart.Name .Values.nameOverride }}\n")
	b.WriteString("{{- if contains $name .Release.Name }}\n")
	b.WriteString("{{- .Release.Name | trunc 63 | trimSuffix \"-\" }}\n")
	b.WriteString("{{- else }}\n")
	b.WriteString("{{- printf \"%s-%s\" .Release.Name $name | trunc 63 | trimSuffix \"-\" }}\n")
	b.WriteString("{{- end }}\n")
	b.WriteString("{{- end }}\n")
	b.WriteString("{{- end }}\n\n")

	// Chart label
	b.WriteString("{{- define \"luxo.chart\" -}}\n")
	b.WriteString("{{- printf \"%s-%s\" .Chart.Name .Chart.Version | replace \"+\" \"_\" | trunc 63 | trimSuffix \"-\" }}\n")
	b.WriteString("{{- end }}\n\n")

	// Common labels
	b.WriteString("{{- define \"luxo.labels\" -}}\n")
	b.WriteString("helm.sh/chart: {{ include \"luxo.chart\" . }}\n")
	b.WriteString("{{ include \"luxo.selectorLabels\" . }}\n")
	b.WriteString("app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}\n")
	b.WriteString("app.kubernetes.io/managed-by: {{ .Release.Service }}\n")
	b.WriteString("{{- end }}\n\n")

	// Selector labels
	b.WriteString("{{- define \"luxo.selectorLabels\" -}}\n")
	b.WriteString("app.kubernetes.io/name: {{ include \"luxo.name\" . }}\n")
	b.WriteString("app.kubernetes.io/instance: {{ .Release.Name }}\n")
	b.WriteString("{{- end }}\n\n")

	// Service account name
	b.WriteString("{{- define \"luxo.serviceAccountName\" -}}\n")
	b.WriteString("{{- if .Values.serviceAccount.create }}\n")
	b.WriteString("{{- default (include \"luxo.fullname\" .) .Values.serviceAccount.name }}\n")
	b.WriteString("{{- else }}\n")
	b.WriteString("{{- default \"default\" .Values.serviceAccount.name }}\n")
	b.WriteString("{{- end }}\n")
	b.WriteString("{{- end }}\n")

	return []byte(b.String())
}

func generateConfigMap(modules []moduleInfo, hasEvents bool) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: ConfigMap\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}-config\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("data:\n")
	b.WriteString("  DATABASE_DRIVER: {{ .Values.database.driver | quote }}\n")
	b.WriteString("  DATABASE_HOST: {{ .Values.database.host | quote }}\n")
	b.WriteString("  DATABASE_PORT: {{ .Values.database.port | quote }}\n")
	b.WriteString("  DATABASE_PREFIX: {{ .Values.database.prefix | quote }}\n")
	b.WriteString("  REDIS_HOST: {{ .Values.redis.host | quote }}\n")
	b.WriteString("  REDIS_PORT: {{ .Values.redis.port | quote }}\n")

	if hasEvents {
		b.WriteString("  NATS_URL: {{ .Values.nats.url | quote }}\n")
	}

	// Module service discovery addresses
	for _, m := range modules {
		envKey := strings.ToUpper(m.name) + "_SERVICE_ADDR"
		// Kubernetes DNS: <service-name>.<namespace>.svc.cluster.local:port
		fmt.Fprintf(&b, "  %s: {{ include \"luxo.fullname\" . }}-%s:{{ .Values.modules.%s.rpcPort }}\n", envKey, m.name, m.name)
	}

	return []byte(b.String())
}

func generateSecret() []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: Secret\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}-secret\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("type: Opaque\n")
	b.WriteString("data:\n")
	b.WriteString("  DATABASE_USER: {{ .Values.database.user | b64enc | quote }}\n")
	b.WriteString("  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}\n")

	return []byte(b.String())
}

func generateServiceAccount() []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("{{- if .Values.serviceAccount.create -}}\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: ServiceAccount\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.serviceAccountName\" . }}\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("{{- end }}\n")

	return []byte(b.String())
}

func generateGatewayDeployment() []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: apps/v1\n")
	b.WriteString("kind: Deployment\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}-gateway\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("    app.kubernetes.io/component: gateway\n")
	b.WriteString("spec:\n")
	b.WriteString("  replicas: {{ .Values.gateway.replicas }}\n")
	b.WriteString("  selector:\n")
	b.WriteString("    matchLabels:\n")
	b.WriteString("      {{- include \"luxo.selectorLabels\" . | nindent 6 }}\n")
	b.WriteString("      app.kubernetes.io/component: gateway\n")
	b.WriteString("  template:\n")
	b.WriteString("    metadata:\n")
	b.WriteString("      labels:\n")
	b.WriteString("        {{- include \"luxo.selectorLabels\" . | nindent 8 }}\n")
	b.WriteString("        app.kubernetes.io/component: gateway\n")
	b.WriteString("    spec:\n")
	b.WriteString("      serviceAccountName: {{ include \"luxo.serviceAccountName\" . }}\n")
	b.WriteString("      containers:\n")
	b.WriteString("        - name: gateway\n")
	b.WriteString("          image: \"{{ .Values.image.repository }}/gateway:{{ .Values.image.tag }}\"\n")
	b.WriteString("          imagePullPolicy: {{ .Values.image.pullPolicy }}\n")
	b.WriteString("          ports:\n")
	b.WriteString("            - name: http\n")
	b.WriteString("              containerPort: {{ .Values.gateway.port }}\n")
	b.WriteString("              protocol: TCP\n")
	b.WriteString("          env:\n")
	b.WriteString("            - name: APP_PORT\n")
	b.WriteString("              value: {{ .Values.gateway.port | quote }}\n")
	b.WriteString("            - name: CORS_ORIGIN\n")
	b.WriteString("              value: {{ .Values.gateway.env.CORS_ORIGIN | quote }}\n")
	b.WriteString("          envFrom:\n")
	b.WriteString("            - configMapRef:\n")
	b.WriteString("                name: {{ include \"luxo.fullname\" . }}-config\n")
	b.WriteString("            - secretRef:\n")
	b.WriteString("                name: {{ include \"luxo.fullname\" . }}-secret\n")
	b.WriteString("          livenessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /health\n")
	b.WriteString("              port: http\n")
	b.WriteString("            initialDelaySeconds: 5\n")
	b.WriteString("            periodSeconds: 10\n")
	b.WriteString("          readinessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /health\n")
	b.WriteString("              port: http\n")
	b.WriteString("            initialDelaySeconds: 3\n")
	b.WriteString("            periodSeconds: 5\n")
	b.WriteString("          resources:\n")
	b.WriteString("            {{- toYaml .Values.gateway.resources | nindent 12 }}\n")

	return []byte(b.String())
}

func generateGatewayService() []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: Service\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}-gateway\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("    app.kubernetes.io/component: gateway\n")
	b.WriteString("spec:\n")
	b.WriteString("  type: {{ .Values.gateway.service.type }}\n")
	b.WriteString("  ports:\n")
	b.WriteString("    - port: {{ .Values.gateway.service.port }}\n")
	b.WriteString("      targetPort: http\n")
	b.WriteString("      protocol: TCP\n")
	b.WriteString("      name: http\n")
	b.WriteString("  selector:\n")
	b.WriteString("    {{- include \"luxo.selectorLabels\" . | nindent 4 }}\n")
	b.WriteString("    app.kubernetes.io/component: gateway\n")

	return []byte(b.String())
}

func generateIngress() []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("{{- if .Values.ingress.enabled -}}\n")
	b.WriteString("apiVersion: networking.k8s.io/v1\n")
	b.WriteString("kind: Ingress\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("  {{- with .Values.ingress.annotations }}\n")
	b.WriteString("  annotations:\n")
	b.WriteString("    {{- toYaml . | nindent 4 }}\n")
	b.WriteString("  {{- end }}\n")
	b.WriteString("spec:\n")
	b.WriteString("  {{- if .Values.ingress.className }}\n")
	b.WriteString("  ingressClassName: {{ .Values.ingress.className }}\n")
	b.WriteString("  {{- end }}\n")
	b.WriteString("  {{- if .Values.ingress.tls }}\n")
	b.WriteString("  tls:\n")
	b.WriteString("    {{- toYaml .Values.ingress.tls | nindent 4 }}\n")
	b.WriteString("  {{- end }}\n")
	b.WriteString("  rules:\n")
	b.WriteString("    {{- range .Values.ingress.hosts }}\n")
	b.WriteString("    - host: {{ .host | quote }}\n")
	b.WriteString("      http:\n")
	b.WriteString("        paths:\n")
	b.WriteString("          {{- range .paths }}\n")
	b.WriteString("          - path: {{ .path }}\n")
	b.WriteString("            pathType: {{ .pathType }}\n")
	b.WriteString("            backend:\n")
	b.WriteString("              service:\n")
	b.WriteString("                name: {{ include \"luxo.fullname\" $ }}-gateway\n")
	b.WriteString("                port:\n")
	b.WriteString("                  name: http\n")
	b.WriteString("          {{- end }}\n")
	b.WriteString("    {{- end }}\n")
	b.WriteString("{{- end }}\n")

	return []byte(b.String())
}

func generateHPA(modules []moduleInfo) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")

	// Gateway HPA
	b.WriteString("{{- if .Values.gateway.autoscaling.enabled }}\n")
	b.WriteString("apiVersion: autoscaling/v2\n")
	b.WriteString("kind: HorizontalPodAutoscaler\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: {{ include \"luxo.fullname\" . }}-gateway\n")
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	b.WriteString("spec:\n")
	b.WriteString("  scaleTargetRef:\n")
	b.WriteString("    apiVersion: apps/v1\n")
	b.WriteString("    kind: Deployment\n")
	b.WriteString("    name: {{ include \"luxo.fullname\" . }}-gateway\n")
	b.WriteString("  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}\n")
	b.WriteString("  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}\n")
	b.WriteString("  metrics:\n")
	b.WriteString("    - type: Resource\n")
	b.WriteString("      resource:\n")
	b.WriteString("        name: cpu\n")
	b.WriteString("        target:\n")
	b.WriteString("          type: Utilization\n")
	b.WriteString("          averageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}\n")
	b.WriteString("{{- end }}\n")

	// Per-module HPA
	for _, m := range modules {
		fmt.Fprintf(&b, "---\n")
		fmt.Fprintf(&b, "{{- if .Values.modules.%s.autoscaling.enabled }}\n", m.name)
		b.WriteString("apiVersion: autoscaling/v2\n")
		b.WriteString("kind: HorizontalPodAutoscaler\n")
		b.WriteString("metadata:\n")
		fmt.Fprintf(&b, "  name: {{ include \"luxo.fullname\" . }}-%s\n", m.name)
		b.WriteString("  labels:\n")
		b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
		b.WriteString("spec:\n")
		b.WriteString("  scaleTargetRef:\n")
		b.WriteString("    apiVersion: apps/v1\n")
		b.WriteString("    kind: Deployment\n")
		fmt.Fprintf(&b, "    name: {{ include \"luxo.fullname\" . }}-%s\n", m.name)
		fmt.Fprintf(&b, "  minReplicas: {{ .Values.modules.%s.autoscaling.minReplicas }}\n", m.name)
		fmt.Fprintf(&b, "  maxReplicas: {{ .Values.modules.%s.autoscaling.maxReplicas }}\n", m.name)
		b.WriteString("  metrics:\n")
		b.WriteString("    - type: Resource\n")
		b.WriteString("      resource:\n")
		b.WriteString("        name: cpu\n")
		b.WriteString("        target:\n")
		b.WriteString("          type: Utilization\n")
		fmt.Fprintf(&b, "          averageUtilization: {{ .Values.modules.%s.autoscaling.targetCPUUtilizationPercentage }}\n", m.name)
		fmt.Fprintf(&b, "{{- end }}\n")
	}

	return []byte(b.String())
}

func generateModuleDeployment(m moduleInfo) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: apps/v1\n")
	b.WriteString("kind: Deployment\n")
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: {{ include \"luxo.fullname\" . }}-%s\n", m.name)
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	fmt.Fprintf(&b, "    app.kubernetes.io/component: %s\n", m.name)
	b.WriteString("spec:\n")
	fmt.Fprintf(&b, "  replicas: {{ .Values.modules.%s.replicas }}\n", m.name)
	b.WriteString("  selector:\n")
	b.WriteString("    matchLabels:\n")
	b.WriteString("      {{- include \"luxo.selectorLabels\" . | nindent 6 }}\n")
	fmt.Fprintf(&b, "      app.kubernetes.io/component: %s\n", m.name)
	b.WriteString("  template:\n")
	b.WriteString("    metadata:\n")
	b.WriteString("      labels:\n")
	b.WriteString("        {{- include \"luxo.selectorLabels\" . | nindent 8 }}\n")
	fmt.Fprintf(&b, "        app.kubernetes.io/component: %s\n", m.name)
	b.WriteString("    spec:\n")
	b.WriteString("      serviceAccountName: {{ include \"luxo.serviceAccountName\" . }}\n")
	b.WriteString("      containers:\n")
	fmt.Fprintf(&b, "        - name: %s\n", m.name)
	fmt.Fprintf(&b, "          image: \"{{ .Values.image.repository }}/%s:{{ .Values.image.tag }}\"\n", m.name)
	b.WriteString("          imagePullPolicy: {{ .Values.image.pullPolicy }}\n")
	b.WriteString("          ports:\n")
	b.WriteString("            - name: http\n")
	fmt.Fprintf(&b, "              containerPort: {{ .Values.modules.%s.port }}\n", m.name)
	b.WriteString("              protocol: TCP\n")
	b.WriteString("            - name: rpc\n")
	fmt.Fprintf(&b, "              containerPort: {{ .Values.modules.%s.rpcPort }}\n", m.name)
	b.WriteString("              protocol: TCP\n")
	b.WriteString("          env:\n")
	b.WriteString("            - name: APP_PORT\n")
	fmt.Fprintf(&b, "              value: {{ .Values.modules.%s.port | quote }}\n", m.name)
	b.WriteString("            - name: LUXO_PORT\n")
	fmt.Fprintf(&b, "              value: {{ .Values.modules.%s.rpcPort | quote }}\n", m.name)
	b.WriteString("            - name: DEPLOY_MODE\n")
	b.WriteString("              value: cluster\n")
	b.WriteString("          envFrom:\n")
	b.WriteString("            - configMapRef:\n")
	b.WriteString("                name: {{ include \"luxo.fullname\" . }}-config\n")
	b.WriteString("            - secretRef:\n")
	b.WriteString("                name: {{ include \"luxo.fullname\" . }}-secret\n")
	b.WriteString("          livenessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /health\n")
	b.WriteString("              port: http\n")
	b.WriteString("            initialDelaySeconds: 5\n")
	b.WriteString("            periodSeconds: 10\n")
	b.WriteString("          readinessProbe:\n")
	b.WriteString("            httpGet:\n")
	b.WriteString("              path: /health\n")
	b.WriteString("              port: http\n")
	b.WriteString("            initialDelaySeconds: 3\n")
	b.WriteString("            periodSeconds: 5\n")
	b.WriteString("          resources:\n")
	fmt.Fprintf(&b, "            {{- toYaml .Values.modules.%s.resources | nindent 12 }}\n", m.name)

	return []byte(b.String())
}

func generateModuleService(m moduleInfo) []byte {
	var b strings.Builder
	b.WriteString("# Auto-generated by luxo. DO NOT EDIT.\n")
	b.WriteString("apiVersion: v1\n")
	b.WriteString("kind: Service\n")
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: {{ include \"luxo.fullname\" . }}-%s\n", m.name)
	b.WriteString("  labels:\n")
	b.WriteString("    {{- include \"luxo.labels\" . | nindent 4 }}\n")
	fmt.Fprintf(&b, "    app.kubernetes.io/component: %s\n", m.name)
	b.WriteString("spec:\n")
	b.WriteString("  type: ClusterIP\n")
	b.WriteString("  ports:\n")
	fmt.Fprintf(&b, "    - port: {{ .Values.modules.%s.port }}\n", m.name)
	b.WriteString("      targetPort: http\n")
	b.WriteString("      protocol: TCP\n")
	b.WriteString("      name: http\n")
	fmt.Fprintf(&b, "    - port: {{ .Values.modules.%s.rpcPort }}\n", m.name)
	b.WriteString("      targetPort: rpc\n")
	b.WriteString("      protocol: TCP\n")
	b.WriteString("      name: rpc\n")
	b.WriteString("  selector:\n")
	b.WriteString("    {{- include \"luxo.selectorLabels\" . | nindent 4 }}\n")
	fmt.Fprintf(&b, "    app.kubernetes.io/component: %s\n", m.name)

	return []byte(b.String())
}
