package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/semantic"
)

// GenerateEntryFile produces luxis/app/main.gen.go — the embedded entry point
// that imports all modules, registers handlers, and starts the Luvia gateway.
func GenerateEntryFile(result *semantic.Result, modulePath string) []byte {
	enums := collectEnums(result)

	type moduleInfo struct {
		name       string
		hasCrud    bool
		hasLoaders bool
	}

	var modules []moduleInfo
	for _, file := range result.Files {
		name := strings.TrimSuffix(file.Name, ".luxo")
		if idx := strings.LastIndex(name, "/"); idx >= 0 {
			name = name[idx+1:]
		}
		crud := false
		loaders := false
		for _, m := range file.Models {
			if hasDirective(m.Directives, "crud") {
				crud = true
			}
			if len(analyzeRelations(m, enums)) > 0 {
				loaders = true
			}
		}
		modules = append(modules, moduleInfo{name: name, hasCrud: crud, hasLoaders: loaders})
	}

	if len(modules) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by luxo. DO NOT EDIT.\n")
	b.WriteString("// Source: main.gen.go\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n\n")

	// Import each module's luxo package
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s_luxo \"%s/service/%s/luxo\"\n", m.name, modulePath, m.name)
	}

	// Import each module's resolver package
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s_resolver \"%s/service/%s/resolver\"\n", m.name, modulePath, m.name)
	}

	b.WriteString("\n\t\"github.com/light-speak/luxo/pkg/lux/dataloader\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/luvia\"\n")
	b.WriteString(")\n\n")

	// Version variable
	b.WriteString("var Version = \"dev\"\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tctx := context.Background()\n\n")
	b.WriteString("\tif err := env.Load(\".env\"); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"warning: %v\\n\", err)\n")
	b.WriteString("\t}\n\n")

	// Create each module's App
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%sApp, err := %s_luxo.New(ctx)\n", m.name, m.name)
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(&b, "\t\tfmt.Fprintf(os.Stderr, \"fatal: %s: %%v\\n\", err)\n", m.name)
		b.WriteString("\t\tos.Exit(1)\n")
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tdefer %sApp.Close()\n\n", m.name)
	}

	// Call resolver.Setup for each module
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s_resolver.Setup(%sApp)\n", m.name, m.name)
	}
	b.WriteString("\n")

	// Wire DataLoaders (embedded mode — same DB for all modules)
	b.WriteString("\tdlCfg := dataloader.DefaultConfig()\n")
	for _, m := range modules {
		if m.hasLoaders {
			fmt.Fprintf(&b, "\t%sApp.SetLoaders(%s_luxo.NewDefaultLoaders(%sApp, dlCfg))\n", m.name, m.name, m.name)
		}
	}
	b.WriteString("\n")

	// Create Luvia gateway
	b.WriteString("\tgw := luvia.New()\n\n")

	// Register modules and handlers
	for _, m := range modules {
		fmt.Fprintf(&b, "\tgw.AddModule(%q)\n", m.name)
		if m.hasCrud {
			fmt.Fprintf(&b, "\t%s_luxo.RegisterHandlers(gw.Router, %sApp)\n", m.name, m.name)
		}
	}
	b.WriteString("\n")

	// Start server
	b.WriteString("\tif err := gw.Serve(Version); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}
