package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/semantic"
)

// GenerateEntryFile produces luxis/app/main.gen.go — the embedded entry point
// that imports all modules, registers handlers, and starts the Luvia gateway.
type moduleInfo struct {
	name          string
	hasCrud       bool
	hasLoaders    bool
	hasExtend     bool // has cross-module extend (needs remote loaders in cluster mode)
	hasEvents     bool
	hasServiceFns bool
	hasSchema     bool // has models or APIs (generates RegisterSchema)
}

func collectModules(result *semantic.Result) []moduleInfo {
	enums := collectEnums(result)

	// Group files by module name (directory or single file)
	grouped := make(map[string]*moduleInfo)
	var order []string
	for _, file := range result.Files {
		modName := moduleNameFromFile(file.Name)
		if _, ok := grouped[modName]; !ok {
			grouped[modName] = &moduleInfo{name: modName}
			order = append(order, modName)
		}
		info := grouped[modName]
		for _, m := range file.Models {
			if hasDirective(m.Directives, "crud") {
				info.hasCrud = true
			}
			if len(analyzeRelations(m, enums)) > 0 {
				info.hasLoaders = true
			}
		}
		// Extend declarations need DataLoaders (cross-module load)
		if len(file.Extends) > 0 {
			info.hasLoaders = true
			info.hasExtend = true
		}
		if len(file.Events) > 0 || len(file.Listeners) > 0 {
			info.hasEvents = true
		}
		if len(file.Models) > 0 || len(file.APIs) > 0 {
			info.hasSchema = true
		}
		for _, fn := range file.Functions {
			if hasDirective(fn.Directives, "service") {
				info.hasServiceFns = true
				break
			}
		}
	}

	var modules []moduleInfo
	for _, name := range order {
		modules = append(modules, *grouped[name])
	}
	return modules
}

// moduleNameFromFile extracts the module name from a file path.
// "origin/user.luxo" → "user"
// "origin/user/model.luxo" → "user"
func moduleNameFromFile(path string) string {
	rel := strings.TrimPrefix(path, "origin/")
	parts := strings.Split(rel, "/")
	if len(parts) == 1 {
		return strings.TrimSuffix(parts[0], ".luxo")
	}
	return parts[0]
}

func GenerateEntryFile(result *semantic.Result, modulePath string) []byte {
	modules := collectModules(result)
	if len(modules) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by luxo. DO NOT EDIT.\n")
	b.WriteString("// Source: main.gen.go\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n\n")

	// Import each module's luxo package
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s_luxo \"%s/service/%s/luxo\"\n", m.name, modulePath, m.name)
	}

	// Import each module's resolver package
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s_resolver \"%s/service/%s/resolver\"\n", m.name, modulePath, m.name)
	}

	// Check if any module has events or service fns
	anyEvents := false
	anyServiceFns := false
	for _, m := range modules {
		if m.hasEvents {
			anyEvents = true
		}
		if m.hasServiceFns {
			anyServiceFns = true
		}
	}

	b.WriteString("\n\t\"github.com/light-speak/luxo/pkg/lux\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/dataloader\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	if anyEvents {
		b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/event\"\n")
	}
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/luvia\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/migrate\"\n")
	b.WriteString("\tpg \"github.com/light-speak/luxo/pkg/lux/pg\"\n")
	// rpc needed for fn @service or cluster mode DataLoaders
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/rpc\"\n")
	b.WriteString(")\n\n")

	// Version variable
	b.WriteString("var Version = \"dev\"\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tctx := context.Background()\n\n")
	b.WriteString("\tif err := env.Load(\".env\"); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"warning: %v\\n\", err)\n")
	b.WriteString("\t}\n\n")

	// Database initialization: create database + run migrations
	b.WriteString("\tif env.GetOrDefault(\"AUTO_MIGRATE\", \"true\") == \"true\" {\n")
	b.WriteString("\t\tif err := migrate.EnsureDatabase(ctx); err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"ensure db: %v\\n\", err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tmigrator, err := migrate.New(ctx, \"migrations\")\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"migrate: %v\\n\", err)\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tif applied, err := migrator.Up(ctx); err != nil {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"migrate: %v\\n\", err)\n")
	b.WriteString("\t\t\t} else if len(applied) > 0 {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"migrate: applied %d migration(s)\\n\", len(applied))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tmigrator.Close()\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	writeModuleApps(&b, modules)
	writeDataLoaderWiring(&b, modules)
	if anyEvents {
		writeEventBusWiring(&b, modules)
	}

	// Create Luvia gateway
	b.WriteString("\tgw := luvia.New()\n\n")

	// Register schema for Binary↔JSON conversion (skip event-only modules)
	for _, m := range modules {
		if m.hasSchema {
			fmt.Fprintf(&b, "\t%s_luxo.RegisterSchema(gw.Router.Schema)\n", m.name)
		}
	}
	b.WriteString("\n")

	// Register modules and handlers
	for _, m := range modules {
		fmt.Fprintf(&b, "\tgw.AddModule(%q)\n", m.name)
		if m.hasCrud {
			fmt.Fprintf(&b, "\t%s_luxo.RegisterHandlers(gw.Router, %sApp)\n", m.name, m.name)
		}
	}

	// Register service fns + batch loaders + federation resolvers + RPC server
	hasCrudModules := false
	for _, m := range modules {
		if m.hasCrud {
			hasCrudModules = true
			break
		}
	}
	if anyServiceFns || hasCrudModules {
		b.WriteString("\t// RPC endpoints — registered on router for both embedded and cluster modes\n")
		for _, m := range modules {
			if m.hasServiceFns {
				fmt.Fprintf(&b, "\t%s_luxo.RegisterServiceFns(gw.Router, %sApp)\n", m.name, m.name)
			}
		}
		for _, m := range modules {
			if m.hasCrud {
				fmt.Fprintf(&b, "\t%s_luxo.RegisterBatchLoaders(gw.Router, %sApp)\n", m.name, m.name)
				fmt.Fprintf(&b, "\t%s_luxo.RegisterFederationResolvers(gw.Router, %sApp)\n", m.name, m.name)
			}
		}
		b.WriteString("\n")
		b.WriteString("\t// RPC server — only in cluster mode (other services call via Luxo protocol)\n")
		b.WriteString("\tif deployMode == \"cluster\" {\n")
		b.WriteString("\t\trpcServer := rpc.NewServer(gw.Router)\n")
		b.WriteString("\t\tgo func() {\n")
		b.WriteString("\t\t\trpcAddr := \":\" + env.GetOrDefault(\"LUXO_PORT\", \"9000\")\n")
		b.WriteString("\t\t\tif err := rpcServer.ListenAndServe(rpcAddr); err != nil {\n")
		b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"rpc: %v\\n\", err)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}()\n")
		b.WriteString("\t\tdefer rpcServer.Close()\n")
		b.WriteString("\t}\n\n")
	}

	// Start HTTP server
	b.WriteString("\tif err := gw.Serve(Version); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

func writeModuleApps(b *strings.Builder, modules []moduleInfo) {
	// Embedded mode: all modules share one DB connection pool
	b.WriteString("\tcfg := lux.DBConfigFromEnv()\n")
	b.WriteString("\tdb, err := pg.NewDBWithConfig(ctx, cfg.ConnectionString(), cfg)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: database: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer db.Close()\n\n")

	for _, m := range modules {
		fmt.Fprintf(b, "\t%sApp := %s_luxo.NewFromDB(db)\n", m.name, m.name)
	}
	b.WriteString("\n")
	for _, m := range modules {
		fmt.Fprintf(b, "\t%s_resolver.Setup(%sApp)\n", m.name, m.name)
	}
	b.WriteString("\n")
}

func writeDataLoaderWiring(b *strings.Builder, modules []moduleInfo) {
	b.WriteString("\tdlCfg := dataloader.DefaultConfig()\n")
	b.WriteString("\tdeployMode := env.GetOrDefault(\"DEPLOY_MODE\", \"embedded\")\n\n")

	// Check if any module has cross-module extends (needs remote loaders in cluster mode)
	hasRemote := false
	for _, m := range modules {
		if m.hasExtend {
			hasRemote = true
			break
		}
	}

	if hasRemote {
		b.WriteString("\tif deployMode == \"cluster\" {\n")
		b.WriteString("\t\t// Cluster mode: extend models use RPC-backed DataLoaders\n")
		b.WriteString("\t\trpcClients := make(map[string]*rpc.Client)\n")
		for _, m := range modules {
			envKey := strings.ToUpper(m.name) + "_SERVICE_ADDR"
			defaultAddr := m.name + ":9000"
			fmt.Fprintf(b, "\t\trpcClients[%q] = rpc.NewClient(env.GetOrDefault(%q, %q))\n",
				m.name, envKey, defaultAddr)
		}
		for _, m := range modules {
			if !m.hasLoaders {
				continue
			}
			if m.hasExtend {
				// Module with cross-module extends: use RPC-backed loaders
				fmt.Fprintf(b, "\t\t%sApp.SetLoaders(%s_luxo.NewRemoteLoaders(%sApp, rpcClients, dlCfg))\n", m.name, m.name, m.name)
			} else {
				// Module with only same-module relations: use local DB
				fmt.Fprintf(b, "\t\t%sApp.SetLoaders(%s_luxo.NewDefaultLoaders(%sApp, dlCfg))\n", m.name, m.name, m.name)
			}
		}
		b.WriteString("\t} else {\n")
		b.WriteString("\t\t// Embedded mode: all DataLoaders use local DB\n")
		for _, m := range modules {
			if m.hasLoaders {
				fmt.Fprintf(b, "\t\t%sApp.SetLoaders(%s_luxo.NewDefaultLoaders(%sApp, dlCfg))\n", m.name, m.name, m.name)
			}
		}
		b.WriteString("\t}\n")
	} else {
		for _, m := range modules {
			if m.hasLoaders {
				fmt.Fprintf(b, "\t%sApp.SetLoaders(%s_luxo.NewDefaultLoaders(%sApp, dlCfg))\n", m.name, m.name, m.name)
			}
		}
	}

	b.WriteString("\t_ = deployMode\n\n")
}

func writeEventBusWiring(b *strings.Builder, modules []moduleInfo) {
	b.WriteString("\teventBus := event.NewFromEnv()\n")
	b.WriteString("\tdefer eventBus.Close()\n\n")

	for _, m := range modules {
		if m.hasEvents {
			fmt.Fprintf(b, "\t%sApp.EventBus = eventBus\n", m.name)
			fmt.Fprintf(b, "\t%s_luxo.RegisterEvents(eventBus, %sApp)\n", m.name, m.name)
		}
	}
	b.WriteString("\n")
}

// GenerateModuleEntryFiles produces per-module entry points for cluster mode.
// Each module gets its own main.gen.go under luxis/<module>/.
// Returns map[moduleName][]byte.
func GenerateModuleEntryFiles(result *semantic.Result, modulePath string) map[string][]byte {
	allModules := collectModules(result)
	if len(allModules) == 0 {
		return nil
	}

	entries := make(map[string][]byte)
	for _, target := range allModules {
		src := generateSingleModuleEntry(target, allModules, result, modulePath)
		if src != nil {
			entries[target.name] = src
		}
	}
	return entries
}

// generateSingleModuleEntry generates a standalone entry point for one module.
// Imports only this module. Cross-module DataLoaders use RPC clients.
func generateSingleModuleEntry(target moduleInfo, allModules []moduleInfo, result *semantic.Result, modulePath string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by luxo. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s/main.gen.go (cluster entry for %s module)\n\n", target.name, target.name)
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n\n")

	// Import only this module
	fmt.Fprintf(&b, "\t%s_luxo \"%s/service/%s/luxo\"\n", target.name, modulePath, target.name)
	fmt.Fprintf(&b, "\t%s_resolver \"%s/service/%s/resolver\"\n", target.name, modulePath, target.name)

	b.WriteString("\n")
	if target.hasLoaders {
		b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/dataloader\"\n")
	}
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	if target.hasEvents {
		b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/event\"\n")
	}
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/luvia\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/migrate\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/rpc\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var Version = \"dev\"\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tctx := context.Background()\n\n")
	b.WriteString("\tif err := env.Load(\".env\"); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"warning: %v\\n\", err)\n")
	b.WriteString("\t}\n\n")

	// Cluster mode: DB name = PROJECT_MODULE (e.g., wechat_user)
	fmt.Fprintf(&b, "\tif prefix := os.Getenv(\"DATABASE_PREFIX\"); prefix != \"\" {\n")
	fmt.Fprintf(&b, "\t\tos.Setenv(\"DATABASE_PREFIX\", prefix+\"_%s\")\n", target.name)
	fmt.Fprintf(&b, "\t}\n\n")

	// Auto-migrate on startup (create database if not exists + run migrations)
	b.WriteString("\tif env.GetOrDefault(\"AUTO_MIGRATE\", \"true\") == \"true\" {\n")
	b.WriteString("\t\tif err := migrate.EnsureDatabase(ctx); err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"ensure db: %v\\n\", err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tmigrator, err := migrate.New(ctx, \"migrations\")\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"migrate: %v\\n\", err)\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tif applied, err := migrator.Up(ctx); err != nil {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"migrate: %v\\n\", err)\n")
	b.WriteString("\t\t\t} else if len(applied) > 0 {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"migrate: applied %d migration(s)\\n\", len(applied))\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tmigrator.Close()\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	// Create app
	fmt.Fprintf(&b, "\tapp, err := %s_luxo.New(ctx)\n", target.name)
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\tfmt.Fprintf(os.Stderr, \"fatal: %s: %%v\\n\", err)\n", target.name)
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer app.Close()\n\n")
	fmt.Fprintf(&b, "\t%s_resolver.Setup(app)\n\n", target.name)

	// DataLoader
	if target.hasLoaders {
		b.WriteString("\tdlCfg := dataloader.DefaultConfig()\n")
		if target.hasExtend {
			// Module with cross-module extends: use RPC-backed loaders
			b.WriteString("\trpcClients := make(map[string]*rpc.Client)\n")
			for _, other := range allModules {
				if other.name == target.name {
					continue
				}
				envKey := strings.ToUpper(other.name) + "_SERVICE_ADDR"
				defaultAddr := other.name + ":9000"
				fmt.Fprintf(&b, "\trpcClients[%q] = rpc.NewClient(env.GetOrDefault(%q, %q))\n",
					other.name, envKey, defaultAddr)
			}
			fmt.Fprintf(&b, "\tapp.SetLoaders(%s_luxo.NewRemoteLoaders(app, rpcClients, dlCfg))\n\n", target.name)
		} else {
			// Module with only same-module relations: use local DB
			fmt.Fprintf(&b, "\tapp.SetLoaders(%s_luxo.NewDefaultLoaders(app, dlCfg))\n\n", target.name)
		}
	}

	// Events
	if target.hasEvents {
		b.WriteString("\teventBus := event.NewFromEnv()\n")
		b.WriteString("\tdefer eventBus.Close()\n")
		b.WriteString("\tapp.EventBus = eventBus\n")
		fmt.Fprintf(&b, "\t%s_luxo.RegisterEvents(eventBus, app)\n\n", target.name)
	}

	// Gateway + handlers
	b.WriteString("\tgw := luvia.New()\n")
	fmt.Fprintf(&b, "\tgw.AddModule(%q)\n", target.name)
	if target.hasCrud {
		fmt.Fprintf(&b, "\t%s_luxo.RegisterHandlers(gw.Router, app)\n", target.name)
		fmt.Fprintf(&b, "\t%s_luxo.RegisterBatchLoaders(gw.Router, app)\n", target.name)
	}
	if target.hasServiceFns {
		fmt.Fprintf(&b, "\t%s_luxo.RegisterServiceFns(gw.Router, app)\n", target.name)
	}
	b.WriteString("\n")

	// RPC server (cluster mode — other services call us)
	b.WriteString("\trpcServer := rpc.NewServer(gw.Router)\n")
	b.WriteString("\tgo func() {\n")
	b.WriteString("\t\trpcAddr := \":\" + env.GetOrDefault(\"LUXO_PORT\", \"9000\")\n")
	b.WriteString("\t\tif err := rpcServer.ListenAndServe(rpcAddr); err != nil {\n")
	b.WriteString("\t\t\tfmt.Fprintf(os.Stderr, \"rpc: %v\\n\", err)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}()\n")
	b.WriteString("\tdefer rpcServer.Close()\n\n")

	// Start HTTP
	b.WriteString("\tif err := gw.Serve(Version); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

// GenerateGatewayEntry produces luxis/gateway/main.gen.go — a pure routing gateway.
// Routes API requests to the correct backend service via Luxo RPC.
// Owns the full schema for Binary↔JSON conversion. No handler code.
func GenerateGatewayEntry(result *semantic.Result, modulePath string) []byte {
	allModules := collectModules(result)
	if len(allModules) == 0 {
		return nil
	}

	// Build API → module mapping
	// Collect compiled API names first for dedup
	compiledAPIs := make(map[string]bool)
	for _, file := range result.Files {
		for _, a := range file.APIs {
			compiledAPIs[a.Name] = true
		}
	}

	routeMap := make(map[string]string) // apiName → moduleName (deduplicates)
	var routeOrder []string
	addRoute := func(name, mod string) {
		if _, exists := routeMap[name]; !exists {
			routeOrder = append(routeOrder, name)
		}
		routeMap[name] = mod
	}

	for _, file := range result.Files {
		modName := moduleNameFromFile(file.Name)
		for _, m := range file.Models {
			if !hasCrud(m) {
				continue
			}
			for _, op := range crudOperations(m) {
				apiName := crudAPIName(m.Name, op)
				if compiledAPIs[apiName] {
					continue // compiled API overrides CRUD
				}
				addRoute(apiName, modName)
			}
		}
		for _, a := range file.APIs {
			if hasDirective(a.Directives, "stream") {
				continue // stream APIs registered separately
			}
			addRoute(a.Name, modName)
		}
		for _, fn := range file.Functions {
			if hasDirective(fn.Directives, "service") {
				addRoute("svc:"+fn.Name, modName)
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by luxo. DO NOT EDIT.\n")
	b.WriteString("// Source: gateway/main.gen.go (Luvia Gateway — API router)\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n\n")

	for _, m := range allModules {
		if m.hasSchema || m.hasCrud || m.hasServiceFns {
			fmt.Fprintf(&b, "\t%s_luxo \"%s/service/%s/luxo\"\n", m.name, modulePath, m.name)
		}
	}

	b.WriteString("\n\t\"encoding/json\"\n")
	b.WriteString("\t\"sync\"\n\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/api\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/codec\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/luvia\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/rpc\"\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/schema\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var Version = \"dev\"\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tif err := env.Load(\".env\"); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"warning: %v\\n\", err)\n")
	b.WriteString("\t}\n\n")

	// RPC clients — default address = moduleName:9000 (Docker/K8s DNS)
	b.WriteString("\trpcClients := map[string]*rpc.Client{}\n")
	for _, m := range allModules {
		envKey := strings.ToUpper(m.name) + "_SERVICE_ADDR"
		defaultAddr := m.name + ":9000"
		fmt.Fprintf(&b, "\trpcClients[%q] = rpc.NewClient(env.GetOrDefault(%q, %q))\n",
			m.name, envKey, defaultAddr)
	}
	b.WriteString("\n")

	// Gateway
	b.WriteString("\tgw := luvia.New()\n\n")

	// Schema (skip event-only modules)
	for _, m := range allModules {
		if m.hasSchema {
			fmt.Fprintf(&b, "\t%s_luxo.RegisterSchema(gw.Router.Schema)\n", m.name)
		}
	}
	b.WriteString("\n")

	// Routing table (deduplicated)
	b.WriteString("\trouting := map[string]string{\n")
	for _, name := range routeOrder {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", name, routeMap[name])
	}
	b.WriteString("\t}\n")
	b.WriteString("\tfor apiName, moduleName := range routing {\n")
	b.WriteString("\t\tclient := rpcClients[moduleName]\n")
	b.WriteString("\t\tif client == nil {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tgw.Router.Handle(apiName, proxyHandler(client, gw.Router.Schema, apiName, rpcClients))\n")
	b.WriteString("\t}\n\n")

	for _, m := range allModules {
		fmt.Fprintf(&b, "\tgw.AddModule(%q)\n", m.name)
	}
	b.WriteString("\n")

	b.WriteString("\t_ = context.Background\n\n")

	b.WriteString("\tif err := gw.Serve(Version); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// proxyHandler with federation support
	b.WriteString("// proxyHandler forwards requests to a backend service via Luxo RPC.\n")
	b.WriteString("// If the API's return model has extend fields in the request mask,\n")
	b.WriteString("// uses federation: splits request, parallel RPC, merges responses.\n")
	b.WriteString("func proxyHandler(client *rpc.Client, s *schema.Schema, apiName string, rpcClients map[string]*rpc.Client) api.HandlerFunc {\n")
	b.WriteString("\tapiMeta := s.APIs[apiName]\n")
	b.WriteString("\tapiID := 0\n")
	b.WriteString("\tvar model *schema.Model\n")
	b.WriteString("\tif apiMeta != nil {\n")
	b.WriteString("\t\tapiID = apiMeta.ID\n")
	b.WriteString("\t\tmodel = s.Models[apiMeta.ReturnType]\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn func(ctx context.Context, req *api.Request) error {\n")
	b.WriteString("\t\t// Encode params: JSON raw params → binary using schema\n")
	b.WriteString("\t\tvar params []byte\n")
	b.WriteString("\t\tif apiMeta != nil && len(req.Params) > 0 {\n")
	b.WriteString("\t\t\tjsonParams := make(map[string]any, len(req.Params))\n")
	b.WriteString("\t\t\tfor k, v := range req.Params {\n")
	b.WriteString("\t\t\t\tvar val any\n")
	b.WriteString("\t\t\t\tif err := json.Unmarshal(v, &val); err == nil {\n")
	b.WriteString("\t\t\t\t\tjsonParams[k] = val\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tparams = schema.JSONParamsToBinary(jsonParams, apiMeta)\n")
	b.WriteString("\t\t}\n\n")

	// Federation: query planning
	b.WriteString("\t\t// Federation: check if request needs cross-module field resolution\n")
	b.WriteString("\t\tvar apiModule string\n")
	b.WriteString("\t\tif apiMeta != nil { apiModule = apiMeta.Module }\n")
	b.WriteString("\t\tplan := luvia.Plan(model, req.FieldMask, apiModule)\n")
	b.WriteString("\t\tif plan == nil {\n")
	b.WriteString("\t\t\t// No extend fields — direct forward with field mask\n")
	b.WriteString("\t\t\tresp, err := client.CallWithMask(apiID, req.FieldMask, params)\n")
	b.WriteString("\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\treturn err\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treq.Buf.B = append(req.Buf.B, resp...)\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t}\n\n")

	// Federation: parallel RPC
	b.WriteString("\t\t// Primary request with federation mask (local fields + id)\n")
	b.WriteString("\t\tresp, err := client.CallWithMask(apiID, plan.Primary.Mask, params)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n\n")

	// Helper: encode resolve keys (same format as batchLoad: field1=count, field2=keys)
	b.WriteString("\t\t// resolveKeys encodes FK values for svc:resolve RPC\n")
	b.WriteString("\t\tresolveKeys := func(ids []int64) []byte {\n")
	b.WriteString("\t\t\tvar enc codec.Encoder\n")
	b.WriteString("\t\t\tenc.WriteFieldInt(1, int64(len(ids)))\n")
	b.WriteString("\t\t\tfor _, k := range ids { enc.WriteFieldInt(2, k) }\n")
	b.WriteString("\t\t\tenc.WriteEnd()\n")
	b.WriteString("\t\t\treturn enc.Bytes()\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString("\t\tif apiMeta.ReturnList {\n")
	b.WriteString("\t\t\t// List federation: extract ID column, resolve extends\n")
	b.WriteString("\t\t\tids := luvia.ExtractIDColumn(resp, plan.IDFieldID, model)\n")
	b.WriteString("\t\t\tif len(ids) == 0 {\n")
	b.WriteString("\t\t\t\treq.Buf.B = append(req.Buf.B, resp...)\n")
	b.WriteString("\t\t\t\treturn nil\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tresolveCol := func(ext luvia.ExtendStep, cl *rpc.Client) luvia.ExtendColumnResult {\n")
	b.WriteString("\t\t\t\tsvcName := \"svc:resolve:\" + ext.ModelName + \":\" + ext.ForeignKey\n")
	b.WriteString("\t\t\t\tresolveAPI := s.APIs[svcName]\n")
	b.WriteString("\t\t\t\tif resolveAPI == nil { return luvia.ExtendColumnResult{} }\n")
	b.WriteString("\t\t\t\textResp, err := cl.CallWithMask(resolveAPI.ID, req.FieldMask, resolveKeys(ids))\n")
	b.WriteString("\t\t\t\tif err != nil { return luvia.ExtendColumnResult{} }\n")
	b.WriteString("\t\t\t\tblobs := luvia.ParseGroupedResponse(extResp, ext.IsList)\n")
	b.WriteString("\t\t\t\treturn luvia.ExtendColumnResult{FieldID: ext.FieldID, Blobs: blobs}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\textCols := make([]luvia.ExtendColumnResult, len(plan.Extends))\n")
	b.WriteString("\t\t\tif len(plan.Extends) == 1 {\n")
	b.WriteString("\t\t\t\text := plan.Extends[0]\n")
	b.WriteString("\t\t\t\tif cl := rpcClients[ext.Module]; cl != nil {\n")
	b.WriteString("\t\t\t\t\textCols[0] = resolveCol(ext, cl)\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tvar wg sync.WaitGroup\n")
	b.WriteString("\t\t\t\tfor ei, ext := range plan.Extends {\n")
	b.WriteString("\t\t\t\t\tif cl := rpcClients[ext.Module]; cl != nil {\n")
	b.WriteString("\t\t\t\t\t\twg.Add(1)\n")
	b.WriteString("\t\t\t\t\t\tgo func(idx int, ext luvia.ExtendStep, cl *rpc.Client) {\n")
	b.WriteString("\t\t\t\t\t\t\tdefer wg.Done()\n")
	b.WriteString("\t\t\t\t\t\t\textCols[idx] = resolveCol(ext, cl)\n")
	b.WriteString("\t\t\t\t\t\t}(ei, ext, cl)\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\twg.Wait()\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tmerged := luvia.MergeColumnar(resp, extCols)\n")
	b.WriteString("\t\t\treq.Buf.B = append(req.Buf.B, merged...)\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString("\t\t// Single record federation: extract ID, resolve extends\n")
	b.WriteString("\t\tprimaryID, ok := luvia.ExtractID(resp, plan.IDFieldID, plan.FieldTypes)\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\treq.Buf.B = append(req.Buf.B, resp...)\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t}\n")

	// Group extends by SvcName — same resolve endpoint shares one RPC call
	b.WriteString("\t\t// Deduplicate: group extends by resolve endpoint, parallel per unique endpoint\n")
	b.WriteString("\t\tsvcGroups := map[string][]int{} // svcName → indices into plan.Extends\n")
	b.WriteString("\t\tfor i, ext := range plan.Extends {\n")
	b.WriteString("\t\t\tsvcGroups[ext.SvcName] = append(svcGroups[ext.SvcName], i)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tsvcResp := make(map[string][]byte, len(svcGroups))\n")
	b.WriteString("\t\tif len(svcGroups) == 1 {\n")
	b.WriteString("\t\t\t// Single unique endpoint — direct call\n")
	b.WriteString("\t\t\tfor svcName := range svcGroups {\n")
	b.WriteString("\t\t\t\text := plan.Extends[svcGroups[svcName][0]]\n")
	b.WriteString("\t\t\t\tif cl := rpcClients[ext.Module]; cl != nil {\n")
	b.WriteString("\t\t\t\t\tresolveAPI := s.APIs[svcName]\n")
	b.WriteString("\t\t\t\t\tif resolveAPI != nil {\n")
	b.WriteString("\t\t\t\t\t\tr, e := cl.CallWithMask(resolveAPI.ID, req.FieldMask, resolveKeys([]int64{primaryID}))\n")
	b.WriteString("\t\t\t\t\t\tif e == nil { svcResp[svcName] = r }\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\t// Multiple unique endpoints — parallel\n")
	b.WriteString("\t\t\tvar mu sync.Mutex\n")
	b.WriteString("\t\t\tvar wg sync.WaitGroup\n")
	b.WriteString("\t\t\tfor svcName, idxs := range svcGroups {\n")
	b.WriteString("\t\t\t\text := plan.Extends[idxs[0]]\n")
	b.WriteString("\t\t\t\tcl := rpcClients[ext.Module]\n")
	b.WriteString("\t\t\t\tif cl == nil { continue }\n")
	b.WriteString("\t\t\t\tresolveAPI := s.APIs[svcName]\n")
	b.WriteString("\t\t\t\tif resolveAPI == nil { continue }\n")
	b.WriteString("\t\t\t\twg.Add(1)\n")
	b.WriteString("\t\t\t\tgo func(name string, cl *rpc.Client, apiID int) {\n")
	b.WriteString("\t\t\t\t\tdefer wg.Done()\n")
	b.WriteString("\t\t\t\t\tr, e := cl.CallWithMask(apiID, req.FieldMask, resolveKeys([]int64{primaryID}))\n")
	b.WriteString("\t\t\t\t\tif e == nil { mu.Lock(); svcResp[name] = r; mu.Unlock() }\n")
	b.WriteString("\t\t\t\t}(svcName, cl, resolveAPI.ID)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\twg.Wait()\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\t// Distribute results to all extends sharing the same endpoint\n")
	b.WriteString("\t\textResults := make([]luvia.ExtendResult, len(plan.Extends))\n")
	b.WriteString("\t\tfor ei, ext := range plan.Extends {\n")
	b.WriteString("\t\t\tif r, ok := svcResp[ext.SvcName]; ok {\n")
	b.WriteString("\t\t\t\tblobs := luvia.ParseGroupedResponse(r, ext.IsList)\n")
	b.WriteString("\t\t\t\tif len(blobs) > 0 && len(blobs[0]) > 0 {\n")
	b.WriteString("\t\t\t\t\textResults[ei] = luvia.ExtendResult{FieldID: ext.FieldID, Data: blobs[0]}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tmerged := luvia.Merge(resp, extResults)\n")
	b.WriteString("\t\treq.Buf.B = append(req.Buf.B, merged...)\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}
