package codegen

import (
	"fmt"
	"strings"

	"github.com/light-speak/luxo/pkg/semantic"
)

// InitResult holds scaffold files generated by Init (one-time, not overwritten).
type InitResult struct {
	Files map[string][]byte // relative path → content
}

// Init generates project scaffold files that are created once and never overwritten.
// These include cmd/app/main.go and resolver/resolver.go.
func Init(result *semantic.Result, modulePath, packageName string) *InitResult {
	ir := &InitResult{
		Files: make(map[string][]byte),
	}

	ir.Files["cmd/app/main.go"] = generateMainGo(modulePath, packageName)
	ir.Files["resolver/resolver.go"] = generateResolverGo()

	return ir
}

// generateMainGo produces the cmd/app/main.go entry point.
func generateMainGo(modulePath, packageName string) []byte {
	var b strings.Builder

	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "\t\"%s/%s\"\n", modulePath, packageName)
	fmt.Fprintf(&b, "\t\"%s/resolver\"\n", modulePath)
	b.WriteString("\n")
	b.WriteString("\t\"github.com/light-speak/luxo/pkg/lux/env\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tctx := context.Background()\n")
	b.WriteString("\n")
	b.WriteString("\t// Load .env file\n")
	b.WriteString("\tif err := env.Load(\".env\"); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"warning: %v\\n\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\n")
	b.WriteString("\t// Initialize app\n")
	fmt.Fprintf(&b, "\tapp, err := %s.New(ctx)\n", packageName)
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"fatal: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer app.Close()\n")
	b.WriteString("\n")
	b.WriteString("\t// Setup user hooks and dependencies\n")
	b.WriteString("\tresolver.Setup(app)\n")
	b.WriteString("\n")
	b.WriteString("\t// TODO: start HTTP server\n")
	b.WriteString("\t_ = app\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

// generateResolverGo produces the resolver/resolver.go scaffold.
func generateResolverGo() []byte {
	var b strings.Builder

	b.WriteString("package resolver\n\n")
	b.WriteString("// Resolver holds custom dependencies for @native method implementations.\n")
	b.WriteString("// Add your own fields here (API clients, services, etc.).\n")
	b.WriteString("type Resolver struct {\n")
	b.WriteString("\t// Example:\n")
	b.WriteString("\t// Stripe *stripe.Client\n")
	b.WriteString("\t// Redis  *redis.Client\n")
	b.WriteString("}\n\n")

	b.WriteString("// Setup initializes custom dependencies and hooks.\n")
	b.WriteString("// Called once at startup from cmd/app/main.go.\n")
	b.WriteString("func Setup(app any) {\n")
	b.WriteString("\t// Example:\n")
	b.WriteString("\t// app.Use(corsMiddleware)\n")
	b.WriteString("\t// app.OnShutdown(func() { redis.Close() })\n")
	b.WriteString("}\n")

	return []byte(b.String())
}
