package codegen

import (
	"strings"
	"testing"
)

func TestInitProject(t *testing.T) {
	sr := InitProject("github.com/example/myapp")

	expected := []string{".gitignore", ".env.example", "go.mod"}
	for _, name := range expected {
		if _, ok := sr.Files[name]; !ok {
			t.Errorf("missing %s", name)
		}
	}
}

func TestInitProjectGoMod(t *testing.T) {
	sr := InitProject("github.com/example/myapp")
	src := string(sr.Files["go.mod"])

	checks := []string{
		"module github.com/example/myapp",
		"go 1.26.0",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Errorf("missing %q in go.mod:\n%s", check, src)
		}
	}
}

func TestInitProjectGitignore(t *testing.T) {
	sr := InitProject("github.com/example/myapp")
	src := string(sr.Files[".gitignore"])

	checks := []string{".env", "bin/", ".DS_Store", "*.cov"}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Errorf("missing %q in .gitignore:\n%s", check, src)
		}
	}
}

func TestInitProjectEnvExample(t *testing.T) {
	sr := InitProject("github.com/example/myapp")
	src := string(sr.Files[".env.example"])

	checks := []string{
		"DATABASE_DRIVER=pg",
		"JWT_SECRET=change-me",
		"DEPLOY_MODE=embedded",
		"CORS_ORIGINS=*",
		"LOG_LEVEL=info",
		"HEALTH_PATH=/health",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Errorf("missing %q in .env.example:\n%s", check, src)
		}
	}
}

func TestAddModule(t *testing.T) {
	sr := AddModule("github.com/example/myapp", "user")

	expected := []string{
		"origin/user.luxo",
		"service/user/resolver/resolver.go",
	}
	for _, name := range expected {
		if _, ok := sr.Files[name]; !ok {
			t.Errorf("missing %s", name)
		}
	}
}

func TestAddModuleSchema(t *testing.T) {
	sr := AddModule("github.com/example/myapp", "user")
	src := string(sr.Files["origin/user.luxo"])

	checks := []string{
		"User module",
		"model User",
		"id:        UUID      @auto",
		"createdAt: DateTime",
		"updatedAt: DateTime",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Errorf("missing %q in user.luxo:\n%s", check, src)
		}
	}
}

func TestAddModuleResolver(t *testing.T) {
	sr := AddModule("github.com/example/myapp", "user")
	src := string(sr.Files["service/user/resolver/resolver.go"])

	checks := []string{
		"package resolver",
		"type Resolver struct",
		"func Setup(app *luxo.App)",
		"user module",
	}
	for _, check := range checks {
		if !strings.Contains(src, check) {
			t.Errorf("missing %q in resolver.go:\n%s", check, src)
		}
	}
}

// TestAddModuleNoLuxisMain guards against re-introducing a hand-written
// luxis/<module>/main.go scaffold: `luxo gen` emits main.gen.go in that same
// directory, so a second main.go would collide (duplicate package main / func main).
func TestAddModuleNoLuxisMain(t *testing.T) {
	sr := AddModule("github.com/example/myapp", "user")

	if _, ok := sr.Files["luxis/user/main.go"]; ok {
		t.Error("AddModule must not generate luxis/user/main.go — it collides with luxo gen's main.gen.go")
	}
	for path := range sr.Files {
		if strings.HasPrefix(path, "luxis/") {
			t.Errorf("AddModule must not write under luxis/ (generated by luxo gen), got %q", path)
		}
	}
}

func TestAddModuleDifferentNames(t *testing.T) {
	tests := []struct {
		module    string
		modelName string
	}{
		{"user", "User"},
		{"order", "Order"},
		{"payment", "Payment"},
	}
	for _, tt := range tests {
		t.Run(tt.module, func(t *testing.T) {
			sr := AddModule("github.com/example/myapp", tt.module)
			schema := string(sr.Files["origin/"+tt.module+".luxo"])
			if !strings.Contains(schema, "model "+tt.modelName) {
				t.Errorf("missing model %s in schema:\n%s", tt.modelName, schema)
			}
			resolverSrc := string(sr.Files["service/"+tt.module+"/resolver/resolver.go"])
			if !strings.Contains(resolverSrc, "package resolver") {
				t.Errorf("missing resolver package for module %s:\n%s", tt.module, resolverSrc)
			}
		})
	}
}
