package codec

// LuxoMarshaler is implemented by types that can encode themselves to Luxo binary.
// Generated by codegen for event structs and model structs.
type LuxoMarshaler interface {
	MarshalLuxo() []byte
}

// LuxoUnmarshaler is implemented by types that can decode themselves from Luxo binary.
type LuxoUnmarshaler interface {
	UnmarshalLuxo(data []byte) error
}

// Encoder builds a binary message by appending fields.
// Zero allocation after initial buffer — reuse via Reset().
//
// Usage (generated code):
//
//	var enc codec.Encoder
//	enc.WriteFieldInt(1, event.TaskId)
//	enc.WriteFieldString(2, event.Name)
//	data := enc.Bytes()
type Encoder struct {
	buf []byte
}

// Reset clears the buffer for reuse.
func (e *Encoder) Reset() {
	e.buf = e.buf[:0]
}

// Bytes returns the encoded bytes. Valid until next Reset/Write call.
func (e *Encoder) Bytes() []byte {
	return e.buf
}

// --- Field writers ---
// Each writes: [fieldID varint] [value]

// WriteFieldInt writes a signed int64 field.
func (e *Encoder) WriteFieldInt(fieldID int, v int64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendSvarint(e.buf, v)
}

// WriteFieldFloat writes a float64 field.
func (e *Encoder) WriteFieldFloat(fieldID int, v float64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendFixed64(e.buf, v)
}

// WriteFieldString writes a string field.
func (e *Encoder) WriteFieldString(fieldID int, v string) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendString(e.buf, v)
}

// WriteFieldBool writes a boolean field.
func (e *Encoder) WriteFieldBool(fieldID int, v bool) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendBool(e.buf, v)
}

// WriteFieldBytes writes a raw bytes field.
func (e *Encoder) WriteFieldBytes(fieldID int, v []byte) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendBytes(e.buf, v)
}

// --- Nullable field writers ---
// Writes: [fieldID varint] [0x00=null | 0x01 + value]

// WriteFieldIntPtr writes a nullable int64 field.
func (e *Encoder) WriteFieldIntPtr(fieldID int, v *int64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	if v == nil {
		e.buf = AppendNull(e.buf)
	} else {
		e.buf = AppendPresent(e.buf)
		e.buf = AppendSvarint(e.buf, *v)
	}
}

// WriteFieldFloatPtr writes a nullable float64 field.
func (e *Encoder) WriteFieldFloatPtr(fieldID int, v *float64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	if v == nil {
		e.buf = AppendNull(e.buf)
	} else {
		e.buf = AppendPresent(e.buf)
		e.buf = AppendFixed64(e.buf, *v)
	}
}

// WriteFieldStringPtr writes a nullable string field.
func (e *Encoder) WriteFieldStringPtr(fieldID int, v *string) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	if v == nil {
		e.buf = AppendNull(e.buf)
	} else {
		e.buf = AppendPresent(e.buf)
		e.buf = AppendString(e.buf, *v)
	}
}

// WriteFieldBoolPtr writes a nullable boolean field.
func (e *Encoder) WriteFieldBoolPtr(fieldID int, v *bool) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	if v == nil {
		e.buf = AppendNull(e.buf)
	} else {
		e.buf = AppendPresent(e.buf)
		e.buf = AppendBool(e.buf, *v)
	}
}

// --- Array field writers ---
// Format: [fieldID varint] [count varint] [item0] [item1] ...

// WriteFieldIntArray writes an int64 array field.
func (e *Encoder) WriteFieldIntArray(fieldID int, v []int64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendSvarint(e.buf, item)
	}
}

// WriteFieldStringArray writes a string array field.
func (e *Encoder) WriteFieldStringArray(fieldID int, v []string) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendString(e.buf, item)
	}
}

// WriteFieldFloatArray writes a float64 array field.
func (e *Encoder) WriteFieldFloatArray(fieldID int, v []float64) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendFixed64(e.buf, item)
	}
}

// WriteFieldBoolArray writes a bool array field.
func (e *Encoder) WriteFieldBoolArray(fieldID int, v []bool) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendBool(e.buf, item)
	}
}

// WriteFieldBytesArray writes a [][]byte array field. Each element is a
// length-prefixed byte blob — used for lists of nested models (each element is
// a model's Luxo binary) and for [Bytes]/[JSON] lists.
func (e *Encoder) WriteFieldBytesArray(fieldID int, v [][]byte) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendBytes(e.buf, item)
	}
}

// WriteFieldUUID writes a fixed 16-byte UUID field.
func (e *Encoder) WriteFieldUUID(fieldID int, v [16]byte) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendUUID(e.buf, v)
}

// WriteFieldUUIDPtr writes a nullable UUID field.
func (e *Encoder) WriteFieldUUIDPtr(fieldID int, v *[16]byte) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	if v == nil {
		e.buf = AppendNull(e.buf)
	} else {
		e.buf = AppendPresent(e.buf)
		e.buf = AppendUUID(e.buf, *v)
	}
}

// WriteFieldUUIDArray writes a UUID array field. Each element is a fixed
// 16-byte value (no per-item length prefix), per the protocol UUID encoding.
func (e *Encoder) WriteFieldUUIDArray(fieldID int, v [][16]byte) {
	e.buf = AppendVarint(e.buf, uint64(fieldID))
	e.buf = AppendArrayHeader(e.buf, len(v))
	for _, item := range v {
		e.buf = AppendUUID(e.buf, item)
	}
}

// WriteEnd writes the message terminator (fieldID 0).
func (e *Encoder) WriteEnd() {
	e.buf = append(e.buf, 0x00)
}
