import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { LuxoSchema, LuxoAPI } from '@luxo/client'

/** Generate TypeScript types + client from Luxo schema */
export async function generateTypes(schema: LuxoSchema, outDir: string): Promise<void> {
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  writeFileSync(join(outDir, 'types.ts'), genTypes(schema))
  writeFileSync(join(outDir, 'client.ts'), genClient(schema))
  console.log(`[luxo] Generated types → ${outDir}/`)
}

function luxoTypeToTS(type: string): string {
  switch (type) {
    case 'Int': case 'Float': case 'Duration': return 'number'
    case 'String': case 'DateTime': case 'UUID': case 'Decimal': case 'Enum': return 'string'
    case 'Boolean': return 'boolean'
    case 'Bytes': return 'string'
    default: return type // model reference
  }
}

function genTypes(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Page } from '@luxo/client'\n\n"

  for (const model of Object.values(schema.models)) {
    out += `export interface ${model.name} {\n`
    for (const field of model.fields) {
      const ts = luxoTypeToTS(field.type)
      if (field.nullable) {
        out += `  ${field.name}: ${ts} | null\n`
      } else {
        out += `  ${field.name}: ${ts}\n`
      }
    }
    out += '}\n\n'
  }

  out += 'export type { Page }\n'
  return out
}

function genClient(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Transport, Page } from '@luxo/client'\n"

  // Collect model type imports
  const typeImports = new Set<string>()
  for (const api of Object.values(schema.apis)) {
    if (api.returnType && !isScalar(api.returnType)) {
      typeImports.add(api.returnType)
    }
  }
  if (typeImports.size > 0) {
    out += `import type { ${Array.from(typeImports).join(', ')} } from './types'\n`
  }

  out += '\nexport class LuxoClient {\n'
  out += '  constructor(private transport: Transport) {}\n\n'

  for (const api of Object.values(schema.apis)) {
    // Skip internal service fns
    if (api.name.startsWith('svc:')) continue

    out += genMethod(api, schema)
  }

  out += '}\n'
  return out
}

function genMethod(api: LuxoAPI, schema: LuxoSchema): string {
  const retTS = getReturnType(api)

  // Detect CRUD patterns by name
  if (api.name.startsWith('get') && !api.returnList) {
    return `  async ${api.name}(id: number, opts?: { $select?: string }): Promise<${retTS}> {\n` +
           `    return this.transport.call('${api.name}', { id, ...opts })\n  }\n\n`
  }

  if (api.name.startsWith('list')) {
    return `  async ${api.name}(params?: { page?: number; pageSize?: number; $select?: string; $filters?: unknown[]; $sorters?: unknown[] }): Promise<${retTS}> {\n` +
           `    return this.transport.call('${api.name}', params)\n  }\n\n`
  }

  if (api.name.startsWith('create') && api.returnType) {
    return `  async ${api.name}(input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           `    return this.transport.call('${api.name}', input)\n  }\n\n`
  }

  if (api.name.startsWith('update') && api.returnType) {
    return `  async ${api.name}(id: number, input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           `    return this.transport.call('${api.name}', { id, ...input })\n  }\n\n`
  }

  if (api.name.startsWith('delete')) {
    if (api.name.endsWith('s')) {
      return `  async ${api.name}(ids: number[]): Promise<number> {\n` +
             `    return this.transport.call('${api.name}', { ids })\n  }\n\n`
    }
    return `  async ${api.name}(id: number): Promise<number> {\n` +
           `    return this.transport.call('${api.name}', { id })\n  }\n\n`
  }

  // Custom API
  if (api.params && api.params.length > 0) {
    const paramStr = api.params.map(p => `${p.name}: ${luxoTypeToTS(p.type)}`).join('; ')
    return `  async ${api.name}(params: { ${paramStr} }): Promise<${retTS}> {\n` +
           `    return this.transport.call('${api.name}', params)\n  }\n\n`
  }

  return `  async ${api.name}(): Promise<${retTS}> {\n` +
         `    return this.transport.call('${api.name}')\n  }\n\n`
}

function getReturnType(api: LuxoAPI): string {
  if (!api.returnType) return 'number'
  const ts = luxoTypeToTS(api.returnType)
  if (api.paginated) return `Page<${ts}>`
  if (api.returnList) return `${ts}[]`
  return ts
}

function isScalar(type: string): boolean {
  return ['Int', 'Float', 'String', 'Boolean', 'DateTime', 'Duration', 'UUID', 'Bytes', 'Decimal'].includes(type)
}
