import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { LuxoSchema, LuxoAPI } from '@luxo/client'

/** Generate TypeScript types + client from Luxo schema */
export async function generateTypes(schema: LuxoSchema, outDir: string): Promise<void> {
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  writeFileSync(join(outDir, 'types.ts'), genTypes(schema))
  writeFileSync(join(outDir, 'schema.ts'), genSchema(schema))
  writeFileSync(join(outDir, 'client.ts'), genClient(schema))
  console.log(`[luxo] Generated types → ${outDir}/`)
}

function luxoTypeToTS(type: string): string {
  switch (type) {
    case 'Int': case 'Float': case 'Duration': return 'number'
    case 'String': case 'DateTime': case 'UUID': case 'Decimal': case 'Enum': return 'string'
    case 'Boolean': return 'boolean'
    case 'Bytes': return 'string'
    default: return type // model reference
  }
}

// --- types.ts ---

/** Resolve field type to TypeScript, using typeName for model/enum references */
function resolveFieldType(field: { type: string; typeName?: string; isList?: boolean; list?: boolean }, schema: LuxoSchema): string {
  const isList = field.isList || field.list
  const typeName = field.typeName || field.type
  let ts: string

  // Check if it's an enum
  if (schema.enums?.[typeName]) {
    ts = typeName
  } else if (schema.models[typeName]) {
    ts = typeName // model reference
  } else if (schema.types?.[typeName]) {
    ts = typeName // type declaration reference
  } else {
    ts = luxoTypeToTS(field.type)
  }

  return isList ? `${ts}[]` : ts
}

function genTypes(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Page } from '@luxo/client'\n"
  out += "import { Decoder } from '@luxo/client'\n\n"

  // Enum types — union of string literals
  if (schema.enums) {
    for (const e of Object.values(schema.enums)) {
      const values = e.values.map((v: string) => `'${v}'`).join(' | ')
      out += `export type ${e.name} = ${values}\n`
      out += `export const ${e.name}Values = [${e.values.map((v: string) => `'${v}'`).join(', ')}] as const\n\n`
    }
  }

  // Type declarations (non-DB: AuthPayload, ProjectOverview, etc.)
  if (schema.types) {
    for (const t of Object.values(schema.types)) {
      out += `export interface ${t.name} {\n`
      for (const field of t.fields) {
        const ts = resolveFieldType(field, schema)
        out += field.nullable ? `  ${field.name}: ${ts} | null\n` : `  ${field.name}: ${ts}\n`
      }
      out += '}\n\n'
    }
  }

  // Model interfaces
  for (const model of Object.values(schema.models)) {
    out += `export interface ${model.name} {\n`
    for (const field of model.fields) {
      const ts = resolveFieldType(field, schema)
      out += field.nullable ? `  ${field.name}: ${ts} | null\n` : `  ${field.name}: ${ts}\n`
    }
    out += '}\n\n'

    // Binary decoder function — reads from Luxo binary using field IDs
    out += `export function decode${model.name}(dec: Decoder): ${model.name} {\n`
    out += `  const obj: Record<string, unknown> = {}\n`
    out += `  while (dec.nextField()) {\n`
    out += `    switch (dec.fieldID) {\n`
    for (const field of model.fields) {
      out += `      case ${field.id}: obj['${field.name}'] = `
      out += genFieldRead(field) + '; break\n'
    }
    out += `      default: break\n`
    out += `    }\n`
    out += `  }\n`
    out += `  return obj as ${model.name}\n`
    out += '}\n\n'
  }

  out += 'export type { Page }\n'
  return out
}

function genFieldRead(field: { type: string; nullable?: boolean }): string {
  const n = field.nullable
  switch (field.type) {
    case 'Int': case 'Duration': return n ? 'dec.readIntPtr()' : 'dec.readInt()'
    case 'Float': return n ? 'dec.readFloatPtr()' : 'dec.readFloat()'
    case 'String': case 'DateTime': case 'UUID': case 'Decimal': case 'Enum':
      return n ? 'dec.readStringPtr()' : 'dec.readString()'
    case 'Boolean': return n ? 'dec.readBoolPtr()' : 'dec.readBool()'
    default: return 'null' // nested model — TODO
  }
}

// --- schema.ts ---

function genSchema(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { APISchema } from '@luxo/client'\n\n"

  out += '/** API schema map — used by binary transport for encoding requests. */\n'
  out += 'export const LUXO_SCHEMA: Record<string, APISchema> = {\n'
  for (const api of Object.values(schema.apis)) {
    if (api.name.startsWith('svc:')) continue
    out += `  '${api.name}': { id: ${api.id}`
    if (api.params && api.params.length > 0) {
      out += ', params: [\n'
      for (const p of api.params) {
        out += `    { fieldID: ${p.id}, name: '${p.name}', type: '${p.type}' },\n`
      }
      out += '  ]'
    }
    out += ' },\n'
  }
  out += '}\n'
  return out
}

// --- client.ts ---

function genClient(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Transport, TransportOptions, Page } from '@luxo/client'\n"
  out += "import { FetchTransport, WsTransport, Decoder } from '@luxo/client'\n"
  out += "import { LUXO_SCHEMA } from './schema'\n"

  // Collect model type imports + decoder imports
  const typeImports = new Set<string>()
  const decoderImports = new Set<string>()
  for (const api of Object.values(schema.apis)) {
    if (api.returnType && !isScalar(api.returnType)) {
      typeImports.add(api.returnType)
      decoderImports.add(`decode${api.returnType}`)
    }
  }
  if (typeImports.size > 0) {
    out += `import type { ${Array.from(typeImports).join(', ')} } from './types'\n`
    out += `import { ${Array.from(decoderImports).join(', ')} } from './types'\n`
  }

  out += '\nexport class LuxoClient {\n'
  out += '  private transport: Transport\n\n'

  // Constructor: accepts Transport directly
  out += '  constructor(transport: Transport) {\n'
  out += '    this.transport = transport\n'
  out += '    transport.setSchema(LUXO_SCHEMA)\n'
  out += '  }\n\n'

  // Factory: auto-detect transport from URL scheme
  out += '  /** Create client from URL — auto-detects HTTP vs WebSocket transport. */\n'
  out += '  static create(endpoint: string, options?: TransportOptions): LuxoClient {\n'
  out += '    const transport = endpoint.startsWith(\'ws\') ? new WsTransport(endpoint, options) : new FetchTransport(endpoint, options)\n'
  out += '    return new LuxoClient(transport)\n'
  out += '  }\n\n'

  out += '  /** Switch transport mode (json for debug, binary for production). */\n'
  out += '  setMode(mode: \'json\' | \'binary\'): void { this.transport.setMode(mode) }\n\n'
  out += '  /** Update auth token. */\n'
  out += '  setToken(token: string): void { this.transport.setToken(token) }\n\n'
  out += '  /** Close transport (WebSocket). */\n'
  out += '  close(): void { this.transport.close?.() }\n\n'
  out += '  static readonly schema = LUXO_SCHEMA\n\n'

  for (const api of Object.values(schema.apis)) {
    if (api.name.startsWith('svc:')) continue
    out += genMethod(api)
  }

  out += '}\n'
  return out
}

function genDecode(api: LuxoAPI): string {
  const t = api.returnType
  if (!t) return 'd instanceof Uint8Array ? new Decoder(d).readInt() : d as number'

  if (isScalar(t)) {
    const ts = luxoTypeToTS(t)
    const br = t === 'Float' ? 'new Decoder(d).readFloat()'
      : t === 'Boolean' ? 'new Decoder(d).readBool()'
      : (t === 'Int' || t === 'Duration') ? 'new Decoder(d).readInt()'
      : 'new Decoder(d).readString()'
    return `d instanceof Uint8Array ? ${br} : d as ${ts}`
  }

  const binDec = `decode${t}(new Decoder(d))`
  return `d instanceof Uint8Array ? ${binDec} : d as ${t}`
}

function genMethod(api: LuxoAPI): string {
  const retTS = getReturnType(api)
  const decode = genDecode(api)
  const call = (params: string) =>
    `    const d = await this.transport.call('${api.name}'${params ? `, ${params}` : ''})\n` +
    `    return ${decode}\n`

  if (api.name.startsWith('get') && !api.returnList && (!api.params || api.params.length === 0)) {
    return `  async ${api.name}(id: number, opts?: { $select?: string }): Promise<${retTS}> {\n` +
           call('{ id, ...opts }') + `  }\n\n`
  }

  if (api.name.startsWith('list')) {
    return `  async ${api.name}(params?: { page?: number; pageSize?: number; $select?: string; $filters?: unknown[]; $sorters?: unknown[] }): Promise<${retTS}> {\n` +
           call('params') + `  }\n\n`
  }

  if (api.name.startsWith('create') && api.returnType) {
    return `  async ${api.name}(input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           call('input') + `  }\n\n`
  }

  if (api.name.startsWith('update') && api.returnType) {
    return `  async ${api.name}(id: number, input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           call('{ id, ...input }') + `  }\n\n`
  }

  if (api.name.startsWith('delete')) {
    return `  async ${api.name}(id: number): Promise<number> {\n` +
           `    const d = await this.transport.call('${api.name}', { id })\n` +
           `    return d instanceof Uint8Array ? new Decoder(d).readInt() : d as number\n` +
           `  }\n\n`
  }

  if (api.params && api.params.length > 0) {
    const paramStr = api.params.map(p => `${p.name}: ${luxoTypeToTS(p.type)}`).join('; ')
    return `  async ${api.name}(params: { ${paramStr} }): Promise<${retTS}> {\n` +
           call('params') + `  }\n\n`
  }

  return `  async ${api.name}(): Promise<${retTS}> {\n` +
         call('') + `  }\n\n`
}

function getReturnType(api: LuxoAPI): string {
  if (!api.returnType) return 'number'
  const ts = luxoTypeToTS(api.returnType)
  if (api.paginated) return `Page<${ts}>`
  if (api.returnList) return `${ts}[]`
  return ts
}

function isScalar(type: string): boolean {
  return ['Int', 'Float', 'String', 'Boolean', 'DateTime', 'Duration', 'UUID', 'Bytes', 'Decimal', 'Enum'].includes(type)
}
