import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { LuxoSchema, LuxoAPI } from '@luxojs/client'

/** Generate TypeScript types + client from Luxo schema */
export async function generateTypes(schema: LuxoSchema, outDir: string): Promise<void> {
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true })
  }

  writeFileSync(join(outDir, 'types.ts'), genTypes(schema))
  writeFileSync(join(outDir, 'schema.ts'), genSchema(schema))
  writeFileSync(join(outDir, 'client.ts'), genClient(schema))
  console.log(`[luxo] Generated types → ${outDir}/`)
}

function luxoTypeToTS(type: string): string {
  switch (type) {
    case 'Int': case 'Float': case 'Duration': return 'number'
    case 'String': case 'DateTime': case 'UUID': case 'Decimal': case 'Enum': return 'string'
    case 'Boolean': return 'boolean'
    case 'Bytes': return 'string'
    default: return type // model reference
  }
}

// --- types.ts ---

/** Resolve field type to TypeScript, using typeName for model/enum references */
function resolveFieldType(field: { type: string; typeName?: string; isList?: boolean; list?: boolean }, schema: LuxoSchema): string {
  const isList = field.isList || field.list
  const typeName = field.typeName || field.type
  let ts: string

  // Check if it's an enum
  if (schema.enums?.[typeName]) {
    ts = typeName
  } else if (schema.models[typeName]) {
    ts = typeName // model reference
  } else if (schema.types?.[typeName]) {
    ts = typeName // type declaration reference
  } else {
    ts = luxoTypeToTS(field.type)
  }

  return isList ? `${ts}[]` : ts
}

function genTypes(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Page } from '@luxojs/client'\n"
  out += "import { Decoder, ColumnarDecoder } from '@luxojs/client'\n\n"

  // Enum types — union of string literals
  if (schema.enums) {
    for (const e of Object.values(schema.enums)) {
      const values = e.values.map((v: string) => `'${v}'`).join(' | ')
      out += `export type ${e.name} = ${values}\n`
      out += `export const ${e.name}Values = [${e.values.map((v: string) => `'${v}'`).join(', ')}] as const\n\n`
    }
  }

  // Type declarations (non-DB: AuthPayload, ProjectOverview, etc.)
  if (schema.types) {
    for (const t of Object.values(schema.types)) {
      out += `export interface ${t.name} {\n`
      for (const field of t.fields) {
        const ts = resolveFieldType(field, schema)
        out += field.nullable ? `  ${field.name}: ${ts} | null\n` : `  ${field.name}: ${ts}\n`
      }
      out += '}\n\n'

      // Binary decoder for type declarations (same logic as models)
      out += `export function decode${t.name}(dec: Decoder): ${t.name} {\n`
      out += `  const obj: Record<string, unknown> = {}\n`
      out += `  dec.skipArenaHeader()\n`
      out += `  while (dec.nextField()) {\n`
      out += `    switch (dec.fieldID) {\n`
      for (const field of t.fields) {
        out += `      case ${field.id}: obj['${field.name}'] = `
        out += genFieldRead(field, schema) + '; break\n'
      }
      out += `      default: break\n`
      out += `    }\n`
      out += `  }\n`
      out += `  return obj as ${t.name}\n`
      out += '}\n\n'

      // Columnar + paginated decoder for type declarations
      out += genColumnarDecode(t as unknown as LuxoModel, schema)
      out += genPaginatedDecode(t as unknown as LuxoModel)
    }
  }

  // Model interfaces
  for (const model of Object.values(schema.models)) {
    out += `export interface ${model.name} {\n`
    for (const field of model.fields) {
      const ts = resolveFieldType(field, schema)
      out += field.nullable ? `  ${field.name}: ${ts} | null\n` : `  ${field.name}: ${ts}\n`
    }
    out += '}\n\n'

    // Binary decoder function — reads from Luxo binary using field IDs
    out += `export function decode${model.name}(dec: Decoder): ${model.name} {\n`
    out += `  const obj: Record<string, unknown> = {}\n`
    out += `  dec.skipArenaHeader()\n`
    out += `  while (dec.nextField()) {\n`
    out += `    switch (dec.fieldID) {\n`
    for (const field of model.fields) {
      out += `      case ${field.id}: obj['${field.name}'] = `
      out += genFieldRead(field, schema) + '; break\n'
    }
    out += `      default: break\n`
    out += `    }\n`
    out += `  }\n`
    out += `  return obj as ${model.name}\n`
    out += '}\n\n'

    // Columnar decoder — decodes columnar binary to array
    out += genColumnarDecode(model, schema)

    // Paginated columnar decoder
    out += genPaginatedDecode(model)
  }

  out += 'export type { Page }\n'
  return out
}

/** TypeScript array type for a column variable */
function columnTSType(field: { type: string; nullable?: boolean }): string {
  const n = field.nullable
  switch (field.type) {
    case 'Int': case 'Duration': case 'Float':
      return n ? '(number | null)[]' : 'number[]'
    // DateTime is represented as an RFC3339 string in both JSON and binary modes.
    case 'String': case 'Enum': case 'UUID': case 'Decimal': case 'DateTime':
      return n ? '(string | null)[]' : 'string[]'
    case 'Boolean':
      return n ? '(boolean | null)[]' : 'boolean[]'
    default:
      return n ? '(string | null)[]' : 'string[]'
  }
}

/** Default value for missing column */
function columnDefault(field: { type: string; nullable?: boolean }): string {
  if (field.nullable) return 'null'
  switch (field.type) {
    case 'Int': case 'Duration': case 'Float': return '0'
    case 'Boolean': return 'false'
    // DateTime is a string (RFC3339) — default to empty string like other string columns.
    default: return "''"
  }
}

function genColumnRead(field: { type: string; nullable?: boolean }): string {
  const n = field.nullable
  switch (field.type) {
    case 'Int': case 'Duration':
      return n ? 'r.readColumnIntPtr()' : 'r.readColumnInt()'
    // DateTime columns are svarint(unix seconds), decoded to RFC3339 strings (matches JSON mode).
    case 'DateTime':
      return n ? 'r.readColumnDateTimePtr()' : 'r.readColumnDateTime()'
    case 'Float':
      return n ? 'r.readColumnFloatPtr()' : 'r.readColumnFloat()'
    case 'String': case 'Enum': case 'UUID': case 'Decimal':
      return n ? 'r.readColumnStringPtr()' : 'r.readColumnString()'
    case 'Boolean':
      return n ? 'r.readColumnBoolPtr()' : 'r.readColumnBool()'
    default:
      return n ? 'r.readColumnStringPtr()' : 'r.readColumnString()'
  }
}

function genColumnarDecode(model: LuxoModel, schema: LuxoSchema): string {
  const fields = model.fields.filter(f => !f.relation)
  let out = `export function decodeColumnar${model.name}(data: Uint8Array): ${model.name}[] {\n`
  out += `  const r = new ColumnarDecoder(data)\n`
  // Typed column variables — zero Record overhead, zero type assertion
  for (const f of fields) {
    out += `  let _${f.name}: ${columnTSType(f)} | undefined\n`
  }
  out += `  while (r.nextColumn()) {\n`
  out += `    switch (r.fieldID) {\n`
  for (const f of fields) {
    out += `      case ${f.id}: _${f.name} = ${genColumnRead(f)}; break\n`
  }
  out += `      default: break\n`
  out += `    }\n`
  out += `  }\n`
  out += `  const items: ${model.name}[] = new Array(r.count)\n`
  out += `  for (let i = 0; i < r.count; i++) {\n`
  out += `    items[i] = {\n`
  for (const f of fields) {
    out += `      ${f.name}: _${f.name} ? _${f.name}[i] : ${columnDefault(f)},\n`
  }
  out += `    } as ${model.name}\n`
  out += `  }\n`
  out += `  return items\n`
  out += '}\n\n'
  return out
}

function genPaginatedDecode(model: LuxoModel): string {
  const fields = model.fields.filter(f => !f.relation)
  let out = `export function decodePaginated${model.name}(data: Uint8Array): Page<${model.name}> {\n`
  out += `  const r = new ColumnarDecoder(data)\n`
  for (const f of fields) {
    out += `  let _${f.name}: ${columnTSType(f)} | undefined\n`
  }
  out += `  while (r.nextColumn()) {\n`
  out += `    switch (r.fieldID) {\n`
  for (const f of fields) {
    out += `      case ${f.id}: _${f.name} = ${genColumnRead(f)}; break\n`
  }
  out += `      default: break\n`
  out += `    }\n`
  out += `  }\n`
  out += `  const items: ${model.name}[] = new Array(r.count)\n`
  out += `  for (let i = 0; i < r.count; i++) {\n`
  out += `    items[i] = {\n`
  for (const f of fields) {
    out += `      ${f.name}: _${f.name} ? _${f.name}[i] : ${columnDefault(f)},\n`
  }
  out += `    } as ${model.name}\n`
  out += `  }\n`
  out += `  const total = r.readSvarint()\n`
  out += `  const page = r.readSvarint()\n`
  out += `  const pageSize = r.readSvarint()\n`
  out += `  return { items, total, page, pageSize }\n`
  out += '}\n\n'
  return out
}

function genFieldRead(field: { type: string; typeName?: string; nullable?: boolean; isList?: boolean; relation?: boolean }, schema: LuxoSchema): string {
  const n = field.nullable

  // Check for nested model/type reference first (relation fields or typeName pointing to a model/type)
  const tn = field.typeName || field.type
  if (field.relation || (tn && (schema.models[tn] || schema.types?.[tn]))) {
    if (field.isList) {
      return `dec.readArray(() => decode${tn}(dec))`
    }
    return n ? `dec.readNullable(() => decode${tn}(dec))` : `decode${tn}(dec)`
  }

  switch (field.type) {
    case 'Int': case 'Duration': return n ? 'dec.readIntPtr()' : 'dec.readInt()'
    case 'Float': return n ? 'dec.readFloatPtr()' : 'dec.readFloat()'
    // DateTime is svarint(unix seconds) on the wire, decoded to an RFC3339 string (matches JSON mode).
    case 'DateTime': return n ? 'dec.readDateTimePtr()' : 'dec.readDateTime()'
    case 'String': case 'UUID': case 'Decimal': case 'Enum':
      return n ? 'dec.readStringPtr()' : 'dec.readString()'
    case 'Boolean': return n ? 'dec.readBoolPtr()' : 'dec.readBool()'
    default: {
      const fallbackTn = field.typeName || field.type
      if (schema.models[fallbackTn] || schema.types?.[fallbackTn]) {
        if (field.isList) {
          return `dec.readArray(() => decode${fallbackTn}(dec))`
        }
        return n ? `dec.readNullable(() => decode${tn}(dec))` : `decode${tn}(dec)`
      }
      return 'null' // unknown type — should not happen with valid schema
    }
  }
}

// --- schema.ts ---

function genSchema(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { APISchema } from '@luxojs/client'\n\n"

  out += '/** API schema map — used by binary transport for encoding requests. */\n'
  out += 'export const LUXO_SCHEMA: Record<string, APISchema> = {\n'
  for (const api of Object.values(schema.apis)) {
    if (api.name.startsWith('svc:')) continue
    out += `  '${api.name}': { id: ${api.id}`
    if (api.params && api.params.length > 0) {
      out += ', params: [\n'
      for (const p of api.params) {
        out += `    { fieldID: ${p.id}, name: '${p.name}', type: '${p.type}' },\n`
      }
      out += '  ]'
    }
    out += ' },\n'
  }
  out += '}\n'
  return out
}

// --- client.ts ---

function genClient(schema: LuxoSchema): string {
  let out = '// Auto-generated by @luxo/vite-plugin. DO NOT EDIT.\n\n'
  out += "import type { Transport, TransportOptions, Page } from '@luxojs/client'\n"
  out += "import { FetchTransport, WsTransport, Decoder } from '@luxojs/client'\n"
  out += "import { LUXO_SCHEMA } from './schema'\n"

  // Collect model type imports + decoder imports
  const typeImports = new Set<string>()
  const decoderImports = new Set<string>()
  for (const api of Object.values(schema.apis)) {
    if (api.returnType && !isScalar(api.returnType)) {
      typeImports.add(api.returnType)
      decoderImports.add(`decode${api.returnType}`)
      if (api.paginated) {
        decoderImports.add(`decodePaginated${api.returnType}`)
      } else if (api.returnList) {
        decoderImports.add(`decodeColumnar${api.returnType}`)
      }
    }
  }
  if (typeImports.size > 0) {
    out += `import type { ${Array.from(typeImports).join(', ')} } from './types'\n`
    out += `import { ${Array.from(decoderImports).join(', ')} } from './types'\n`
  }

  out += '\nexport class LuxoClient {\n'
  out += '  private transport: Transport\n\n'

  // Constructor: accepts Transport directly
  out += '  constructor(transport: Transport) {\n'
  out += '    this.transport = transport\n'
  out += '    transport.setSchema(LUXO_SCHEMA)\n'
  out += '  }\n\n'

  // Factory: auto-detect transport from URL scheme
  out += '  /** Create client from URL — auto-detects HTTP vs WebSocket transport. */\n'
  out += '  static create(endpoint: string, options?: TransportOptions): LuxoClient {\n'
  out += '    const transport = endpoint.startsWith(\'ws\') ? new WsTransport(endpoint, options) : new FetchTransport(endpoint, options)\n'
  out += '    return new LuxoClient(transport)\n'
  out += '  }\n\n'

  out += '  /** Switch transport mode (json for debug, binary for production). */\n'
  out += '  setMode(mode: \'json\' | \'binary\'): void { this.transport.setMode(mode) }\n\n'
  out += '  /** Update auth token. */\n'
  out += '  setToken(token: string): void { this.transport.setToken(token) }\n\n'
  out += '  /** Close transport (WebSocket). */\n'
  out += '  close(): void { this.transport.close?.() }\n\n'
  out += '  static readonly schema = LUXO_SCHEMA\n\n'

  for (const api of Object.values(schema.apis)) {
    if (api.name.startsWith('svc:')) continue
    out += genMethod(api, schema)
  }

  out += '}\n'
  return out
}

function genDecode(api: LuxoAPI): string {
  const t = api.returnType
  if (!t) return 'd instanceof Uint8Array ? new Decoder(d).readInt() : d as number'

  if (isScalar(t)) {
    const ts = luxoTypeToTS(t)
    const br = t === 'Float' ? 'new Decoder(d).readFloat()'
      : t === 'Boolean' ? 'new Decoder(d).readBool()'
      : (t === 'Int' || t === 'Duration') ? 'new Decoder(d).readInt()'
      // DateTime: svarint(unix seconds) → RFC3339 string (matches JSON mode).
      : t === 'DateTime' ? 'new Decoder(d).readDateTime()'
      : 'new Decoder(d).readString()'
    return `d instanceof Uint8Array ? ${br} : d as ${ts}`
  }

  if (api.paginated) {
    return `d instanceof Uint8Array ? decodePaginated${t}(d) : d as Page<${t}>`
  }
  if (api.returnList) {
    return `d instanceof Uint8Array ? decodeColumnar${t}(d) : d as ${t}[]`
  }

  const binDec = `decode${t}(new Decoder(d))`
  return `d instanceof Uint8Array ? ${binDec} : d as ${t}`
}

function resolveParamType(p: { type: string; name: string }, schema: LuxoSchema): string {
  if (schema.enums?.[p.type]) return p.type
  if (schema.models[p.type]) return p.type
  if (schema.types?.[p.type]) return p.type
  return luxoTypeToTS(p.type)
}

function genMethod(api: LuxoAPI, schema: LuxoSchema): string {
  const retTS = getReturnType(api)
  const decode = genDecode(api)
  const call = (params: string) =>
    `    const d = await this.transport.call('${api.name}'${params ? `, ${params}` : ''})\n` +
    `    return ${decode}\n`

  // If API has explicit params, always use them for the signature (no guessing by name prefix)
  if (api.params && api.params.length > 0) {
    const isPaginated = api.name.startsWith('list') && api.paginated
    const paginationNames = new Set(['page', 'pageSize'])

    // Build typed params: page/pageSize are optional for list APIs
    const paramFields = api.params.map(p => {
      if (isPaginated && paginationNames.has(p.name)) {
        return `${p.name}?: ${resolveParamType(p, schema)}`
      }
      return `${p.name}: ${resolveParamType(p, schema)}`
    }).join('; ')

    // list APIs with page/pageSize get optional pagination extras
    if (isPaginated) {
      return `  async ${api.name}(params?: { ${paramFields}; $select?: string; $filters?: unknown[]; $sorters?: unknown[] }): Promise<${retTS}> {\n` +
             call('params') + `  }\n\n`
    }

    return `  async ${api.name}(params: { ${paramFields} }): Promise<${retTS}> {\n` +
           call('params') + `  }\n\n`
  }

  // No params — zero-arg methods
  if (api.name.startsWith('list') && api.paginated) {
    return `  async ${api.name}(params?: { page?: number; pageSize?: number; $select?: string; $filters?: unknown[]; $sorters?: unknown[] }): Promise<${retTS}> {\n` +
           call('params') + `  }\n\n`
  }

  if (api.name.startsWith('create') && api.returnType) {
    return `  async ${api.name}(input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           call('input') + `  }\n\n`
  }

  if (api.name.startsWith('update') && api.returnType) {
    return `  async ${api.name}(id: number, input: Partial<${api.returnType}>): Promise<${retTS}> {\n` +
           call('{ id, ...input }') + `  }\n\n`
  }

  // No params, no special prefix — zero-arg method
  return `  async ${api.name}(): Promise<${retTS}> {\n` +
         call('') + `  }\n\n`
}

function getReturnType(api: LuxoAPI): string {
  if (!api.returnType) return 'number'
  const ts = luxoTypeToTS(api.returnType)
  if (api.paginated) return `Page<${ts}>`
  if (api.returnList) return `${ts}[]`
  return ts
}

function isScalar(type: string): boolean {
  return ['Int', 'Float', 'String', 'Boolean', 'DateTime', 'Duration', 'UUID', 'Bytes', 'Decimal', 'Enum'].includes(type)
}
