package com.luxo.client.ksp

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.extension
import kotlin.io.path.readText

/**
 * Standalone source scanner — analyzes .kt files to find LuxoClient API calls
 * and trace field access on return values. Generates SelectHints.kt.
 *
 * This is a text-level heuristic analyzer (like @luxo/vite-plugin for TypeScript).
 * No KSP/KCP needed — runs as a Gradle task or CLI tool.
 *
 * Usage:
 *   SelectAnalyzer.analyze(
 *     sourceDir = "src/main/kotlin",
 *     outFile = "src/main/kotlin/com/example/luxo/SelectHints.kt",
 *     packageName = "com.example.luxo",
 *   )
 *
 * Pattern detection:
 *   val user = client.getUser(1)     → tracks var "user" from API "getUser"
 *   val (name, email) = ...          → destructuring (not tracked)
 *   println(user.name)               → records "name" for "getUser"
 *   user.email                       → records "email" for "getUser"
 */
object SelectAnalyzer {

    // Matches: val/var <name> = <expr>.someApiMethod(...)
    // Captures: group(1) = variable name, group(2) = method name
    private val callPattern = Regex(
        """(?:val|var)\s+(\w+)\s*=\s*(?:.*?)\.(\w+)\s*\("""
    )

    // Matches: <variable>.<property> (property access)
    // Captures: group(1) = variable name, group(2) = property name
    private val accessPattern = Regex(
        """(\w+)\.(\w+)"""
    )

    // Known API method prefixes (from CRUD patterns)
    private val apiPrefixes = setOf("get", "list", "create", "update", "delete", "find")

    fun analyze(sourceDir: String, outFile: String, packageName: String) {
        val hints = mutableMapOf<String, MutableSet<String>>()
        val sourceRoot = Path.of(sourceDir)

        // Scan all .kt files
        Files.walk(sourceRoot)
            .filter { it.extension == "kt" }
            .filter { !it.toString().contains("SelectHints") } // skip generated
            .forEach { path ->
                analyzeFile(path.readText(), hints)
            }

        // Generate output
        File(outFile).parentFile?.mkdirs()
        File(outFile).writeText(generateHints(hints, packageName))
        println("[luxo] Generated select hints -> $outFile")
    }

    internal fun analyzeFile(source: String, hints: MutableMap<String, MutableSet<String>>) {
        // Phase 1: find variable → API method mappings
        val varToApi = mutableMapOf<String, String>()

        for (match in callPattern.findAll(source)) {
            val varName = match.groupValues[1]
            val methodName = match.groupValues[2]

            // Only track if method name looks like a Luxo API call
            if (apiPrefixes.any { methodName.startsWith(it) } || methodName.length > 3) {
                varToApi[varName] = methodName
                hints.putIfAbsent(methodName, mutableSetOf())
            }
        }

        // Phase 2: find property accesses on tracked variables
        for (match in accessPattern.findAll(source)) {
            val varName = match.groupValues[1]
            val propName = match.groupValues[2]

            val apiName = varToApi[varName] ?: continue

            // Skip common non-field accesses
            if (propName in setOf("toString", "hashCode", "let", "also", "apply", "run", "takeIf")) continue

            hints[apiName]?.add(propName)
        }
    }

    private fun generateHints(hints: Map<String, Set<String>>, packageName: String): String = buildString {
        appendLine("// GENERATED BY luxo_client. DO NOT EDIT.")
        appendLine("// Rebuild with: ./gradlew luxoAnalyze\n")
        appendLine("package $packageName\n")
        appendLine("/** Field access hints — auto-detected from your code. */")
        appendLine("object SelectHints {")
        appendLine("    val hints: Map<String, String> = mapOf(")
        for ((api, fields) in hints) {
            if (fields.isEmpty()) continue
            val sorted = fields.sorted().joinToString(",")
            appendLine("        \"$api\" to \"$sorted\",")
        }
        appendLine("    )")
        appendLine("}")
    }
}
