package com.luxo.client.ksp

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.extension
import kotlin.io.path.readText

/**
 * Source scanner — analyzes .kt files to find LuxoClient API calls
 * and trace nested field access on return values.
 *
 * Supports nested field tracking:
 *   post.user.name          → "user{name}"
 *   post.comments[0].content → "comments{content}"
 *   post.comments[0].user.id → "comments{user{id}}"
 *
 * Usage:
 *   SelectAnalyzer.analyze(
 *     sourceDir = "src/main/kotlin",
 *     outFile = "src/main/kotlin/com/example/luxo/SelectHints.kt",
 *     packageName = "com.example.luxo",
 *     modelFields = mapOf("Post" to mapOf("title" to "String", "user" to "User"), ...)
 *   )
 */
object SelectAnalyzer {

    // Matches: val/var <name> = <expr>.someApiMethod(...)
    private val callPattern = Regex(
        """(?:val|var)\s+(\w+)\s*=\s*(?:.*?)\.(\w+)\s*\("""
    )

    private val apiPrefixes = setOf("get", "list", "create", "update", "delete", "find")

    fun analyze(
        sourceDir: String,
        outFile: String,
        packageName: String,
        modelFields: Map<String, Map<String, String>> = emptyMap(),
    ) {
        val hints = mutableMapOf<String, FieldNode>()
        val sourceRoot = Path.of(sourceDir)

        Files.walk(sourceRoot)
            .filter { it.extension == "kt" }
            .filter { !it.toString().contains("SelectHints") }
            .forEach { path ->
                analyzeFile(path.readText(), hints, modelFields)
            }

        File(outFile).parentFile?.mkdirs()
        File(outFile).writeText(generateHints(hints, packageName))
        println("[luxo] Generated select hints -> $outFile")
    }

    internal fun analyzeFile(
        source: String,
        hints: MutableMap<String, FieldNode>,
        modelFields: Map<String, Map<String, String>> = emptyMap(),
    ) {
        // Phase 1: find variable → API method + type mappings
        val varToApi = mutableMapOf<String, String>()
        val varToType = mutableMapOf<String, String>()

        for (match in callPattern.findAll(source)) {
            val varName = match.groupValues[1]
            val methodName = match.groupValues[2]

            if (apiPrefixes.any { methodName.startsWith(it) } || methodName.length > 3) {
                varToApi[varName] = methodName
                hints.putIfAbsent(methodName, FieldNode.root())

                // Infer type from method name: getUser → User, listPosts → Post
                val typeName = inferTypeFromMethod(methodName)
                if (typeName != null) {
                    varToType[varName] = typeName
                }
            }
        }

        // Phase 2: find nested property access chains
        // Match: varName.field1.field2, varName.field1[0].field2, varName?.field1
        for ((varName, apiName) in varToApi) {
            val chainRegex = Regex("""\b${Regex.escape(varName)}((?:\??\.\w+|\[\w+])+)""")
            for (match in chainRegex.findAll(source)) {
                val chainStr = match.groupValues[1]
                val segments = chainStr.split(Regex("""[.?\[\]]+"""))
                    .filter { it.isNotEmpty() && !it.all { c -> c.isDigit() } }

                if (segments.isEmpty()) continue

                val root = hints[apiName] ?: continue
                var currentType = varToType[varName]
                var currentNode = root

                for (seg in segments) {
                    // Skip non-field accesses
                    if (seg in setOf("toString", "hashCode", "let", "also", "apply", "run", "takeIf")) break

                    // Validate against model fields if available
                    if (currentType != null && modelFields.containsKey(currentType)) {
                        val fields = modelFields[currentType]!!
                        if (!fields.containsKey(seg)) break

                        currentNode = currentNode.addChild(seg)
                        currentType = fields[seg]
                    } else {
                        currentNode = currentNode.addChild(seg)
                        currentType = null
                    }
                }
            }
        }
    }

    private fun inferTypeFromMethod(method: String): String? {
        for (prefix in apiPrefixes) {
            if (method.startsWith(prefix) && method.length > prefix.length) {
                var typeName = method.removePrefix(prefix)
                // listPosts → Post (remove trailing 's' for list)
                if (prefix == "list" && typeName.endsWith("s")) {
                    typeName = typeName.dropLast(1)
                }
                return typeName
            }
        }
        return null
    }

    private fun generateHints(hints: Map<String, FieldNode>, packageName: String): String = buildString {
        appendLine("// GENERATED BY luxo_client. DO NOT EDIT.")
        appendLine("// Rebuild with: ./gradlew luxoAnalyze\n")
        appendLine("package $packageName\n")
        appendLine("/** Nested field access hints — auto-detected from your code. */")
        appendLine("object SelectHints {")
        appendLine("    val hints: Map<String, String> = mapOf(")
        for ((api, node) in hints) {
            val selectStr = node.toSelectString()
            if (selectStr.isEmpty()) continue
            appendLine("        \"$api\" to \"$selectStr\",")
        }
        appendLine("    )")
        appendLine("}")
    }
}

/** Tree node for nested field selection. */
class FieldNode private constructor(val name: String) {
    val children = mutableMapOf<String, FieldNode>()

    companion object {
        fun root() = FieldNode("")
    }

    fun addChild(fieldName: String): FieldNode {
        return children.getOrPut(fieldName) { FieldNode(fieldName) }
    }

    fun toSelectString(): String {
        if (children.isEmpty()) return ""
        return children.values.joinToString(",") { child ->
            val nested = child.toSelectString()
            if (nested.isNotEmpty()) "${child.name}{$nested}" else child.name
        }
    }
}
