import 'dart:convert';
import 'dart:io';
import 'types.dart';

/// Generate typed client from Luxo schema introspection.
///
/// Usage:
///   dart run luxo_client:generate --endpoint http://localhost:4000/luvia --key YOUR_KEY --out lib/src/luxo/
Future<void> generate({
  required String endpoint,
  required String key,
  String outDir = 'lib/src/luxo',
}) async {
  final client = HttpClient();
  try {
    final uri = Uri.parse('$endpoint?\$schema&key=$key');
    final request = await client.getUrl(uri);
    final response = await request.close();
    if (response.statusCode != 200) {
      throw Exception('introspection failed: HTTP ${response.statusCode}');
    }
    final body = await response.transform(utf8.decoder).join();

    final Map<String, dynamic> json;
    try {
      json = jsonDecode(body) as Map<String, dynamic>;
    } catch (e) {
      throw Exception('introspection returned invalid JSON: $e');
    }

    final schema = LuxoSchema.fromJson(json);

  final dir = Directory(outDir);
  if (!dir.existsSync()) dir.createSync(recursive: true);

    File('$outDir/types.dart').writeAsStringSync(_genTypes(schema));
    File('$outDir/schema.dart').writeAsStringSync(_genSchemaMap(schema));
    File('$outDir/client.dart').writeAsStringSync(_genClient(schema));
    print('[luxo] Generated types -> $outDir/');
  } finally {
    client.close();
  }
}

String _luxoTypeToDart(String type) {
  switch (type) {
    case 'Int':
    case 'Duration':
      return 'int';
    case 'Float':
      return 'double';
    case 'String':
    case 'DateTime':
    case 'UUID':
    case 'Decimal':
    case 'Enum':
      return 'String';
    case 'Boolean':
      return 'bool';
    case 'Bytes':
      return 'String';
    default:
      return type; // model reference
  }
}

bool _isScalar(String type) =>
    const {'Int', 'Float', 'String', 'Boolean', 'DateTime', 'Duration', 'UUID', 'Bytes', 'Decimal'}.contains(type);

String _genTypes(LuxoSchema schema) {
  final b = StringBuffer();
  b.writeln('// Auto-generated by luxo_client. DO NOT EDIT.\n');
  b.writeln("import 'package:luxo_client/luxo_client.dart';\n");

  for (final m in schema.models.values) {
    b.writeln('class ${m.name} {');
    for (final f in m.fields) {
      final t = _luxoTypeToDart(f.type);
      b.writeln('  final ${f.nullable ? '$t?' : t} ${f.name};');
    }
    b.writeln();
    b.writeln('  const ${m.name}({');
    for (final f in m.fields) {
      b.writeln(f.nullable ? '    this.${f.name},' : '    required this.${f.name},');
    }
    b.writeln('  });\n');
    b.writeln('  factory ${m.name}.fromJson(Map<String, dynamic> json) => ${m.name}(');
    for (final f in m.fields) {
      b.writeln('    ${f.name}: ${_jsonCast(f)},');
    }
    b.writeln('  );');
    b.writeln('}\n');
  }

  // Binary decoder functions — read from Luxo binary using field IDs
  for (final m in schema.models.values) {
    b.writeln('${m.name} decode${m.name}(LuxoDecoder dec) {');
    // Declare nullable locals for all fields
    for (final f in m.fields) {
      final t = _luxoTypeToDart(f.type);
      b.writeln('  ${f.nullable ? '$t?' : '$t?'} _${f.name};');
    }
    b.writeln('  while (dec.nextField()) {');
    b.writeln('    switch (dec.fieldID) {');
    for (final f in m.fields) {
      b.writeln('      case ${f.id}: _${f.name} = ${_binaryRead(f)}; break;');
    }
    b.writeln('    }');
    b.writeln('  }');
    b.writeln('  return ${m.name}(');
    for (final f in m.fields) {
      if (f.nullable) {
        b.writeln('    ${f.name}: _${f.name},');
      } else {
        b.writeln('    ${f.name}: _${f.name}!,');
      }
    }
    b.writeln('  );');
    b.writeln('}\n');
  }

  b.writeln("export 'package:luxo_client/src/types.dart' show Page;");
  return b.toString();
}

String _jsonCast(LuxoField f) {
  final n = f.name;
  final q = f.nullable;
  switch (f.type) {
    case 'Int':
    case 'Duration':
      return q ? "json['$n'] as int?" : "json['$n'] as int";
    case 'Float':
      return q ? "(json['$n'] as num?)?.toDouble()" : "(json['$n'] as num).toDouble()";
    case 'Boolean':
      return q ? "json['$n'] as bool?" : "json['$n'] as bool";
    case 'String':
    case 'DateTime':
    case 'UUID':
    case 'Decimal':
    case 'Enum':
      return q ? "json['$n'] as String?" : "json['$n'] as String";
    default:
      if (q) return "json['$n'] != null ? ${f.type}.fromJson(json['$n'] as Map<String, dynamic>) : null";
      return "${f.type}.fromJson(json['$n'] as Map<String, dynamic>)";
  }
}

String _binaryRead(LuxoField f) {
  final n = f.nullable;
  switch (f.type) {
    case 'Int': case 'Duration': return n ? 'dec.readIntPtr()' : 'dec.readInt()';
    case 'Float': return n ? 'dec.readFloatPtr()' : 'dec.readFloat()';
    case 'Boolean': return n ? 'dec.readBoolPtr()' : 'dec.readBool()';
    case 'String': case 'DateTime': case 'UUID': case 'Decimal': case 'Enum':
      return n ? 'dec.readStringPtr()' : 'dec.readString()';
    default: return 'null'; // nested model TODO
  }
}

String _genSchemaMap(LuxoSchema schema) {
  final b = StringBuffer();
  b.writeln('// Auto-generated by luxo_client. DO NOT EDIT.\n');
  b.writeln("import 'package:luxo_client/luxo_client.dart';\n");
  b.writeln('/// API schema map — used by binary transport for encoding requests.');
  b.writeln('final luxoSchema = <String, APISchemaEntry>{');
  for (final api in schema.apis.values) {
    if (api.name.startsWith('svc:')) continue;
    b.write("  '${api.name}': APISchemaEntry(${api.id}");
    if (api.params.isNotEmpty) {
      b.write(', [\n');
      for (final p in api.params) {
        b.writeln("    ParamSchema(${p.id}, '${p.name}', '${p.type}'),");
      }
      b.write('  ]');
    }
    b.writeln('),');
  }
  b.writeln('};');
  return b.toString();
}

String _genClient(LuxoSchema schema) {
  final b = StringBuffer();
  b.writeln('// Auto-generated by luxo_client. DO NOT EDIT.\n');
  b.writeln("import 'package:luxo_client/luxo_client.dart';");
  b.writeln("import 'types.dart';");
  b.writeln("import 'schema.dart';");
  b.writeln("import '_select_hints.g.dart' as hints show selectHints;\n");
  b.writeln('class LuxoClient {');
  b.writeln('  final Transport transport;');
  b.writeln('  static final schema = luxoSchema;');
  b.writeln('  LuxoClient(this.transport);\n');
  b.writeln('  /// Get auto-detected \$select for an API (from build_runner analysis).');
  b.writeln("  String? _hint(String api) => hints.selectHints[api];\n");

  for (final api in schema.apis.values) {
    if (api.name.startsWith('svc:')) continue;
    _genMethod(b, api);
  }

  b.writeln('}');
  return b.toString();
}

void _genMethod(StringBuffer b, LuxoAPI api) {
  final ret = _returnType(api);
  final dec = _decoder(api);

  if (api.name.startsWith('get') && !api.returnList && api.params.isEmpty) {
    b.writeln("  Future<$ret> ${api.name}(int id, {String? select}) async {");
    b.writeln("    final sel = select ?? _hint('${api.name}');");
    b.writeln("    return transport.call('${api.name}', params: {'id': id, if (sel != null) r'\$select': sel}, decoder: $dec);");
    b.writeln('  }\n');
    return;
  }
  if (api.name.startsWith('list')) {
    b.writeln("  Future<$ret> ${api.name}({int? page, int? pageSize, String? select}) async {");
    b.writeln("    final sel = select ?? _hint('${api.name}');");
    b.writeln("    return transport.call('${api.name}', params: {");
    b.writeln("      if (page != null) 'page': page,");
    b.writeln("      if (pageSize != null) 'pageSize': pageSize,");
    b.writeln("      if (sel != null) r'\$select': sel,");
    b.writeln('    }, decoder: $dec);');
    b.writeln('  }\n');
    return;
  }
  if (api.name.startsWith('create') && api.returnType != null) {
    b.writeln("  Future<$ret> ${api.name}(Map<String, dynamic> input) async {");
    b.writeln("    return transport.call('${api.name}', params: input, decoder: $dec);");
    b.writeln('  }\n');
    return;
  }
  if (api.name.startsWith('update') && api.returnType != null) {
    b.writeln("  Future<$ret> ${api.name}(int id, Map<String, dynamic> input) async {");
    b.writeln("    return transport.call('${api.name}', params: {'id': id, ...input}, decoder: $dec);");
    b.writeln('  }\n');
    return;
  }
  if (api.name.startsWith('delete')) {
    b.writeln("  Future<int> ${api.name}(int id) async {");
    b.writeln("    return transport.call('${api.name}', params: {'id': id}, decoder: (d) => d as int);");
    b.writeln('  }\n');
    return;
  }
  if (api.params.isNotEmpty) {
    final params = api.params.map((p) => '${_luxoTypeToDart(p.type)} ${p.name}').join(', ');
    b.writeln("  Future<$ret> ${api.name}({$params}) async {");
    b.writeln("    return transport.call('${api.name}', params: {");
    for (final p in api.params) {
      b.writeln("      '${p.name}': ${p.name},");
    }
    b.writeln('    }, decoder: $dec);');
    b.writeln('  }\n');
    return;
  }
  b.writeln("  Future<$ret> ${api.name}() async {");
  b.writeln("    return transport.call('${api.name}', decoder: $dec);");
  b.writeln('  }\n');
}

String _returnType(LuxoAPI api) {
  if (api.returnType == null) return 'int';
  final t = _luxoTypeToDart(api.returnType!);
  if (api.paginated) return 'Page<$t>';
  if (api.returnList) return 'List<$t>';
  return t;
}

/// Generates a decoder lambda that handles both JSON (Map/int/etc) and binary (Uint8List).
String _decoder(LuxoAPI api) {
  if (api.returnType == null) {
    return '(d) => d is Uint8List ? (LuxoDecoder(d)..nextField()).readInt() : d as int';
  }
  final t = api.returnType!;
  if (_isScalar(t)) {
    final dartType = _luxoTypeToDart(t);
    final binaryRead = switch (t) {
      'Float' => '(LuxoDecoder(d)..nextField()).readFloat()',
      'Boolean' => '(LuxoDecoder(d)..nextField()).readBool()',
      'Int' || 'Duration' => '(LuxoDecoder(d)..nextField()).readInt()',
      _ => '(LuxoDecoder(d)..nextField()).readString()',
    };
    final jsonRead = t == 'Float' ? '(d as num).toDouble()' : 'd as $dartType';
    return '(d) => d is Uint8List ? $binaryRead : $jsonRead';
  }
  // Model type — binary uses decode{Model}, JSON uses fromJson
  final binaryDecode = 'decode$t(LuxoDecoder(d))';
  if (api.paginated) {
    return "(d) => d is Uint8List ? $binaryDecode : Page.fromJson(d as Map<String, dynamic>, (e) => $t.fromJson(e))";
  }
  if (api.returnList) {
    return "(d) => d is Uint8List ? $binaryDecode : (d as List).map((e) => $t.fromJson(e as Map<String, dynamic>)).toList()";
  }
  return "(d) => d is Uint8List ? $binaryDecode : $t.fromJson(d as Map<String, dynamic>)";
}
