package com.luxo.client

import kotlinx.serialization.json.*
import java.io.File
import java.net.URI

/**
 * Generate typed Kotlin client from Luxo schema introspection.
 *
 * Usage:
 *   LuxoCodegen.generate(
 *     endpoint = "http://localhost:4000/luvia",
 *     key = "YOUR_KEY",
 *     outDir = "src/main/kotlin/com/example/luxo",
 *     packageName = "com.example.luxo",
 *   )
 */
object LuxoCodegen {

    fun generate(endpoint: String, key: String, outDir: String, packageName: String = "com.luxo.generated") {
        val url = URI("$endpoint?\$schema&key=$key").toURL()
        val body = try {
            url.readText()
        } catch (e: Exception) {
            throw RuntimeException("luxo introspection failed: ${e.message}", e)
        }
        val schema = try {
            Json.decodeFromString<LuxoSchema>(body)
        } catch (e: Exception) {
            throw RuntimeException("luxo introspection returned invalid JSON: ${e.message}", e)
        }

        File(outDir).mkdirs()
        File("$outDir/Types.kt").writeText(genTypes(schema, packageName))
        File("$outDir/Schema.kt").writeText(genSchemaMap(schema, packageName))
        File("$outDir/LuxoClient.kt").writeText(genClient(schema, packageName))
        println("[luxo] Generated types -> $outDir/")
    }

    private fun luxoTypeToKt(type: String): String = when (type) {
        "Int", "Duration" -> "Int"
        "Float" -> "Double"
        "String", "DateTime", "UUID", "Decimal", "Enum" -> "String"
        "Boolean" -> "Boolean"
        "Bytes" -> "String"
        else -> type
    }

    private fun isScalar(type: String): Boolean =
        type in setOf("Int", "Float", "String", "Boolean", "DateTime", "Duration", "UUID", "Bytes", "Decimal")

    private fun binaryRead(f: LuxoField): String {
        val n = f.nullable
        return when (f.type) {
            "Int", "Duration" -> if (n) "dec.readIntPtr()" else "dec.readInt()"
            "Float" -> if (n) "dec.readFloatPtr()" else "dec.readFloat()"
            "Boolean" -> if (n) "dec.readBoolPtr()" else "dec.readBool()"
            "String", "DateTime", "UUID", "Decimal", "Enum" -> if (n) "dec.readStringPtr()" else "dec.readString()"
            else -> "null"
        }
    }

    private fun genTypes(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.LuxoDecoder")
        appendLine("import kotlinx.serialization.Serializable\n")

        for (m in schema.models.values) {
            appendLine("@Serializable\ndata class ${m.name}(")
            for ((i, f) in m.fields.withIndex()) {
                val kt = luxoTypeToKt(f.type)
                val nullable = if (f.nullable) "? = null" else ""
                val comma = if (i < m.fields.size - 1) "," else ""
                appendLine("    val ${f.name}: $kt$nullable$comma")
            }
            appendLine(")\n")

            // Binary decoder function
            appendLine("fun decode${m.name}(dec: LuxoDecoder): ${m.name} {")
            for (f in m.fields) {
                val kt = luxoTypeToKt(f.type)
                appendLine("    var _${f.name}: $kt? = null")
            }
            appendLine("    while (dec.nextField()) {")
            appendLine("        when (dec.fieldID) {")
            for (f in m.fields) {
                appendLine("            ${f.id} -> _${f.name} = ${binaryRead(f)}")
            }
            appendLine("        }")
            appendLine("    }")
            appendLine("    return ${m.name}(")
            for (f in m.fields) {
                appendLine("        ${f.name} = _${f.name}${if (f.nullable) "" else "!!"},")
            }
            appendLine("    )")
            appendLine("}\n")
        }
    }

    private fun genSchemaMap(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.APISchemaEntry")
        appendLine("import com.luxo.client.ParamSchema\n")
        appendLine("/** API schema map — used by binary transport for encoding requests. */")
        appendLine("val LUXO_SCHEMA: Map<String, APISchemaEntry> = mapOf(")
        for (api in schema.apis.values) {
            if (api.name.startsWith("svc:")) continue
            append("    \"${api.name}\" to APISchemaEntry(${api.id}")
            if (api.params.isNotEmpty()) {
                appendLine(", listOf(")
                for (p in api.params) {
                    appendLine("        ParamSchema(${p.id}, \"${p.name}\", \"${p.type}\"),")
                }
                append("    )")
            }
            appendLine("),")
        }
        appendLine(")")
    }

    private fun genClient(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.*")
        appendLine("import kotlinx.serialization.json.*\n")
        appendLine("class LuxoClient(private val transport: Transport) {\n")

        for (api in schema.apis.values) {
            if (api.name.startsWith("svc:")) continue
            genMethod(this, api)
        }

        appendLine("}")
    }

    private fun genMethod(b: StringBuilder, api: LuxoAPI) {
        val ret = returnType(api)
        val dec = decode(api)

        when {
            api.name.startsWith("get") && !api.returnList && api.params.isEmpty() -> {
                b.appendLine("    suspend fun ${api.name}(id: Int, select: String? = null): $ret {")
                b.appendLine("        val params = buildMap<String, JsonElement> {")
                b.appendLine("            put(\"id\", JsonPrimitive(id))")
                b.appendLine("            if (select != null) put(\"\\\$select\", JsonPrimitive(select))")
                b.appendLine("        }")
                b.appendLine("        val data = transport.call(\"${api.name}\", params)")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
            api.name.startsWith("list") -> {
                b.appendLine("    suspend fun ${api.name}(page: Int? = null, pageSize: Int? = null, select: String? = null): $ret {")
                b.appendLine("        val params = buildMap<String, JsonElement> {")
                b.appendLine("            if (page != null) put(\"page\", JsonPrimitive(page))")
                b.appendLine("            if (pageSize != null) put(\"pageSize\", JsonPrimitive(pageSize))")
                b.appendLine("            if (select != null) put(\"\\\$select\", JsonPrimitive(select))")
                b.appendLine("        }")
                b.appendLine("        val data = transport.call(\"${api.name}\", params)")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
            api.name.startsWith("create") && api.returnType != null -> {
                b.appendLine("    suspend fun ${api.name}(input: Map<String, JsonElement>): $ret {")
                b.appendLine("        val data = transport.call(\"${api.name}\", input)")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
            api.name.startsWith("update") && api.returnType != null -> {
                b.appendLine("    suspend fun ${api.name}(id: Int, input: Map<String, JsonElement>): $ret {")
                b.appendLine("        val params = buildMap<String, JsonElement> { put(\"id\", JsonPrimitive(id)); putAll(input) }")
                b.appendLine("        val data = transport.call(\"${api.name}\", params)")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
            api.name.startsWith("delete") -> {
                b.appendLine("    suspend fun ${api.name}(id: Int): Int {")
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf(\"id\" to JsonPrimitive(id)))")
                b.appendLine("        return data.jsonPrimitive.int")
                b.appendLine("    }\n")
            }
            api.params.isNotEmpty() -> {
                val ps = api.params.joinToString(", ") { "${it.name}: ${luxoTypeToKt(it.type)}" }
                b.appendLine("    suspend fun ${api.name}($ps): $ret {")
                b.appendLine("        val params = buildMap<String, JsonElement> {")
                for (p in api.params) {
                    b.appendLine("            put(\"${p.name}\", JsonPrimitive(${p.name}))")
                }
                b.appendLine("        }")
                b.appendLine("        val data = transport.call(\"${api.name}\", params)")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
            else -> {
                b.appendLine("    suspend fun ${api.name}(): $ret {")
                b.appendLine("        val data = transport.call(\"${api.name}\")")
                b.appendLine("        return $dec")
                b.appendLine("    }\n")
            }
        }
    }

    private fun returnType(api: LuxoAPI): String {
        if (api.returnType == null) return "Int"
        val t = luxoTypeToKt(api.returnType!!)
        return when {
            api.paginated -> "Page<$t>"
            api.returnList -> "List<$t>"
            else -> t
        }
    }

    private fun decode(api: LuxoAPI): String {
        if (api.returnType == null) return "data.jsonPrimitive.int"
        val t = api.returnType!!
        if (isScalar(t)) return when (t) {
            "Int", "Duration" -> "data.jsonPrimitive.int"
            "Float" -> "data.jsonPrimitive.double"
            "Boolean" -> "data.jsonPrimitive.boolean"
            else -> "data.jsonPrimitive.content"
        }
        return when {
            api.paginated -> "Json.decodeFromJsonElement<Page<$t>>(data)"
            api.returnList -> "Json.decodeFromJsonElement<List<$t>>(data)"
            else -> "Json.decodeFromJsonElement<$t>(data)"
        }
    }
}
