package com.luxo.client

import kotlinx.serialization.json.*
import java.io.File
import java.net.URI

/**
 * Generate typed Kotlin client from Luxo schema introspection.
 *
 * Usage:
 *   LuxoCodegen.generate(
 *     endpoint = "http://localhost:4000/luvia",
 *     key = "YOUR_KEY",
 *     outDir = "src/main/kotlin/com/example/luxo",
 *     packageName = "com.example.luxo",
 *   )
 */
object LuxoCodegen {

    fun generate(endpoint: String, key: String, outDir: String, packageName: String = "com.luxo.generated") {
        val url = URI("$endpoint?\$schema&key=$key").toURL()
        val body = try {
            url.readText()
        } catch (e: Exception) {
            throw RuntimeException("luxo introspection failed: ${e.message}", e)
        }
        val schema = try {
            Json.decodeFromString<LuxoSchema>(body)
        } catch (e: Exception) {
            throw RuntimeException("luxo introspection returned invalid JSON: ${e.message}", e)
        }

        File(outDir).mkdirs()
        File("$outDir/Types.kt").writeText(genTypes(schema, packageName))
        File("$outDir/Schema.kt").writeText(genSchemaMap(schema, packageName))
        File("$outDir/LuxoClient.kt").writeText(genClient(schema, packageName))
        println("[luxo] Generated types -> $outDir/")
    }

    private fun luxoTypeToKt(type: String): String = when (type) {
        "Int", "Duration" -> "Int"
        "Float" -> "Double"
        "String", "DateTime", "UUID", "Decimal", "Enum" -> "String"
        "Boolean" -> "Boolean"
        "Bytes" -> "String"
        else -> type
    }

    private fun resolveFieldType(f: LuxoField, schema: LuxoSchema): String {
        val tn = f.typeName ?: f.type
        if (schema.enums.containsKey(tn)) return if (f.isList) "List<$tn>" else tn
        if (schema.models.containsKey(tn)) return if (f.isList) "List<$tn>" else tn
        if (schema.types.containsKey(tn)) return if (f.isList) "List<$tn>" else tn
        val base = luxoTypeToKt(f.type)
        return if (f.isList) "List<$base>" else base
    }

    private fun isScalar(type: String): Boolean =
        type in setOf("Int", "Float", "String", "Boolean", "DateTime", "Duration", "UUID", "Bytes", "Decimal")

    private fun binaryRead(f: LuxoField): String {
        val n = f.nullable
        return when (f.type) {
            "Int", "Duration" -> if (n) "dec.readIntPtr()" else "dec.readInt()"
            "Float" -> if (n) "dec.readFloatPtr()" else "dec.readFloat()"
            "Boolean" -> if (n) "dec.readBoolPtr()" else "dec.readBool()"
            "String", "DateTime", "UUID", "Decimal", "Enum" -> if (n) "dec.readStringPtr()" else "dec.readString()"
            else -> {
                // Nested model — decode recursively
                val tn = f.typeName ?: f.type
                if (f.isList) "dec.readArray { decode$tn(dec) }"
                else if (n) "dec.readNullable { decode$tn(dec) }"
                else "decode$tn(dec)"
            }
        }
    }

    private fun genTypes(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.LuxoDecoder")
        appendLine("import kotlinx.serialization.Serializable\n")

        // Enums
        for (e in schema.enums.values) {
            appendLine("/** ${e.name} enum values */")
            appendLine("typealias ${e.name} = String")
            appendLine("object ${e.name}Values {")
            for (v in e.values) {
                appendLine("    const val $v: ${e.name} = \"$v\"")
            }
            appendLine("    val all = listOf(${e.values.joinToString(", ") { "\"$it\"" }})")
            appendLine("}\n")
        }

        // Type declarations (non-DB)
        for (t in schema.types.values) {
            appendLine("@Serializable\ndata class ${t.name}(")
            for ((i, f) in t.fields.withIndex()) {
                val kt = resolveFieldType(f, schema)
                val nullable = if (f.nullable) "? = null" else ""
                val comma = if (i < t.fields.size - 1) "," else ""
                appendLine("    val ${f.name}: $kt$nullable$comma")
            }
            appendLine(")\n")
        }

        // Models
        for (m in schema.models.values) {
            appendLine("@Serializable\ndata class ${m.name}(")
            for ((i, f) in m.fields.withIndex()) {
                val kt = luxoTypeToKt(f.type)
                val nullable = if (f.nullable) "? = null" else ""
                val comma = if (i < m.fields.size - 1) "," else ""
                appendLine("    val ${f.name}: $kt$nullable$comma")
            }
            appendLine(")\n")

            // Binary decoder function
            appendLine("fun decode${m.name}(dec: LuxoDecoder): ${m.name} {")
            for (f in m.fields) {
                val kt = luxoTypeToKt(f.type)
                appendLine("    var _${f.name}: $kt? = null")
            }
            appendLine("    while (dec.nextField()) {")
            appendLine("        when (dec.fieldID) {")
            for (f in m.fields) {
                appendLine("            ${f.id} -> _${f.name} = ${binaryRead(f)}")
            }
            appendLine("        }")
            appendLine("    }")
            appendLine("    return ${m.name}(")
            for (f in m.fields) {
                appendLine("        ${f.name} = _${f.name}${if (f.nullable) "" else "!!"},")
            }
            appendLine("    )")
            appendLine("}\n")
        }
    }

    private fun genSchemaMap(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.APISchemaEntry")
        appendLine("import com.luxo.client.ParamSchema\n")
        appendLine("/** API schema map — used by binary transport for encoding requests. */")
        appendLine("val LUXO_SCHEMA: Map<String, APISchemaEntry> = mapOf(")
        for (api in schema.apis.values) {
            if (api.name.startsWith("svc:")) continue
            append("    \"${api.name}\" to APISchemaEntry(${api.id}")
            if (api.params.isNotEmpty()) {
                appendLine(", listOf(")
                for (p in api.params) {
                    appendLine("        ParamSchema(${p.id}, \"${p.name}\", \"${p.type}\"),")
                }
                append("    )")
            }
            appendLine("),")
        }
        appendLine(")")
    }

    private fun genClient(schema: LuxoSchema, pkg: String): String = buildString {
        appendLine("// Auto-generated by luxo. DO NOT EDIT.\n")
        appendLine("package $pkg\n")
        appendLine("import com.luxo.client.*")
        appendLine("import kotlinx.serialization.json.*\n")
        appendLine("class LuxoClient(val transport: Transport) {\n")
        appendLine("    init { transport.setSchema(LUXO_SCHEMA) }\n")
        appendLine("    companion object {")
        appendLine("        val schema = LUXO_SCHEMA")
        appendLine("        /** Create client from URL — auto-selects HTTP transport. */")
        appendLine("        fun create(endpoint: String, mode: TransportMode = TransportMode.JSON, token: String? = null): LuxoClient {")
        appendLine("            val transport = OkHttpTransport(endpoint, token = token, mode = mode, schema = LUXO_SCHEMA)")
        appendLine("            return LuxoClient(transport)")
        appendLine("        }")
        appendLine("    }\n")
        appendLine("    fun setMode(mode: TransportMode) = transport.setMode(mode)")
        appendLine("    fun setToken(token: String) = transport.setToken(token)")
        appendLine("    private fun hint(api: String): String? = try { SelectHints.hints[api] } catch (_: Exception) { null }\n")

        for (api in schema.apis.values) {
            if (api.name.startsWith("svc:")) continue
            genMethod(this, api)
        }

        appendLine("}")
    }

    private fun genMethod(b: StringBuilder, api: LuxoAPI) {
        val ret = returnType(api)

        // All methods: call transport, then decode based on response type (JSON or binary)
        fun emitDecode() {
            b.appendLine("        return decode_${api.name}(data)")
        }

        when {
            api.name.startsWith("get") && !api.returnList && api.params.isEmpty() -> {
                b.appendLine("    suspend fun ${api.name}(id: Int, select: String? = null): $ret {")
                b.appendLine("        val sel = select ?: hint(\"${api.name}\")")
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf(\"id\" to id, \"\\\$select\" to sel))")
                emitDecode()
                b.appendLine("    }\n")
            }
            api.name.startsWith("list") -> {
                b.appendLine("    suspend fun ${api.name}(page: Int? = null, pageSize: Int? = null, select: String? = null): $ret {")
                b.appendLine("        val sel = select ?: hint(\"${api.name}\")")
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf(\"page\" to page, \"pageSize\" to pageSize, \"\\\$select\" to sel))")
                emitDecode()
                b.appendLine("    }\n")
            }
            api.name.startsWith("create") && api.returnType != null -> {
                b.appendLine("    suspend fun ${api.name}(input: Map<String, Any?>): $ret {")
                b.appendLine("        val data = transport.call(\"${api.name}\", input)")
                emitDecode()
                b.appendLine("    }\n")
            }
            api.name.startsWith("update") && api.returnType != null -> {
                b.appendLine("    suspend fun ${api.name}(id: Int, input: Map<String, Any?>): $ret {")
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf(\"id\" to id) + input)")
                emitDecode()
                b.appendLine("    }\n")
            }
            api.name.startsWith("delete") -> {
                b.appendLine("    suspend fun ${api.name}(id: Int): Int {")
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf(\"id\" to id))")
                b.appendLine("        return if (data is ByteArray) { val d = LuxoDecoder(data); d.nextField(); d.readInt().toInt() } else (data as JsonElement).jsonPrimitive.int")
                b.appendLine("    }\n")
            }
            api.params.isNotEmpty() -> {
                val ps = api.params.joinToString(", ") { "${it.name}: ${luxoTypeToKt(it.type)}" }
                b.appendLine("    suspend fun ${api.name}($ps): $ret {")
                val paramMap = api.params.joinToString(", ") { "\"${it.name}\" to ${it.name}" }
                b.appendLine("        val data = transport.call(\"${api.name}\", mapOf($paramMap))")
                emitDecode()
                b.appendLine("    }\n")
            }
            else -> {
                b.appendLine("    suspend fun ${api.name}(): $ret {")
                b.appendLine("        val data = transport.call(\"${api.name}\")")
                emitDecode()
                b.appendLine("    }\n")
            }
        }

        // Private decode helper — dispatches JSON vs binary
        genDecodeHelper(b, api)
    }

    private fun genDecodeHelper(b: StringBuilder, api: LuxoAPI) {
        val ret = returnType(api)
        val t = api.returnType
        b.appendLine("    private fun decode_${api.name}(data: Any): $ret = when (data) {")

        if (t == null || isScalar(t)) {
            // Scalar decode
            val jsonDecode = when (t) {
                null, "Int", "Duration" -> "(data as JsonElement).jsonPrimitive.int"
                "Float" -> "(data as JsonElement).jsonPrimitive.double"
                "Boolean" -> "(data as JsonElement).jsonPrimitive.boolean"
                else -> "(data as JsonElement).jsonPrimitive.content"
            }
            val binaryDecode = when (t) {
                null, "Int", "Duration" -> "LuxoDecoder(data).let { d -> d.nextField(); d.readInt().toInt() }"
                "Float" -> "LuxoDecoder(data).let { d -> d.nextField(); d.readFloat() }"
                "Boolean" -> "LuxoDecoder(data).let { d -> d.nextField(); d.readBool() }"
                else -> "LuxoDecoder(data).let { d -> d.nextField(); d.readString() }"
            }
            b.appendLine("        is ByteArray -> $binaryDecode")
            b.appendLine("        else -> $jsonDecode")
        } else {
            // Model decode
            val jsonDecode = when {
                api.paginated -> "Json.decodeFromJsonElement<Page<$t>>(data as JsonElement)"
                api.returnList -> "Json.decodeFromJsonElement<List<$t>>(data as JsonElement)"
                else -> "Json.decodeFromJsonElement<$t>(data as JsonElement)"
            }
            val binaryDecode = "decode$t(LuxoDecoder(data))"
            b.appendLine("        is ByteArray -> $binaryDecode")
            b.appendLine("        else -> $jsonDecode")
        }

        b.appendLine("    }\n")
    }

    private fun returnType(api: LuxoAPI): String {
        if (api.returnType == null) return "Int"
        val t = luxoTypeToKt(api.returnType!!)
        return when {
            api.paginated -> "Page<$t>"
            api.returnList -> "List<$t>"
            else -> t
        }
    }
}

/** CLI entry point for gradle JavaExec task. */
object LuxoCodegenCli {
    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size >= 2) { "Usage: LuxoCodegenCli <endpoint> <key> [outDir] [package]" }
        val endpoint = args[0]
        val key = args[1]
        val outDir = args.getOrElse(2) { "src/main/kotlin/com/luxo/generated" }
        val pkg = args.getOrElse(3) { "com.luxo.generated" }
        LuxoCodegen.generate(endpoint, key, outDir, pkg)
    }
}
