package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/light-speak/luxo/pkg/codegen"
	"github.com/light-speak/luxo/pkg/lux"
	"github.com/light-speak/luxo/pkg/lux/env"
	"github.com/light-speak/luxo/pkg/lux/pg"
	"github.com/light-speak/luxo/pkg/semantic"
	"github.com/spf13/cobra"
)

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Database migration commands / 数据库迁移命令",
	Long: `Manage database migrations.
管理数据库迁移。

Commands / 子命令:
  diff [name]    Generate migration from schema changes / 从 schema 变更生成迁移
  up             Apply pending migrations / 执行未执行的迁移
  status         Show migration status / 查看迁移状态`,
}

var migrateDiffCmd = &cobra.Command{
	Use:   "diff [name]",
	Short: "Generate migration SQL from schema diff / 从 schema 差异生成迁移 SQL",
	Long: `Compare current .luxo schema with the last migration state and generate SQL.
对比当前 .luxo schema 和上次迁移状态，生成差异 SQL。

Dangerous operations (DROP TABLE, DROP COLUMN) are commented out by default.
破坏性操作（DROP TABLE、DROP COLUMN）默认注释掉。

Example / 示例:
  luxo migrate diff
  luxo migrate diff add_user_avatar`,
	Args: cobra.MaximumNArgs(1),
	RunE: runMigrateDiff,
}

var migrateUpCmd = &cobra.Command{
	Use:   "up",
	Short: "Apply pending migrations / 执行未执行的迁移",
	Args:  cobra.NoArgs,
	RunE:  runMigrateUp,
}

var migrateStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show migration status / 查看迁移状态",
	Args:  cobra.NoArgs,
	RunE:  runMigrateStatus,
}

func init() {
	migrateCmd.AddCommand(migrateDiffCmd)
	migrateCmd.AddCommand(migrateUpCmd)
	migrateCmd.AddCommand(migrateStatusCmd)
	rootCmd.AddCommand(migrateCmd)
}

func runMigrateDiff(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	bold := "\033[1m"
	reset := "\033[0m"

	result, err := parseAndAnalyze()
	if err != nil {
		return err
	}

	env.Load(".env")
	dialect := loadDialect()
	enums := codegen.CollectEnumsFromResult(result)
	desired := codegen.ComputeState(result, enums, dialect)

	statePath := filepath.Join("migrations", ".state.json")
	current, err := codegen.LoadState(statePath)
	if err != nil {
		return fmt.Errorf("load state: %w", err)
	}

	ops := codegen.Diff(current, desired)
	if len(ops) == 0 {
		fmt.Printf("\n  %s✓ No changes detected / 无变更%s\n\n", green, reset)
		return nil
	}

	name := codegen.AutoMigrationName(ops)
	if len(args) > 0 {
		name = args[0]
	}

	migrationPath, err := writeMigrationFile(ops, desired, name, dialect)
	if err != nil {
		return err
	}

	if err := codegen.SaveState(statePath, desired); err != nil {
		return err
	}

	fmt.Printf("\n  %s%s✓ Migration generated / 迁移已生成%s\n\n", bold, green, reset)
	fmt.Printf("  %s+%s %s\n", green, reset, migrationPath)
	printDiffOps(ops)
	fmt.Println()
	return nil
}

func parseAndAnalyze() (*semantic.Result, error) {
	schemaFiles, err := findSchemaFiles()
	if err != nil {
		return nil, err
	}
	files, err := parseAllFiles(schemaFiles)
	if err != nil {
		return nil, err
	}
	return analyzeFiles(files)
}

func writeMigrationFile(ops []codegen.DiffOp, desired *codegen.SchemaState, name string, dialect lux.Dialect) (string, error) {
	up, down := codegen.GenerateMigrationSQL(ops, desired, dialect)

	seq := nextMigrationSeq()
	fileName := fmt.Sprintf("%s_%03d_%s.sql", time.Now().Format("20060102"), seq, name)

	if err := os.MkdirAll("migrations", 0755); err != nil {
		return "", err
	}
	path := filepath.Join("migrations", fileName)

	var content strings.Builder
	content.WriteString("-- Migration: " + name + "\n")
	content.WriteString("-- Generated by luxo migrate diff\n\n")
	content.WriteString("-- ====== UP ======\n\n")
	content.WriteString(up)
	content.WriteString("\n-- ====== DOWN ======\n\n")
	content.WriteString(down)

	return path, os.WriteFile(path, []byte(content.String()), 0644)
}

func printDiffOps(ops []codegen.DiffOp) {
	green := "\033[32m"
	yellow := "\033[33m"
	dim := "\033[2m"
	reset := "\033[0m"

	for _, op := range ops {
		switch op.Kind {
		case codegen.CreateTable:
			fmt.Printf("    %sCREATE TABLE%s %s\n", green, reset, op.Table)
		case codegen.DropTable:
			fmt.Printf("    %sDROP TABLE%s   %s %s(commented out)%s\n", yellow, reset, op.Table, dim, reset)
		case codegen.AddColumn:
			fmt.Printf("    %sADD COLUMN%s   %s.%s\n", green, reset, op.Table, op.Column)
		case codegen.DropColumn:
			fmt.Printf("    %sDROP COLUMN%s  %s.%s %s(commented out)%s\n", yellow, reset, op.Table, op.Column, dim, reset)
		case codegen.AlterColumn:
			fmt.Printf("    %sALTER COLUMN%s %s.%s\n", yellow, reset, op.Table, op.Column)
		case codegen.AddIndex:
			fmt.Printf("    %sADD INDEX%s    %s\n", green, reset, op.Index.Name)
		case codegen.DropIndex:
			fmt.Printf("    %sDROP INDEX%s   %s\n", yellow, reset, op.Index.Name)
		}
	}
}

func runMigrateUp(cmd *cobra.Command, args []string) error {
	fmt.Println("luxo migrate up is not yet implemented / luxo migrate up 尚未实现")
	fmt.Println("For now, apply the generated SQL manually / 目前请手动执行生成的 SQL")
	return nil
}

func runMigrateStatus(cmd *cobra.Command, args []string) error {
	entries, err := filepath.Glob("migrations/*.sql")
	if err != nil || len(entries) == 0 {
		fmt.Println("  No migrations found / 未找到迁移文件")
		return nil
	}

	sort.Strings(entries)
	for _, e := range entries {
		name := filepath.Base(e)
		fmt.Printf("  %s\n", name)
	}
	return nil
}

// loadDialect returns the SQL dialect based on DATABASE_DRIVER env.
func loadDialect() lux.Dialect {
	driver, _ := env.Get("DATABASE_DRIVER")
	switch driver {
	case "mysql":
		fmt.Fprintf(os.Stderr, "warning: MySQL dialect not yet implemented, using pg\n")
		return pg.Dialect{}
	default:
		return pg.Dialect{}
	}
}

func nextMigrationSeq() int {
	entries, err := filepath.Glob("migrations/*.sql")
	if err != nil {
		return 1
	}
	return len(entries) + 1
}
