package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/light-speak/luxo/pkg/codegen"
	"github.com/light-speak/luxo/pkg/lux"
	"github.com/light-speak/luxo/pkg/lux/env"
	"github.com/light-speak/luxo/pkg/lux/migrate"
	"github.com/light-speak/luxo/pkg/lux/pg"
	"github.com/light-speak/luxo/pkg/semantic"
	"github.com/spf13/cobra"
)

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Database migration commands / 数据库迁移命令",
	Long: `Manage database migrations.
管理数据库迁移。

Commands / 子命令:
  diff [name]    Generate migration from origin changes / 从 origin 变更生成迁移
  up             Apply pending migrations / 执行未执行的迁移
  status         Show migration status / 查看迁移状态`,
}

var migrateDiffCmd = &cobra.Command{
	Use:   "diff [name]",
	Short: "Generate migration SQL from origin diff / 从 origin 差异生成迁移 SQL",
	Long: `Compare current .luxo origin with the last migration state and generate SQL.
对比当前 .luxo origin 和上次迁移状态，生成差异 SQL。

Dangerous operations (DROP TABLE, DROP COLUMN) are commented out by default.
破坏性操作（DROP TABLE、DROP COLUMN）默认注释掉。

Example / 示例:
  luxo migrate diff
  luxo migrate diff add_user_avatar`,
	Args: cobra.MaximumNArgs(1),
	RunE: runMigrateDiff,
}

var migrateUpCmd = &cobra.Command{
	Use:   "up",
	Short: "Apply pending migrations / 执行未执行的迁移",
	Args:  cobra.NoArgs,
	RunE:  runMigrateUp,
}

var migrateDownCmd = &cobra.Command{
	Use:   "down [N]",
	Short: "Rollback last N migrations (default 1) / 回滚最近 N 次迁移（默认 1）",
	Args:  cobra.MaximumNArgs(1),
	RunE:  runMigrateDown,
}

var migrateStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show migration status / 查看迁移状态",
	Args:  cobra.NoArgs,
	RunE:  runMigrateStatus,
}

var migrateVerifyCmd = &cobra.Command{
	Use:   "verify",
	Short: "Verify DB matches expected origin / 验证数据库与预期 origin 一致",
	Args:  cobra.NoArgs,
	RunE:  runMigrateVerify,
}

var migrateSquashCmd = &cobra.Command{
	Use:   "squash",
	Short: "Squash all migrations into one / 合并所有迁移为一个",
	Args:  cobra.NoArgs,
	RunE:  runMigrateSquash,
}

func init() {
	migrateCmd.AddCommand(migrateDiffCmd)
	migrateCmd.AddCommand(migrateUpCmd)
	migrateCmd.AddCommand(migrateDownCmd)
	migrateCmd.AddCommand(migrateStatusCmd)
	migrateCmd.AddCommand(migrateVerifyCmd)
	migrateCmd.AddCommand(migrateSquashCmd)
	rootCmd.AddCommand(migrateCmd)
}

func runMigrateDiff(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	bold := "\033[1m"
	reset := "\033[0m"

	result, err := parseAndAnalyze()
	if err != nil {
		return err
	}

	env.Load(".env")
	dialect := loadDialect()
	enums := codegen.CollectEnumsFromResult(result)
	desired := codegen.ComputeState(result, enums, dialect)

	statePath := filepath.Join("migrations", ".state.json")
	current, err := codegen.LoadState(statePath)
	if err != nil {
		return fmt.Errorf("load state: %w", err)
	}

	ops := codegen.Diff(current, desired, nil) // TODO: pass field ID maps for rename detection
	if len(ops) == 0 {
		fmt.Printf("\n  %s✓ No changes detected / 无变更%s\n\n", green, reset)
		return nil
	}

	name := codegen.AutoMigrationName(ops)
	if len(args) > 0 {
		name = args[0]
	}

	migrationPath, err := writeMigrationFile(ops, desired, name, dialect)
	if err != nil {
		return err
	}

	if err := codegen.SaveState(statePath, desired); err != nil {
		return err
	}

	fmt.Printf("\n  %s%s✓ Migration generated / 迁移已生成%s\n\n", bold, green, reset)
	fmt.Printf("  %s+%s %s\n", green, reset, migrationPath)
	printDiffOps(ops)
	fmt.Println()
	return nil
}

func parseAndAnalyze() (*semantic.Result, error) {
	originFiles, err := findSchemaFiles()
	if err != nil {
		return nil, err
	}
	files, err := parseAllFiles(originFiles)
	if err != nil {
		return nil, err
	}
	return analyzeFiles(files)
}

func writeMigrationFile(ops []codegen.DiffOp, desired *codegen.SchemaState, name string, dialect lux.Dialect) (string, error) {
	up, down := codegen.GenerateMigrationSQL(ops, desired, dialect)

	seq := nextMigrationSeq()
	fileName := fmt.Sprintf("%s_%03d_%s.sql", time.Now().Format("20060102"), seq, name)

	if err := os.MkdirAll("migrations", 0755); err != nil {
		return "", err
	}
	path := filepath.Join("migrations", fileName)

	var content strings.Builder
	content.WriteString("-- Migration: " + name + "\n")
	content.WriteString("-- Generated by luxo migrate diff\n\n")
	content.WriteString("-- ====== UP ======\n\n")
	content.WriteString(up)
	content.WriteString("\n-- ====== DOWN ======\n\n")
	content.WriteString(down)

	return path, os.WriteFile(path, []byte(content.String()), 0644)
}

func printDiffOps(ops []codegen.DiffOp) {
	green := "\033[32m"
	cyan := "\033[36m"
	yellow := "\033[33m"
	red := "\033[31m"
	dim := "\033[2m"
	reset := "\033[0m"

	for _, op := range ops {
		switch op.Kind {
		case codegen.CreateTable:
			fmt.Printf("    %sCREATE TABLE%s  %s\n", green, reset, op.Table)
		case codegen.DropTable:
			fmt.Printf("    %sDROP TABLE%s    %s %s(commented out)%s\n", red, reset, op.Table, dim, reset)
		case codegen.AddColumn:
			fmt.Printf("    %sADD COLUMN%s    %s.%s\n", green, reset, op.Table, op.Column)
		case codegen.DropColumn:
			fmt.Printf("    %sDROP COLUMN%s   %s.%s %s(commented out)%s\n", red, reset, op.Table, op.Column, dim, reset)
		case codegen.RenameColumn:
			fmt.Printf("    %sRENAME COLUMN%s %s.%s → %s\n", cyan, reset, op.Table, op.OldName, op.Column)
		case codegen.AlterColumn:
			fmt.Printf("    %sALTER COLUMN%s  %s.%s\n", yellow, reset, op.Table, op.Column)
		case codegen.AddIndex:
			fmt.Printf("    %sADD INDEX%s     %s\n", green, reset, op.Index.Name)
		case codegen.DropIndex:
			fmt.Printf("    %sDROP INDEX%s    %s\n", yellow, reset, op.Index.Name)
		}
		if op.Warning != "" {
			fmt.Printf("      %s⚠ %s%s\n", yellow, op.Warning, reset)
		}
	}
}

func runMigrateUp(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	bold := "\033[1m"
	dim := "\033[2m"
	reset := "\033[0m"

	env.Load(".env")
	ctx := cmd.Context()

	runner, err := migrate.New(ctx, "migrations")
	if err != nil {
		return fmt.Errorf("connect: %w", err)
	}
	defer runner.Close()

	executed, err := runner.Up(ctx)
	if err != nil {
		return fmt.Errorf("migrate up: %w", err)
	}

	if len(executed) == 0 {
		fmt.Printf("\n  %s✓ No pending migrations / 无待执行的迁移%s\n\n", green, reset)
		return nil
	}

	fmt.Printf("\n  %s%s✓ %d migration(s) applied / 已执行 %d 个迁移%s\n\n", bold, green, len(executed), len(executed), reset)
	for _, name := range executed {
		fmt.Printf("  %s✓%s %s%s%s\n", green, reset, dim, name, reset)
	}
	fmt.Println()
	return nil
}

func runMigrateDown(cmd *cobra.Command, args []string) error {
	yellow := "\033[33m"
	bold := "\033[1m"
	dim := "\033[2m"
	reset := "\033[0m"

	n := 1
	if len(args) > 0 {
		fmt.Sscanf(args[0], "%d", &n)
	}

	env.Load(".env")
	ctx := cmd.Context()

	runner, err := migrate.New(ctx, "migrations")
	if err != nil {
		return fmt.Errorf("connect: %w", err)
	}
	defer runner.Close()

	rolledBack, err := runner.Down(ctx, n)
	if err != nil {
		return fmt.Errorf("migrate down: %w", err)
	}

	if len(rolledBack) == 0 {
		fmt.Printf("\n  %s✓ No migrations to rollback / 无可回滚的迁移%s\n\n", yellow, reset)
		return nil
	}

	fmt.Printf("\n  %s%s✓ %d migration(s) rolled back / 已回滚 %d 个迁移%s\n\n", bold, yellow, len(rolledBack), len(rolledBack), reset)
	for _, name := range rolledBack {
		fmt.Printf("  %s↩%s %s%s%s\n", yellow, reset, dim, name, reset)
	}
	fmt.Println()
	return nil
}

func runMigrateStatus(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	dim := "\033[2m"
	yellow := "\033[33m"
	reset := "\033[0m"

	env.Load(".env")
	ctx := cmd.Context()

	runner, err := migrate.New(ctx, "migrations")
	if err != nil {
		return fmt.Errorf("connect: %w", err)
	}
	defer runner.Close()

	statuses, err := runner.Status(ctx)
	if err != nil {
		return err
	}

	if len(statuses) == 0 {
		fmt.Println("  No migrations found / 未找到迁移文件")
		return nil
	}

	fmt.Println()
	for _, s := range statuses {
		if s.Applied {
			fmt.Printf("  %s✓%s %s %s%s%s\n", green, reset, s.Name, dim, s.AppliedAt.Format("2006-01-02 15:04:05"), reset)
		} else {
			fmt.Printf("  %s○%s %s %s(pending)%s\n", yellow, reset, s.Name, dim, reset)
		}
	}
	fmt.Println()
	return nil
}

// loadDialect returns the SQL dialect based on DATABASE_DRIVER env.
func loadDialect() lux.Dialect {
	driver, _ := env.Get("DATABASE_DRIVER")
	switch driver {
	case "mysql":
		fmt.Fprintf(os.Stderr, "warning: MySQL dialect not yet implemented, using pg\n")
		return pg.Dialect{}
	default:
		return pg.Dialect{}
	}
}

func nextMigrationSeq() int {
	entries, err := filepath.Glob("migrations/*.sql")
	if err != nil {
		return 1
	}
	return len(entries) + 1
}

func runMigrateVerify(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	red := "\033[31m"
	bold := "\033[1m"
	reset := "\033[0m"

	env.Load(".env")
	ctx := cmd.Context()

	runner, err := migrate.New(ctx, "migrations")
	if err != nil {
		return fmt.Errorf("connect: %w", err)
	}
	defer runner.Close()

	drifts, err := runner.Verify(ctx)
	if err != nil {
		return fmt.Errorf("verify: %w", err)
	}

	if len(drifts) == 0 {
		fmt.Printf("\n  %s%s✓ Database matches expected origin / 数据库与预期 origin 一致%s\n\n", bold, green, reset)
		return nil
	}

	fmt.Printf("\n  %s%s✗ Schema drift detected / 检测到 origin 漂移%s\n\n", bold, red, reset)
	for _, d := range drifts {
		fmt.Printf("  %s•%s %s\n", red, reset, d)
	}
	fmt.Println()
	return fmt.Errorf("%d drift(s) found", len(drifts))
}

func runMigrateSquash(cmd *cobra.Command, args []string) error {
	green := "\033[32m"
	bold := "\033[1m"
	dim := "\033[2m"
	reset := "\033[0m"

	env.Load(".env")
	dialect := loadDialect()

	result, err := parseAndAnalyze()
	if err != nil {
		return err
	}

	enums := codegen.CollectEnumsFromResult(result)
	desired := codegen.ComputeState(result, enums, dialect)

	// Generate fresh CREATE TABLE for all models
	empty := &codegen.SchemaState{Models: make(map[string]*codegen.ModelState)}
	ops := codegen.Diff(empty, desired, nil)
	up, down := codegen.GenerateMigrationSQL(ops, desired, dialect)

	// Write squashed migration
	if err := os.MkdirAll("migrations", 0755); err != nil {
		return err
	}
	fileName := fmt.Sprintf("%s_001_initial.sql", time.Now().Format("20060102"))
	path := filepath.Join("migrations", fileName)

	var content strings.Builder
	content.WriteString("-- Squashed migration: all tables from scratch\n")
	content.WriteString("-- Generated by luxo migrate squash\n\n")
	content.WriteString("-- ====== UP ======\n\n")
	content.WriteString(up)
	content.WriteString("\n-- ====== DOWN ======\n\n")
	content.WriteString(down)

	if err := os.WriteFile(path, []byte(content.String()), 0644); err != nil {
		return err
	}

	// Update state
	statePath := filepath.Join("migrations", ".state.json")
	if err := codegen.SaveState(statePath, desired); err != nil {
		return err
	}

	fmt.Printf("\n  %s%s✓ Migrations squashed / 迁移已合并%s\n\n", bold, green, reset)
	fmt.Printf("  %s+%s %s\n", green, reset, path)
	fmt.Printf("  %sRemove old migration files manually if desired%s\n", dim, reset)
	fmt.Printf("  %s如需删除旧迁移文件请手动操作%s\n\n", dim, reset)
	return nil
}
