import 'dart:async';
import 'package:build/build.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:glob/glob.dart';
// source_gen not needed — using build runner directly
import 'select_analyzer.dart';

/// Build runner builder that scans user code for LuxoClient API calls,
/// traces field access, and generates _select_hints.g.dart.
///
/// Usage in build.yaml:
/// ```yaml
/// targets:
///   $default:
///     builders:
///       luxo_client|select_hints:
///         enabled: true
/// ```
class SelectHintsBuilder implements Builder {
  /// Model field type map from generated types (populated from schema)
  final Map<String, Map<String, String>> modelFields;

  SelectHintsBuilder(this.modelFields);

  @override
  Map<String, List<String>> get buildExtensions => {
        r'lib/$lib$': ['lib/src/luxo/_select_hints.g.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final allHints = <String, FieldNode>{};

    // Scan all .dart files in lib/
    await for (final input in buildStep.findAssets(Glob('lib/**.dart'))) {
      if (input.path.endsWith('.g.dart')) continue;
      if (input.path.contains('/luxo/')) continue;

      final content = await buildStep.readAsString(input);
      final result = parseString(content: content);
      final unit = result.unit;

      final analyzer = SelectAnalyzer(modelFields);
      unit.visitChildren(analyzer);

      for (final entry in analyzer.hints.entries) {
        allHints[entry.key] = entry.value;
      }
    }

    final output = AssetId(
      buildStep.inputId.package,
      'lib/src/luxo/_select_hints.g.dart',
    );

    final code = StringBuffer();
    code.writeln('// GENERATED BY luxo_client. DO NOT EDIT.');
    code.writeln('// Rebuild with: dart run build_runner build\n');
    code.writeln('/// Field access hints — auto-detected from your code.');
    code.writeln('/// Used by LuxoClient to inject \$select for optimal queries.');
    code.writeln('const selectHints = <String, String>{');
    for (final entry in allHints.entries) {
      final select = entry.value.toSelectString();
      if (select.isEmpty) continue;
      code.writeln("  '${entry.key}': '$select',");
    }
    code.writeln('};');

    await buildStep.writeAsString(output, code.toString());
  }
}

/// Factory for build_runner registration.
Builder selectHintsBuilder(BuilderOptions options) {
  // Model fields can be populated from the generated types
  // For now, empty map = accept all field accesses
  return SelectHintsBuilder(<String, Map<String, String>>{});
}
